objects/BU_PH__c.object
<CustomObject>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>BU-PH</relationshipLabel>
        <relationshipName>BU_PH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>Product Hierarchy</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>BU-PH</relationshipLabel>
        <relationshipName>BU_PH</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BU-PH</label>
    <nameField>
        <displayFormat>BUPH-{00000}</displayFormat>
        <label>BU-PH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BU-PH</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ERP_Customer_Material_Key__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used to differentiate the Component and its assosicated values in the record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Price Group</fullName>
                </value>
                <value>
                    <fullName>Material Price Group</fullName>
                </value>
                <value>
                    <fullName>Price List Type</fullName>
                </value>
                <value>
                    <fullName>Sales Office</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Material Group 3</fullName>
                </value>
                <value>
                    <fullName>Material Group 4</fullName>
                </value>
                <value>
                    <fullName>Terms of Payment</fullName>
                </value>
                <value>
                    <fullName>Pricing Exception</fullName>
                </value>
                <value>
                    <fullName>Incoterms</fullName>
                </value>
                <value>
                    <fullName>Sales Type</fullName>
                </value>
                <value>
                    <fullName>Variant</fullName>
                </value>
                <value>
                    <fullName>Sales Order Type</fullName>
                </value>
                <value>
                    <fullName>Sales District</fullName>
                </value>
                <value>
                    <fullName>Material Group 1</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Document Currency</fullName>
                </value>
                <value>
                    <fullName>Material Group 5</fullName>
                </value>
                <value>
                    <fullName>Plant</fullName>
                </value>
                <value>
                    <fullName>Customer Group 4</fullName>
                </value>
                <value>
                    <fullName>Distributor Code</fullName>
                </value>
                <value>
                    <fullName>Shipping Condition</fullName>
                </value>
                <value>
                    <fullName>Sales Order Item</fullName>
                </value>
                <value>
                    <fullName>Value Center</fullName>
                </value>
                <value>
                    <fullName>Ext Matl Grp</fullName>
                </value>
                <value>
                    <fullName>Material Group 2</fullName>
                </value>
                <value>
                    <fullName>Price Zone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ERP Customer - Material Key</label>
    <nameField>
        <displayFormat>CMK-{00000}</displayFormat>
        <label>ERP Customer - Material Key Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Customer - Material Key</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ERP_Pricing_Procedure__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Procedure_Code__c</fullName>
        <label>Pricing Procedure Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Procedure_Description__c</fullName>
        <label>Pricing Procedure Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Cluster__c</fullName>
        <label>SAP Cluster</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Pricing Procedure</label>
    <nameField>
        <displayFormat>ERP_PP-{00000}</displayFormat>
        <label>ERP Pricing Procedure</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Pricing Procedures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Material__c.object
<CustomObject>
    <fields>
        <fullName>ERP_Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Organizational Group object that this Material record belongs to, lookup to Organizational Group</description>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Materials</relationshipLabel>
        <relationshipName>Materials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <description>Name of the concatenation of the 9 Product Hierarchy Levels, does not exist in SAP</description>
        <label>Product Hierarchy</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <recordTypes>
        <fullName>ERP_Material_Extended_Data</fullName>
        <active>true</active>
        <description>ERP Material – Extended Data (Sales Area)</description>
        <label>ERP Material - Extended Data</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Org_Group_ERP_Key__c.object
<CustomObject>
    <fields>
        <fullName>ERP_Cus_Mat_Compt_Key__c</fullName>
        <label>ERP Customer - Material Key</label>
        <referenceTo>ERP_Customer_Material_Key__c</referenceTo>
        <relationshipLabel>Org Group ERP Key</relationshipLabel>
        <relationshipName>Org_Group_ERP_Key</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group Item</label>
        <referenceTo>Organizational_Group_Item__c</referenceTo>
        <relationshipLabel>Org Group ERP Key</relationshipLabel>
        <relationshipName>Org_Group_ERP_Key</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Group ERP Key</label>
    <nameField>
        <displayFormat>OGK-{00000}</displayFormat>
        <label>Org Group Key Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Group ERP Key</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Organizational_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items (Business1)</relationshipLabel>
        <relationshipName>Organizational_Group_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Display_Standardized_Rate__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Standardized Rate</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ERP_Pricing_Procedure__c</fullName>
        <label>ERP Pricing Procedure</label>
        <referenceTo>ERP_Pricing_Procedure__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>BU_Org_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Enable_Variable_Config_Materials__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Variable Config Materials</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Latest_Valid_To_Offset_Cust_Spec__c</fullName>
        <label>Latest Valid To Offset - Cust Spec</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Valid_From_Offset_Cust_Spec__c</fullName>
        <label>Latest Valid From Offset - Cust Spec</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>OrgGroup</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>Organizational_Group_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Organizational Group Item</label>
    <nameField>
        <displayFormat>OGI-{00000}</displayFormat>
        <label>Organizational Group Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ERP_Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>To identify the type of Organizational Group record this is</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ERP</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>Product Hierarchy Master storing all the PH available</description>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH_Code__c</fullName>
        <label>PH Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH_Level__c</fullName>
        <label>PH Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <displayFormat>PH-{00000}</displayFormat>
        <label>Product Hierarchy Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PAMaterialSelection_UT.cls
@isTest
private class PAMaterialSelection_UT {
    static testMethod void paPAMaterialSelectionSAPClusterTestMethod() {
        //PAApprovalWF_UT.paApprovalWFTestMethodPAQuery();  
        //Recordtype recType = [select id,name from Recordtype where name = 'ERP Material - Extended Data'];        
        
        Id recType = Rtype.getIdByDevName('Material__c','ERP_Material_Extended_Data');
        
        OrgGroup__c orgGroup1 = new OrgGroup__c(Business__c='BI EMEA Surfaces');
        OrgGroup__c orgGroup2 = new OrgGroup__c(ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Division_Code__c='02');
        Insert orgGroup1;
        Insert orgGroup2;
        
        
        ERP_Pricing_Procedure__c priProcedure = new ERP_Pricing_Procedure__c(Pricing_Procedure_Code__c='DA640',Pricing_Procedure_Description__c='BI EMEA Surfaces',SAP_Cluster__c='Q80');
        Insert priProcedure;
        
        Organizational_Group_Item__c orgGroupItem = new Organizational_Group_Item__c(Business__c=orgGroup1.id,OrgGroup__c=orgGroup2.id,ERP_Pricing_Procedure__c=priProcedure.id,Enable_Variable_Config_Materials__c=false);
        Insert orgGroupItem;
        Product_Hierarchy__c ph = new Product_Hierarchy__c(PH_Code__c='A123',PH_Level__c=2);
        insert ph;
        Product_Hierarchy__c ph1 = new Product_Hierarchy__c(PH_Code__c='A6',PH_Level__c=1);
        insert ph1;
        BU_PH__c buph = new BU_PH__c(OrgGroup__c=orgGroup1.id,Product_Hierarchy__c=ph.id);
        Insert buph;
        BU_PH__c buph1 = new BU_PH__c(OrgGroup__c=orgGroup1.id,Product_Hierarchy__c=ph1.id);
        Insert buph1;
        ERP_Customer_Material_Key__c cmKey1 = new ERP_Customer_Material_Key__c(Code__c='M3',Type__c='Material Group 3');
        insert cmKey1;
        ERP_Customer_Material_Key__c cmKey2 = new ERP_Customer_Material_Key__c(Code__c='M4',Type__c='Material Group 4');
        insert cmKey2;
        ERP_Customer_Material_Key__c cmKey3 = new ERP_Customer_Material_Key__c(Code__c='M5',Type__c='Material Group 5');
        insert cmKey3;
        Org_Group_ERP_Key__c ogKey1 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey1.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey1;
        Org_Group_ERP_Key__c ogKey2 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey2.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey2;
        Org_Group_ERP_Key__c ogKey3 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey3.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey3;
        PAMaterialSelection matSelObj = new PAMaterialSelection();
        matselobj.PHClause='';
        matselobj.q='';
        matselobj.totalRecords=10;
        matselobj.label=''; 
        matSelObj.materialCodeFromPage = 'D123';
        
        
    /*  List<Organizational_Group_Item__c>  buOrgGroup = [SELECT ERP_Pricing_Procedure__c,Max_Valid_From_Offset_Cust_Spec__c,
                                                          Display_Standardized_Rate__c,Latest_Valid_To_Offset_Cust_Spec__c,Latest_Valid_From_Offset_Non_Cust_Spec__c,
                                                          Retroactive_Limit__c,Enable_Variable_Config_Materials__c,Business__r.Business__c FROM
                                                          Organizational_Group_Item__c WHERE OrgGroup__r.Business__c =:'BI EMEA Surfaces'AND
                                                          OrgGroup__r.ERP_Sales_Org_Code__c =:'A640' AND
                                                          OrgGroup__r.ERP_Distribution_Channel_Code__c =:'10' AND
                                                          OrgGroup__r.ERP_Division_Code__c =:'02']; 
                                                          
               System.debug('buOrgGroup'+buOrgGroup);
               
           Insert buOrgGroup; */
           
        
         // matSelObj.enableVarConfigMaterial=true;
           
        //matSelObj.selectedBUFromPage='BI EMEA Surfaces';  
        
        Material__c matObj2 = new Material__c(Name='Corian Sheet',ERP_Material_Code__c='D12345678',ERP_Source_Cluster__c='Q80',ERP_Deletion_Flag__c=false,ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Profit_Center_4_Code__c='A612',ERP_Product_Hierarchy_Code__c='A6',RecordTypeId=recType);
        insert matObj2;
        
        Material__c matObj1 = new Material__c(Name='Corian Sheet',ERP_Product_Hierarchy_Code__c='A6');
        insert matObj1;
        
        
        matSelObj.salesOrgCode = 'A641';
        matSelObj.distiCode = '10';
        matSelObj.divCode = '02';
        matSelObj.sourceCluster = 'CB1';
        matSelObj.selectedBUFromPage = orgGroup1.id;
        matSelObj = new PAMaterialSelection();
        matselobj.PHClause='';
        matselobj.q='';
        matselobj.totalRecords=10;
        matselobj.label=''; 
        matSelObj.materialCodeFromPage = 'D123';        
        
        matSelObj.salesOrgCode = 'A641';
        matSelObj.distiCode = '10';
        matSelObj.divCode = '02';
        matSelObj.sourceCluster = 'CB1';
        matSelObj.selectedBUFromPage = orgGroup1.id;
        matSelObj.displayPopUpWindow();
        matSelObj.materialCodeFromPage = null;
        matSelObj.displayPopUpWindow();
        
        matSelObj.desiredAction = 'selectAll';
        matSelObj.dosearch();
        matSelObj.filter_materialCode = 'D1';
        matSelObj.dosearch();
        matSelObj.filter_material = 'D';
        matSelObj.from_filter_PH = 'A6################';
        matSelObj.from_filter_FRB = 'A612';
        matSelObj.heighestFRBLevel = 4;
        
        matSelObj.dosearch();
        matSelObj.offsetfromPage= 300;
        matSelObj.dosearchwithOffsetBack();
        matSelObj.dosearchwithOffset();
        PAMaterialSelection.materialWrapper matWrap = new PAMaterialSelection.materialWrapper();
        matWrap.isSelected = true;
        matWrap.materialObj = matObj2;
        matSelObj.materialWrapperList.add(matWrap);
        matSelObj.returnMaterials();
        
        matSelObj.listOfMaterials = new List<Material__c>();
        matSelObj.listOfMaterials.add(matObj1);
        matSelObj.listOfMaterials.add(matObj2);
        matSelObj.noOfRecordsAPage = 1;
    
        matSelObj.closeMaterialPopUpWindow();      
        matSelObj.firstPage();
        matSelObj.nextPage();
        matSelObj.lastPage();
        matSelObj.noOfRecordsAPage = 3;
        matSelObj.incrementer = 4;
        matSelObj.previousPage();
        matSelObj.selectAllFlag =true;
        matSelObj.action();
        matSelObj.selectAllFlag =false;
        matSelObj.action();
        matSelObj.displayPopUpWindow();
        matSelObj.materialCodeFromPage = 'D123';
        matSelObj.displayPopUpWindow();
        matSelObj.dosearch();
        matSelObj.saveandClose();
        matSelObj.saveandContinue();
        
        
        List<Material__c> matList = new List<Material__c>();
        for(Integer i=0;i<205;i++) {
            Material__c matObj = new Material__c(Name='Corian Sheet'+i,ERP_Material_Code__c='D123456'+i,ERP_Source_Cluster__c='Q80',ERP_Deletion_Flag__c=false,ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Profit_Center_4_Code__c='A612',ERP_Product_Hierarchy_Code__c='A6',RecordTypeId=recType);
            matList.add(matObj);
        }
        insert matList;
        matSelObj.materialCodeFromPage = 'D';
        matSelObj.displayPopUpWindow();
        matSelObj.dosearch();
        matSelObj.filter_materialCode =null;
        matSelObj.dosearch();
        matSelObj.returnData();
        matSelObj.closeWindow();
        matSelObj.incrementer = 50;
        matSelObj.noOfRecordsAPage = 3;
        matSelObj.nextPage();
        List<SelectOption> a1 = matSelObj.MaterialGroup4;
        a1 = matSelObj.MaterialGroup3;
        /*List<SelectOption> a2 = matSelObj.MaterialGroup5;
        a2 = matSelObj.MaterialGroup5;*/
    }
    
    static testMethod void paPAMaterialSelectionTestMethod() {
        //PAApprovalWF_UT.paApprovalWFTestMethodPAQuery();  
        //Recordtype recType = [select id,name from Recordtype where name = 'ERP Material - Extended Data'];        
        
        Id recType = Rtype.getIdByDevName('Material__c','ERP_Material_Extended_Data');
        
        OrgGroup__c orgGroup1 = new OrgGroup__c(Business__c='BI EMEA Surfaces');
        OrgGroup__c orgGroup2 = new OrgGroup__c(ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Division_Code__c='02');
        Insert orgGroup1;
        Insert orgGroup2;
        
        
        ERP_Pricing_Procedure__c priProcedure = new ERP_Pricing_Procedure__c(Pricing_Procedure_Code__c='DA640',Pricing_Procedure_Description__c='BI EMEA Surfaces',SAP_Cluster__c='CB1');
        Insert priProcedure;
        
        Organizational_Group_Item__c orgGroupItem = new Organizational_Group_Item__c(Business__c=orgGroup1.id,OrgGroup__c=orgGroup2.id,ERP_Pricing_Procedure__c=priProcedure.id,Enable_Variable_Config_Materials__c=true);
        Insert orgGroupItem;
        Product_Hierarchy__c ph = new Product_Hierarchy__c(PH_Code__c='A123',PH_Level__c=2);
        insert ph;
        Product_Hierarchy__c ph1 = new Product_Hierarchy__c(PH_Code__c='A6',PH_Level__c=1);
        insert ph1;
        BU_PH__c buph = new BU_PH__c(OrgGroup__c=orgGroup1.id,Product_Hierarchy__c=ph.id);
        Insert buph;
        BU_PH__c buph1 = new BU_PH__c(OrgGroup__c=orgGroup1.id,Product_Hierarchy__c=ph1.id);
        Insert buph1;
        ERP_Customer_Material_Key__c cmKey1 = new ERP_Customer_Material_Key__c(Code__c='M3',Type__c='Material Group 3');
        insert cmKey1;
        ERP_Customer_Material_Key__c cmKey2 = new ERP_Customer_Material_Key__c(Code__c='M4',Type__c='Material Group 4');
        insert cmKey2;
        ERP_Customer_Material_Key__c cmKey3 = new ERP_Customer_Material_Key__c(Code__c='M5',Type__c='Material Group 5');
        insert cmKey3;
        Org_Group_ERP_Key__c ogKey1 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey1.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey1;
        Org_Group_ERP_Key__c ogKey2 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey2.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey2;
        Org_Group_ERP_Key__c ogKey3 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey3.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey3;
        PAMaterialSelection matSelObj = new PAMaterialSelection();
        matselobj.PHClause='';
        matselobj.q='';
        matselobj.totalRecords=10;
        matselobj.label=''; 
        matSelObj.materialCodeFromPage = 'D123';
        
        
    /*  List<Organizational_Group_Item__c>  buOrgGroup = [SELECT ERP_Pricing_Procedure__c,Max_Valid_From_Offset_Cust_Spec__c,
                                                          Display_Standardized_Rate__c,Latest_Valid_To_Offset_Cust_Spec__c,Latest_Valid_From_Offset_Non_Cust_Spec__c,
                                                          Retroactive_Limit__c,Enable_Variable_Config_Materials__c,Business__r.Business__c FROM
                                                          Organizational_Group_Item__c WHERE OrgGroup__r.Business__c =:'BI EMEA Surfaces'AND
                                                          OrgGroup__r.ERP_Sales_Org_Code__c =:'A640' AND
                                                          OrgGroup__r.ERP_Distribution_Channel_Code__c =:'10' AND
                                                          OrgGroup__r.ERP_Division_Code__c =:'02']; 
                                                          
               System.debug('buOrgGroup'+buOrgGroup);
               
           Insert buOrgGroup; */
           
        
         // matSelObj.enableVarConfigMaterial=true;
           
        //matSelObj.selectedBUFromPage='BI EMEA Surfaces';  
        
        Material__c matObj2 = new Material__c(Name='Corian Sheet',ERP_Material_Code__c='D12345678',ERP_Source_Cluster__c='CB1',ERP_Deletion_Flag__c=false,ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Profit_Center_4_Code__c='A612',ERP_Product_Hierarchy_Code__c='A6',RecordTypeId=recType);
        insert matObj2;
        
        Material__c matObj1 = new Material__c(Name='Corian Sheet',ERP_Product_Hierarchy_Code__c='A6');
        insert matObj1;
        
        
        matSelObj.salesOrgCode = 'A641';
        matSelObj.distiCode = '10';
        matSelObj.divCode = '02';
        matSelObj.sourceCluster = 'CB1';
        matSelObj.selectedBUFromPage = orgGroup1.id;
        matSelObj = new PAMaterialSelection();
        matselobj.PHClause='';
        matselobj.q='';
        matselobj.totalRecords=10;
        matselobj.label=''; 
        matSelObj.materialCodeFromPage = 'D123';        
        
        matSelObj.salesOrgCode = 'A641';
        matSelObj.distiCode = '10';
        matSelObj.divCode = '02';
        matSelObj.sourceCluster = 'CB1';
        matSelObj.selectedBUFromPage = orgGroup1.id;
        matSelObj.displayPopUpWindow();
        matSelObj.materialCodeFromPage = null;
        matSelObj.displayPopUpWindow();
        
        matSelObj.desiredAction = 'selectAll';
        matSelObj.dosearch();
        matSelObj.filter_materialCode = 'D1';
        matSelObj.dosearch();
        matSelObj.filter_material = 'D';
        matSelObj.from_filter_PH = 'A6################';
        matSelObj.from_filter_FRB = 'A612';
        matSelObj.heighestFRBLevel = 4;
        
        matSelObj.dosearch();
        matSelObj.offsetfromPage= 300;
        matSelObj.dosearchwithOffsetBack();
        matSelObj.dosearchwithOffset();
        PAMaterialSelection.materialWrapper matWrap = new PAMaterialSelection.materialWrapper();
        matWrap.isSelected = true;
        matWrap.materialObj = matObj2;
        matSelObj.materialWrapperList.add(matWrap);
        matSelObj.returnMaterials();
        
        matSelObj.listOfMaterials = new List<Material__c>();
        matSelObj.listOfMaterials.add(matObj1);
        matSelObj.listOfMaterials.add(matObj2);
        matSelObj.noOfRecordsAPage = 1;
    
        matSelObj.closeMaterialPopUpWindow();      
        matSelObj.firstPage();
        matSelObj.nextPage();
        matSelObj.lastPage();
        matSelObj.noOfRecordsAPage = 3;
        matSelObj.incrementer = 4;
        matSelObj.previousPage();
        matSelObj.selectAllFlag =true;
        matSelObj.action();
        matSelObj.selectAllFlag =false;
        matSelObj.action();
        matSelObj.displayPopUpWindow();
        matSelObj.materialCodeFromPage = 'D123';
        matSelObj.displayPopUpWindow();
        matSelObj.dosearch();
        matSelObj.saveandClose();
        matSelObj.saveandContinue();
        
        
        List<Material__c> matList = new List<Material__c>();
        for(Integer i=0;i<205;i++) {
            Material__c matObj = new Material__c(Name='Corian Sheet'+i,ERP_Material_Code__c='D123456'+i,ERP_Source_Cluster__c='CB1',ERP_Deletion_Flag__c=false,ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Profit_Center_4_Code__c='A612',ERP_Product_Hierarchy_Code__c='A6',RecordTypeId=recType);
            matList.add(matObj);
        }
        insert matList;
        matSelObj.materialCodeFromPage = 'D';
        matSelObj.displayPopUpWindow();
        matSelObj.dosearch();
        matSelObj.filter_materialCode =null;
        matSelObj.dosearch();
        matSelObj.returnData();
        matSelObj.closeWindow();
        matSelObj.incrementer = 50;
        matSelObj.noOfRecordsAPage = 3;
        matSelObj.nextPage();
        List<SelectOption> a1 = matSelObj.MaterialGroup4;
        a1 = matSelObj.MaterialGroup3;
        List<SelectOption> a2 = matSelObj.MaterialGroup5;
        a2 = matSelObj.MaterialGroup5;
    }
    static testMethod void paPAMaterialSelectionTestMethod2() {
        //PAApprovalWF_UT.paApprovalWFTestMethodPAQuery();  
        //Recordtype recType = [select id,name from Recordtype where name = 'ERP Material - Extended Data'];        
        
        Id recType = Rtype.getIdByDevName('Material__c','ERP_Material_Extended_Data');
        PAHelpLinks__c link=new PAHelpLinks__c(name='Test',help_link__c='test.com');
        insert link;
        OrgGroup__c orgGroup1 = new OrgGroup__c(Business__c='MCM AP Green Tape');
        OrgGroup__c orgGroup2 = new OrgGroup__c(ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Division_Code__c='02');
        Insert orgGroup1;
        Insert orgGroup2;
        
        
        ERP_Pricing_Procedure__c priProcedure = new ERP_Pricing_Procedure__c(Pricing_Procedure_Code__c='DA640',Pricing_Procedure_Description__c='MCM AP Green Tape',SAP_Cluster__c='CB1');
        Insert priProcedure;
        
        Organizational_Group_Item__c orgGroupItem = new Organizational_Group_Item__c(Business__c=orgGroup1.id,OrgGroup__c=orgGroup2.id,ERP_Pricing_Procedure__c=priProcedure.id,Enable_Variable_Config_Materials__c=false);
        Insert orgGroupItem;
        Product_Hierarchy__c ph = new Product_Hierarchy__c(PH_Code__c='A123',PH_Level__c=2);
        insert ph;
        Product_Hierarchy__c ph1 = new Product_Hierarchy__c(PH_Code__c='A6',PH_Level__c=1);
        insert ph1;
        BU_PH__c buph = new BU_PH__c(OrgGroup__c=orgGroup1.id,Product_Hierarchy__c=ph.id);
        Insert buph;
        BU_PH__c buph1 = new BU_PH__c(OrgGroup__c=orgGroup1.id,Product_Hierarchy__c=ph1.id);
        Insert buph1;
        ERP_Customer_Material_Key__c cmKey1 = new ERP_Customer_Material_Key__c(Code__c='M3',Type__c='Material Group 3');
        insert cmKey1;
        ERP_Customer_Material_Key__c cmKey2 = new ERP_Customer_Material_Key__c(Code__c='M4',Type__c='Material Group 4');
        insert cmKey2;
        ERP_Customer_Material_Key__c cmKey3 = new ERP_Customer_Material_Key__c(Code__c='M5',Type__c='Material Group 5');
        insert cmKey3;
        Org_Group_ERP_Key__c ogKey1 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey1.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey1;
        Org_Group_ERP_Key__c ogKey2 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey2.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey2;
        Org_Group_ERP_Key__c ogKey3 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey3.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey3;
        PAMaterialSelection matSelObj = new PAMaterialSelection();
        matselobj.PHClause='';
        matselobj.q='';
        matselobj.totalRecords=10;
        matselobj.label='Test'; 
        matSelObj.materialCodeFromPage = 'D123';
        
        
    /*  List<Organizational_Group_Item__c>  buOrgGroup = [SELECT ERP_Pricing_Procedure__c,Max_Valid_From_Offset_Cust_Spec__c,
                                                          Display_Standardized_Rate__c,Latest_Valid_To_Offset_Cust_Spec__c,Latest_Valid_From_Offset_Non_Cust_Spec__c,
                                                          Retroactive_Limit__c,Enable_Variable_Config_Materials__c,Business__r.Business__c FROM
                                                          Organizational_Group_Item__c WHERE OrgGroup__r.Business__c =:'BI EMEA Surfaces'AND
                                                          OrgGroup__r.ERP_Sales_Org_Code__c =:'A640' AND
                                                          OrgGroup__r.ERP_Distribution_Channel_Code__c =:'10' AND
                                                          OrgGroup__r.ERP_Division_Code__c =:'02']; 
                                                          
               System.debug('buOrgGroup'+buOrgGroup);
               
           Insert buOrgGroup; */
           
        
         // matSelObj.enableVarConfigMaterial=true;
           
        //matSelObj.selectedBUFromPage='BI EMEA Surfaces';  
        
        Material__c matObj2 = new Material__c(Name='Corian Sheet',ERP_Material_Code__c='D12345678',ERP_Source_Cluster__c='CB1',ERP_Deletion_Flag__c=false,ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Profit_Center_4_Code__c='F423GT',ERP_Product_Hierarchy_Code__c='A6',RecordTypeId=recType);
        insert matObj2;
        
        Material__c matObj1 = new Material__c(Name='Corian Sheet');
        insert matObj1;
        
        
        matSelObj.salesOrgCode = 'A641';
        matSelObj.distiCode = '10';
        matSelObj.divCode = '02';
        matSelObj.sourceCluster = 'CB1';
        matSelObj.selectedBUFromPage = orgGroup1.id;
        
        matSelObj.displayPopUpWindow();
        matSelObj.materialCodeFromPage = null;
        matSelObj.displayPopUpWindow();
        
        matSelObj.desiredAction = 'SaveAndClose';
        matSelObj.dosearch();
        matSelObj.filter_materialCode = 'D1';
        matSelObj.dosearch();
        matSelObj.filter_material = 'D';
        matSelObj.from_filter_PH = 'A6################';
        matSelObj.from_filter_FRB = 'A612';
        matSelObj.heighestFRBLevel = 4;
        
        matSelObj.dosearch();
        matSelObj.offsetfromPage= 300;
        matSelObj.dosearchwithOffsetBack();
        matSelObj.dosearchwithOffset();
        PAMaterialSelection.materialWrapper matWrap = new PAMaterialSelection.materialWrapper();
        matWrap.isSelected = true;
        matWrap.materialObj = matObj2;
        matSelObj.materialWrapperList.add(matWrap);
        matSelObj.returnMaterials();
        
        matSelObj.listOfMaterials = new List<Material__c>();
        matSelObj.listOfMaterials.add(matObj1);
        matSelObj.listOfMaterials.add(matObj2);
        matSelObj.noOfRecordsAPage = 1;
    
        matSelObj.closeMaterialPopUpWindow();      
        matSelObj.firstPage();
        matSelObj.nextPage();
        matSelObj.lastPage();
        matSelObj.noOfRecordsAPage = 3;
        matSelObj.incrementer = 4;
        matSelObj.previousPage();
        matSelObj.selectAllFlag =true;
        matSelObj.action();
        matSelObj.selectAllFlag =false;
        matSelObj.action();
        matSelObj.displayPopUpWindow();
        matSelObj.materialCodeFromPage = 'D123';
        matSelObj.displayPopUpWindow();
        matSelObj.dosearch();
        matSelObj.saveandClose();
        matSelObj.saveandContinue();
        
        
        List<Material__c> matList = new List<Material__c>();
        for(Integer i=0;i<205;i++) {
            Material__c matObj = new Material__c(Name='Corian Sheet'+i,ERP_Material_Code__c='D123456'+i,ERP_Source_Cluster__c='CB1',ERP_Deletion_Flag__c=false,ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Profit_Center_4_Code__c='A612',ERP_Product_Hierarchy_Code__c='F423GT',RecordTypeId=recType);
            matList.add(matObj);
        }
        insert matList;
        matSelObj.materialCodeFromPage = 'D12';
        matSelObj.displayPopUpWindow();
        matSelObj.dosearch();
        matSelObj.filter_materialCode =null;
        matSelObj.dosearch();
        matSelObj.returnData();
        matSelObj.closeWindow();
        matSelObj.incrementer = 50;
        matSelObj.noOfRecordsAPage = 3;
        matSelObj.nextPage();
        List<SelectOption> a1,a2 = matSelObj.MaterialGroup4;
        a1 = matSelObj.MaterialGroup3;
        a2 = a1;
        PageReference pr = new PageReference('');
        pr=matSelObj.helpLink();
    }
    static testMethod void paPAMaterialSelectionTestMethod3() {
        //PAApprovalWF_UT.paApprovalWFTestMethodPAQuery();  
        //Recordtype recType = [select id,name from Recordtype where name = 'ERP Material - Extended Data'];        
        
        Id recType = Rtype.getIdByDevName('Material__c','ERP_Material_Extended_Data');
        
        OrgGroup__c orgGroup1 = new OrgGroup__c(Business__c='MCM AP Paste');
        OrgGroup__c orgGroup2 = new OrgGroup__c(ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Division_Code__c='02');
        Insert orgGroup1;
        Insert orgGroup2;
        
        
        ERP_Pricing_Procedure__c priProcedure = new ERP_Pricing_Procedure__c(Pricing_Procedure_Code__c='DA640',Pricing_Procedure_Description__c='MCM AP Paste',SAP_Cluster__c='CB1');
        Insert priProcedure;
        
        Organizational_Group_Item__c orgGroupItem = new Organizational_Group_Item__c(Business__c=orgGroup1.id,OrgGroup__c=orgGroup2.id,ERP_Pricing_Procedure__c=priProcedure.id,Enable_Variable_Config_Materials__c=false);
        Insert orgGroupItem;
        Product_Hierarchy__c ph = new Product_Hierarchy__c(PH_Code__c='A123',PH_Level__c=2);
        insert ph;
        Product_Hierarchy__c ph1 = new Product_Hierarchy__c(PH_Code__c='A6',PH_Level__c=1);
        insert ph1;
        BU_PH__c buph = new BU_PH__c(OrgGroup__c=orgGroup1.id,Product_Hierarchy__c=ph.id);
        Insert buph;
        BU_PH__c buph1 = new BU_PH__c(OrgGroup__c=orgGroup1.id,Product_Hierarchy__c=ph1.id);
        Insert buph1;
        ERP_Customer_Material_Key__c cmKey1 = new ERP_Customer_Material_Key__c(Code__c='M3',Type__c='Material Group 3');
        insert cmKey1;
        ERP_Customer_Material_Key__c cmKey2 = new ERP_Customer_Material_Key__c(Code__c='M4',Type__c='Material Group 4');
        insert cmKey2;
        ERP_Customer_Material_Key__c cmKey3 = new ERP_Customer_Material_Key__c(Code__c='M5',Type__c='Material Group 5');
        insert cmKey3;
        Org_Group_ERP_Key__c ogKey1 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey1.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey1;
        Org_Group_ERP_Key__c ogKey2 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey2.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey2;
        Org_Group_ERP_Key__c ogKey3 = new Org_Group_ERP_Key__c(ERP_Cus_Mat_Compt_Key__c=cmkey3.Id,Organizational_Group_Item__c=orgGroupItem.Id);
        insert ogKey3;
        PAMaterialSelection matSelObj = new PAMaterialSelection();
        matselobj.PHClause='';
        matselobj.q='';
        matselobj.totalRecords=10;
        matselobj.label=''; 
        matSelObj.materialCodeFromPage = 'D123';
        
        
    /*  List<Organizational_Group_Item__c>  buOrgGroup = [SELECT ERP_Pricing_Procedure__c,Max_Valid_From_Offset_Cust_Spec__c,
                                                          Display_Standardized_Rate__c,Latest_Valid_To_Offset_Cust_Spec__c,Latest_Valid_From_Offset_Non_Cust_Spec__c,
                                                          Retroactive_Limit__c,Enable_Variable_Config_Materials__c,Business__r.Business__c FROM
                                                          Organizational_Group_Item__c WHERE OrgGroup__r.Business__c =:'BI EMEA Surfaces'AND
                                                          OrgGroup__r.ERP_Sales_Org_Code__c =:'A640' AND
                                                          OrgGroup__r.ERP_Distribution_Channel_Code__c =:'10' AND
                                                          OrgGroup__r.ERP_Division_Code__c =:'02']; 
                                                          
               System.debug('buOrgGroup'+buOrgGroup);
               
           Insert buOrgGroup; */
           
        
         // matSelObj.enableVarConfigMaterial=true;
           
        //matSelObj.selectedBUFromPage='BI EMEA Surfaces';  
        
        Material__c matObj2 = new Material__c(Name='Corian Sheet',ERP_Material_Code__c='D12345678',ERP_Source_Cluster__c='CB1',ERP_Deletion_Flag__c=false,ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Profit_Center_4_Code__c='A612',ERP_Product_Hierarchy_Code__c='F423TF',RecordTypeId=recType);
        insert matObj2;
        
        Material__c matObj1 = new Material__c(Name='Corian Sheet');
        insert matObj1;
        
        
        matSelObj.salesOrgCode = 'A641';
        matSelObj.distiCode = '10';
        matSelObj.divCode = '02';
        matSelObj.sourceCluster = 'CB1';
        matSelObj.selectedBUFromPage = orgGroup1.id;
        
        matSelObj.displayPopUpWindow();
        matSelObj.materialCodeFromPage = null;
        matSelObj.displayPopUpWindow();
        
        matSelObj.desiredAction = 'SaveAndContinue';
        matSelObj.dosearch();
        matSelObj.filter_materialCode = 'D1';
        matSelObj.dosearch();
        matSelObj.filter_material = 'D';
        matSelObj.from_filter_PH = 'A6################';
        matSelObj.from_filter_FRB = 'A612';
        matSelObj.heighestFRBLevel = 4;
        
        matSelObj.dosearch();
        matSelObj.offsetfromPage= 300;
        matSelObj.dosearchwithOffsetBack();
        matSelObj.dosearchwithOffset();
        PAMaterialSelection.materialWrapper matWrap = new PAMaterialSelection.materialWrapper();
        matWrap.isSelected = true;
        matWrap.materialObj = matObj2;
        matSelObj.materialWrapperList.add(matWrap);
        matSelObj.returnMaterials();
        
        matSelObj.listOfMaterials = new List<Material__c>();
        matSelObj.listOfMaterials.add(matObj1);
        matSelObj.listOfMaterials.add(matObj2);
        matSelObj.noOfRecordsAPage = 1;
    
        matSelObj.closeMaterialPopUpWindow();      
        matSelObj.firstPage();
        matSelObj.nextPage();
        matSelObj.lastPage();
        matSelObj.noOfRecordsAPage = 3;
        matSelObj.incrementer = 4;
        matSelObj.previousPage();
        matSelObj.selectAllFlag =true;
        matSelObj.action();
        matSelObj.selectAllFlag =false;
        matSelObj.action();
        matSelObj.displayPopUpWindow();
        matSelObj.materialCodeFromPage = 'D123';
        matSelObj.displayPopUpWindow();
        matSelObj.dosearch();
        matSelObj.saveandClose();
        matSelObj.saveandContinue();
        
        
        List<Material__c> matList = new List<Material__c>();
        for(Integer i=0;i<205;i++) {
            Material__c matObj = new Material__c(Name='Corian Sheet'+i,ERP_Material_Code__c='D123456'+i,ERP_Source_Cluster__c='CB1',ERP_Deletion_Flag__c=false,ERP_Sales_Org_Code__c='A641',ERP_Distribution_Channel_Code__c='10',ERP_Profit_Center_4_Code__c='A612',ERP_Product_Hierarchy_Code__c='F423TF',RecordTypeId=recType);
            matList.add(matObj);
        }
        insert matList;
        matSelObj.materialCodeFromPage = 'D';
        matSelObj.displayPopUpWindow();
        matSelObj.dosearch();
        matSelObj.filter_materialCode =null;
        matSelObj.dosearch();
        matSelObj.returnData();
        matSelObj.closeWindow();
        matSelObj.incrementer = 50;
        matSelObj.noOfRecordsAPage = 3;
        matSelObj.nextPage();
        List<SelectOption> a1 = matSelObj.MaterialGroup4;
        a1 = matSelObj.MaterialGroup3;
        List<SelectOption> a2 = matSelObj.MaterialGroup5;
        a2 = a1;
    }
}