objects/BU_PH__c.object
<CustomObject>
    <fields>
        <fullName>Business_Description__c</fullName>
        <label>Business Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Default_Per__c</fullName>
        <label>Default Per</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Default_UOM__c</fullName>
        <label>Default UOM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>BU-PH</relationshipLabel>
        <relationshipName>BU_PH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>Product Hierarchy</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>BU-PH</relationshipLabel>
        <relationshipName>BU_PH</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BU-PH</label>
    <nameField>
        <displayFormat>BUPH-{00000}</displayFormat>
        <label>BU-PH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BU-PH</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>Product Hierarchy Master storing all the PH available</description>
    <fields>
        <fullName>PH_Code__c</fullName>
        <label>PH Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH_Level__c</fullName>
        <label>PH Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <displayFormat>PH-{00000}</displayFormat>
        <label>Product Hierarchy Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PARequestItemHelper.cls
/***********************************************************************************************************************
<TJ20140402>
Last Modified By    :   Tarun Jain
Last Modified Date  :   2 April 2014
Description         :   Class to query and add the Default UOM & Per for a particular Product Hierarchy.
 ***********************************************************************************************************************/
public with sharing class PARequestItemHelper
{   
	public String selectedBU;
	public PARequestItemHelper(String selectBU)
	{
		selectedBU=selectBU;
	}
	//<TJ20140402> -- Queries the BU_PH Data for a Set of PH Codes
	public List<BU_PH__c> query(Set<String> pHCodes)
	{
		system.debug('#@phcodes'+pHCodes+','+selectedBU);
		List<BU_PH__c> buPHData=new List<BU_PH__c>();
		buPHData.clear();
		buPHData=[SELECT Product_Hierarchy__r.PH_Code__c,Business_Description__c,Default_UOM__c,Default_Per__c from BU_PH__c WHERE 
		          Product_Hierarchy__r.PH_Code__c in:pHCodes AND OrgGroup__c =:selectedBU ORDER BY Product_Hierarchy__r.PH_Level__c DESC];
		system.debug('@#BUPHDATA'+buPHData.size());
		return buPHData;
	}
	//<TJ20140402> -- Returns the Default UOM for a PH Code
	public map<String,String> getDefaultUOM(list<BU_PH__c> bu_ph_data)
	{
		Set<String> phSubStr=new Set<String>();
		String uom;
		list<BU_PH__c> default_UOM=new list<BU_PH__c>();
		map<String,String> defaultUOM=new map<String,String>();
		map<String,String> pHUOM=new map<String,String>();
		map<String,Set<String>> phcodesubstring=new map<String,Set<String>>();
		for(Integer i=0;i<bu_ph_data.size();i++)
		{
			for(Integer j=0;j<=bu_ph_data[i].Product_Hierarchy__r.PH_Code__c.length();j=j+2)
			{
				phSubStr.add(bu_ph_data[i].Product_Hierarchy__r.PH_Code__c.substring(0,j));
			}
			phcodesubstring.put(bu_ph_data[i].Product_Hierarchy__r.PH_Code__c,phSubStr);
		}
		default_UOM=query(phSubStr);
		Integer size=bu_ph_data.size();
		for(integer z=0;z<default_UOM.size();z++)
		{   
			if((default_UOM[z].Default_UOM__c!=null))
			{
				uom=default_UOM[z].Default_UOM__c;
				break;
			}
		}
		for(integer i=0;i<size;i++)
		{
			defaultUOM.put(bu_ph_data[i].Product_Hierarchy__r.PH_Code__c,uom);
		}
		system.debug('defaultUOM'+defaultUOM);
		system.debug('uom@@'+uom);
		system.debug('defaultUOMList'+default_UOM);
		return defaultUOM;
	}

	//<TJ20140402> -- Returns the Default Per for a PH Code
	public map<String,decimal> getDefaultPer(list<BU_PH__c> bu_ph_data)
	{
		Set<String> phSubStr=new Set<String>();
		list<BU_PH__c> default_Per=new list<BU_PH__c>();
		map<String,Decimal> defaultPer=new map<String,Decimal>();
		map<String,Decimal> pHPer=new map<String,Decimal>();
		map<String,Set<String>> phcodesubstring=new map<String,Set<String>>();
		decimal per;
		for(Integer i=0;i<bu_ph_data.size();i++)
		{
			for(Integer j=0;j<=bu_ph_data[i].Product_Hierarchy__r.PH_Code__c.length();j=j+2)
			{
				phSubStr.add(bu_ph_data[i].Product_Hierarchy__r.PH_Code__c.substring(0,j));
			}
			phcodesubstring.put(bu_ph_data[i].Product_Hierarchy__r.PH_Code__c,phSubStr);
		}
		default_Per=query(phSubStr);
		Integer size=bu_ph_data.size();
		for(integer z=0;z<default_Per.size();z++)
		{
			if(default_Per[z].Default_Per__c!=null)
			{
				per=default_Per[z].Default_Per__c;
				break;
			}
		}
		for(integer i=0;i<size;i++)
		{
			
			defaultPer.put(bu_ph_data[i].Product_Hierarchy__r.PH_Code__c,per);

		}
		system.debug('defaultPer'+defaultPer);
		return defaultPer; 
	}
}