objects/BU_PH__c.object
<CustomObject>
    <fields>
        <fullName>Business_Description__c</fullName>
        <label>Business Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>BU-PH</relationshipLabel>
        <relationshipName>BU_PH</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>Product Hierarchy</label>
        <referenceTo>Product_Hierarchy__c</referenceTo>
        <relationshipLabel>BU-PH</relationshipLabel>
        <relationshipName>BU_PH</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>BU-PH</label>
    <nameField>
        <displayFormat>BUPH-{00000}</displayFormat>
        <label>BU-PH Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BU-PH</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ERP_Pricing_Procedure__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Procedure_Code__c</fullName>
        <label>Pricing Procedure Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Procedure_Description__c</fullName>
        <label>Pricing Procedure Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Procedure__c</fullName>
        <label>Pricing Procedure</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Application_Id__c</fullName>
        <label>SAP Application Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Client_Id__c</fullName>
        <label>SAP Client Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Cluster__c</fullName>
        <label>SAP Cluster</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Pricing Procedure</label>
    <nameField>
        <displayFormat>ERP_PP-{00000}</displayFormat>
        <label>ERP Pricing Procedure</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Pricing Procedures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Organizational_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items (Business1)</relationshipLabel>
        <relationshipName>Organizational_Group_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Request_Reasons__c</fullName>
        <label>Customer Request Reasons</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CP01-Customer negotiation</fullName>
                </value>
                <value>
                    <fullName>CP02-New customer</fullName>
                </value>
                <value>
                    <fullName>CP03-New materials</fullName>
                </value>
                <value>
                    <fullName>CP04-Competitive pricing</fullName>
                </value>
                <value>
                    <fullName>CP05-Extending current prices</fullName>
                </value>
                <value>
                    <fullName>CP06-Pricing campaign</fullName>
                </value>
                <value>
                    <fullName>CP07-Seasonal price</fullName>
                </value>
                <value>
                    <fullName>CP08-Slow moving inventory</fullName>
                </value>
                <value>
                    <fullName>CP09-Other reason</fullName>
                </value>
                <value>
                    <fullName>CP10-New Application</fullName>
                </value>
                <value>
                    <fullName>CP11-New End Use</fullName>
                </value>
                <value>
                    <fullName>CP12-New Converter</fullName>
                </value>
                <value>
                    <fullName>CP13-New Development Project</fullName>
                </value>
                <value>
                    <fullName>CP14-Price Extension</fullName>
                </value>
                <value>
                    <fullName>CP15-2nd Quality grade</fullName>
                </value>
                <value>
                    <fullName>CP16-Distributor Pricing</fullName>
                </value>
                <value>
                    <fullName>CP17-Change of Incoterm</fullName>
                </value>
                <value>
                    <fullName>CP18-Price increase</fullName>
                </value>
                <value>
                    <fullName>CP19-Gap closer</fullName>
                </value>
                <value>
                    <fullName>CP20-Sales Promotion</fullName>
                </value>
                <value>
                    <fullName>CP21-Key accounts prices</fullName>
                </value>
                <value>
                    <fullName>CP22-HuaMei Pricing</fullName>
                </value>
                <value>
                    <fullName>CP23-Nike OEM Pricing</fullName>
                </value>
                <value>
                    <fullName>CP24-LCL Price</fullName>
                </value>
                <value>
                    <fullName>CP25-Price include airfreight</fullName>
                </value>
                <value>
                    <fullName>CP41-Price include landing and transport</fullName>
                </value>
                <value>
                    <fullName>CP26-Price aligned with PLM guidline</fullName>
                </value>
                <value>
                    <fullName>CP27-Price Decreased</fullName>
                </value>
                <value>
                    <fullName>CP47-Sales Projection 10-30 MT/month</fullName>
                </value>
                <value>
                    <fullName>CP42-Sales Projection 30-60 MT/month</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ERP_Pricing_Procedure__c</fullName>
        <label>ERP Pricing Procedure</label>
        <referenceTo>ERP_Pricing_Procedure__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>BU_Org_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>OrgGroup</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>Organizational_Group_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Organizational Group Item</label>
    <nameField>
        <displayFormat>OGI-{00000}</displayFormat>
        <label>Organizational Group Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Organizational_Group_User__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <formula>Organizational_Group_Item__r.Business__r.Business__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group Item</label>
        <referenceTo>Organizational_Group_Item__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Organizational Group Users</label>
    <nameField>
        <displayFormat>OGU-{00000}</displayFormat>
        <label>Organizational Group User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ERP_Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>The DuPont Business (Business Unit) or legal entity</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PAProfilePermissions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Name__c</fullName>
        <description>Stores the API Name of the permission sets</description>
        <label>API Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name of the profile</description>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PAProfilePermissions</label>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>Product Hierarchy Master storing all the PH available</description>
    <fields>
        <fullName>Business__c</fullName>
        <label>Business</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH_Code__c</fullName>
        <label>PH Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH_Level__c</fullName>
        <label>PH Level</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product Hierarchy</label>
    <nameField>
        <displayFormat>PH-{00000}</displayFormat>
        <label>Product Hierarchy Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PAProductHierarchy_UT.cls
/*
 * Name      :   PAProductHierarchy_UT
 * Description  :   This is the test class for PAProductHierarchy
 * Author      :   Infosys Limited
 * Created Date :   25-03-2013
 *
 * Version    Modified Date    Modified By   Modification
 * ------------------------------------------------------------------------------
 */
@isTest
private class PAProductHierarchy_UT
{
    static testMethod void PAProductHierarchyTestMethod()
    {
        
        List<PAProfilePermissions__c> profilePSList = new List<PAProfilePermissions__c>();
        PAProfilePermissions__c profilePS1 = new PAProfilePermissions__c();
        profilePS1.Name = 'Sales Admin';
        profilePS1.Name__c = 'Price Approval-Sales Admin';
        profilePS1.API_Name__c = 'Price_Approval_Sales_Admin';
        profilePSList.add(profilePS1);
        PAProfilePermissions__c profilePS2 = new PAProfilePermissions__c();
        profilePS2.Name = 'Approver';
        profilePS2.Name__c = 'Price Approval-Approver';
        profilePS2.API_Name__c = 'Price_Approval_Approver';
        profilePSList.add(profilePS2);
        PAProfilePermissions__c profilePS3 = new PAProfilePermissions__c();
        profilePS3.Name = 'BU Admin';
        profilePS3.Name__c = 'Price Approval-BU Admin';
        profilePS3.API_Name__c = '';
        profilePSList.add(profilePS3);
        PAProfilePermissions__c profilePS4 = new PAProfilePermissions__c();
        profilePS4.Name = 'Price Requester';
        profilePS4.Name__c = 'Price Approval-Price Requester';
        profilePS4.API_Name__c = '';
        profilePSList.add(profilePS4);
        PAProfilePermissions__c profilePS5 = new PAProfilePermissions__c();
        profilePS5.Name = 'IT Admin';
        profilePS5.Name__c = 'Price Approval-IT Admin';
        profilePS5.API_Name__c = '';
        profilePSList.add(profilePS5);
        insert profilePSList;
        
        List<Product_Hierarchy__c> PHList = new List<Product_Hierarchy__c>();
        Product_Hierarchy__c PH1 = new Product_Hierarchy__c();
        PH1.PH_Code__c = 'A6';
        PH1.PH_Level__c = 1;
        PHList.add(PH1);
        Product_Hierarchy__c PH2 = new Product_Hierarchy__c();
        PH2.PH_Code__c = 'A6S1';
        PH2.PH_Level__c = 2;
        PHList.add(PH2);
        
        Product_Hierarchy__c PH3 = new Product_Hierarchy__c();
        PH3.PH_Code__c = 'A6S4';
        PH3.PH_Level__c = 2;
        PHList.add(PH3);
        Product_Hierarchy__c PH4 = new Product_Hierarchy__c();
        PH4.PH_Code__c = 'A6S112';
        PH4.PH_Level__c = 3;
        PHList.add(PH4);
        
        Product_Hierarchy__c PH5 = new Product_Hierarchy__c();
        PH5.PH_Code__c = 'B6';
        PH5.PH_Level__c = 1;
        PHList.add(PH5);
        
        Product_Hierarchy__c PH6 = new Product_Hierarchy__c();
        PH6.PH_Code__c = 'A6S112AA';
        PH6.PH_Level__c = 4;
        PHList.add(PH6);
        insert PHList;

        OrgGroup__c orgGrp = new OrgGroup__c();
        orgGrp.Business__c = 'Surfaces';
        insert orgGrp;

        //paph.selectedBUFromPage = orgGrp.Id;
        List<BU_PH__c> buphList = new List<BU_PH__c>();
        BU_PH__c buph1 = new BU_PH__c();
        buph1.Product_Hierarchy__c = PHList[0].Id;
        buph1.OrgGroup__c = orgGrp.Id;
        buph1.Business_Description__c = 'Test1';
        buphList.add(buph1);
        BU_PH__c buph2 = new BU_PH__c();
        buph2.Product_Hierarchy__c = PHList[1].Id;
        buph2.OrgGroup__c = orgGrp.Id;
        //buph2.Business_Description__c = 'Test2';
        buphList.add(buph2);
        BU_PH__c buph3 = new BU_PH__c();
        buph3.Product_Hierarchy__c = PHList[2].Id;
        buph3.OrgGroup__c = orgGrp.Id;
        buph3.Business_Description__c = 'Test3';
        buphList.add(buph3);
        BU_PH__c buph4 = new BU_PH__c();
        buph4.Product_Hierarchy__c = PHList[3].Id;
        buph4.OrgGroup__c = orgGrp.Id;
        //buph4.Business_Description__c = 'Test4';
        buphList.add(buph4);
        BU_PH__c buph5 = new BU_PH__c();
        buph5.Product_Hierarchy__c = PHList[4].Id;
        buph5.OrgGroup__c = orgGrp.Id;
        buph5.Business_Description__c = 'Test5';
        buphList.add(buph5);
        BU_PH__c buph6 = new BU_PH__c();
        buph6.Product_Hierarchy__c = PHList[5].Id;
        buph6.OrgGroup__c = orgGrp.Id;
        buph6.Business_Description__c = 'Test6';
        buphList.add(buph6);
        insert buphList;
        
        
        // For populating getListOptions() of orgGrpItem
            RecordType rType = [select id from RecordType Where sObjectType='OrgGroup__c' AND Name='Business'];
        
            OrgGroup__c salesArea = new OrgGroup__c(ERP_Sales_Org_code__c='A640',ERP_Distribution_Channel_Code__c='10',
                                            ERP_Division_code__c='02');
            insert salesArea;
                        
            OrgGroup__c Business = new OrgGroup__c(Business__c='BI EMEA Surfaces',RecordTypeId=rType.id);
            insert Business;
            
            ERP_Pricing_Procedure__c pp = new ERP_Pricing_Procedure__c(Pricing_Procedure_Code__c='ZA640A',
            Pricing_Procedure_Description__c='BI EMEA Surfaces',Pricing_Procedure__c='BI EMEA Surfaces',
            SAP_Application_Id__c='V',SAP_Client_Id__c='510',SAP_Cluster__c='CB1');
            insert pp;
            
            List<Organizational_Group_Item__c> orgItemList = new List<Organizational_Group_Item__c>();
            orgItemList.add(new Organizational_Group_Item__c(
            Business__c=Business.id,OrgGroup__c=salesArea.id,ERP_Pricing_Procedure__c=pp.id,
                    Customer_Request_Reasons__c='A;B',Non_Customer_Permanent_Request_Reasons__c='Non-A;Non-B',
                    ERP_Currency__c=null));
            orgItemList.add(new Organizational_Group_Item__c(
            Business__c=Business.id,OrgGroup__c=salesArea.id,ERP_Pricing_Procedure__c=pp.id,
                    Customer_Request_Reasons__c='A;B',Non_Customer_Permanent_Request_Reasons__c='Non-A;Non-B',
                    ERP_Currency__c='USD',ERP_UoM__c ='KG',
                    Pricing_Task_Reasons__c ='Pricing Task',
                    Rebate_Agreement__c ='Rebate',Pricing_Task_Type__c='Spot',Retroactive_Limit__c=31,Max_Valid_From_Offset_Cust_Spec__c=91,
                    Latest_Valid_From_Offset_Non_Cust_Spec__c=10,Latest_Valid_To_Offset_Cust_Spec__c=25,
                    Latest_Valid_To_Offset_Non_Cust_Spec__c=25/*,Approval_Escalation_Price_Requests=6*/));
            orgItemList.add(new Organizational_Group_Item__c(
            Business__c=Business.id,OrgGroup__c=salesArea.id,ERP_Pricing_Procedure__c=pp.id,
                    Customer_Request_Reasons__c='A;B',Non_Customer_Permanent_Request_Reasons__c='Non-A;Non-B',
                    ERP_Currency__c='USD',ERP_UoM__c ='KG',
                    Pricing_Task_Reasons__c ='Pricing Task',
                    Rebate_Agreement__c ='Rebate',Pricing_Task_Type__c='Spot',Retroactive_Limit__c=30,Max_Valid_From_Offset_Cust_Spec__c=90,
                    Latest_Valid_From_Offset_Non_Cust_Spec__c=5,Latest_Valid_To_Offset_Cust_Spec__c=24,
                    Latest_Valid_To_Offset_Non_Cust_Spec__c=24/*,Approval_Escalation_Price_Requests=5*/));                                
            
            insert orgItemList;
            Organizational_Group_User__c orgUser = new Organizational_Group_User__c();
            orgUser.Related_User__c = userInfo.getUserId();
            orgUser.OrgGroup__c=salesArea.id;
            orgUser.Organizational_Group_Item__c =orgItemList[0].id ;
            insert orgUser;
        //End
        
        PAOrganizationalGroupItems paOGItems = new PAOrganizationalGroupItems();
        paOGItems.selectedBU = Business.id; 
        paOGItems.selectedRecordId= orgGrp.Id;
        
        
        try{
        PAProductHierarchy Paprh= new PAProductHierarchy();
        Paprh.selectedPHValue = 'A6S1';
        Paprh.getListWrappers();
        System.debug('test dee inside try1');
        paprh.Validate('error');
        PAOrganizationalGroupItems paOGItems1 = new PAOrganizationalGroupItems();
        paOGItems1.selectedBU = null; 
        paOGItems1.selectedRecordId= null; 
        System.debug('test dee inside try');
        }
        Catch (Exception e){}
        System.debug('test dee inside catch');
        PAProductHierarchy Paph= new PAProductHierarchy();
        PAServiceState paSS = new PAServiceState();
        paSS.ogitems = new PAOrganizationalGroupItems();
        paSS.ogitems.selectedBU = paOGItems.selectedBU;
        PAProductHierarchy PH= new PAProductHierarchy(paSS);
        
        PH.paOGItem=paOGItems;
        PH.getListOptions();
        PH.getListBusinessComponents();
        PH.deleteRecord();
        PH.selectedPHValue = 'A6S1';
        PH.getListWrappers();
        
        PH.getName();
            PH.action('PAGlobalConfig', 'PAGlobalConfig', 'BUSetup');
            PH.action('PAGlobalConfig', 'PAGlobalConfig', 'BUSetupFetchPH');
            PH.action('PAGlobalConfig', 'PAGlobalConfig', 'BUSetupPHSave');
            PH.action('PAGlobalConfig', 'PAGlobalConfig', 'Cancel');
             PH.action('PAGlobalConfig', 'PAGlobalConfig', 'BUSetup_PHSave');
            PH.selectedPHValue = 'D6##14########';
            PH.relatedWrappersList=PH.getListWrappers();
            try{
            PH.action('PAGlobalConfig', 'PAGlobalConfig', 'BUSetupNamePHSave');
            }
            catch(exception e){
            }
            try{
            PH.action('PAGlobalConfig', 'PAGlobalConfig', 'BUSetupAddNewPH');
            }
            catch(exception e){
            }
        PH.selectedPHValue = '';
        PH.getListWrappers();
        PH.valuePH = 'BUSetupAddNewPH';
        PH.save();
        PH.action('PAGlobalConfig', 'PAGlobalConfig', 'BUSetup_PHSave');
        
        PH.selectedPHValue = '';
        PH.NewPH = 'B6';
        PH.save();
        
        try{
        PH.checkIfBuPhExists = true;
        PH.save();
        }catch(Exception ex){}
    }
    
    
}