objects/ERP_Sales_Prices_SAP__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Holder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Holder</label>
        <referenceTo>ERP_Sales_Prices_SAP__c</referenceTo>
        <relationshipLabel>ERP Sales Prices - SAP</relationshipLabel>
        <relationshipName>ERP_Sales_Prices_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Org. Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPriceHolder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPriceHolder</label>
        <type>Checkbox</type>
    </fields>
    <label>ERP Sales Prices - SAP</label>
    <nameField>
        <displayFormat>SPSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP Sales Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Sales Prices - SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ProfileRecordIds__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>RecordId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>ProfileRecordIds</label>
</CustomObject>

classes/BatchToMapHolder_New_UT.cls
@isTest 
private class BatchToMapHolder_New_UT{
    static testMethod void batchClassForHolderTestMethod() {
        
        ProfileRecordIds__c pr = new ProfileRecordIds__c (Name='System Administrator', RecordId__c='00e30000001mVQC');
                  insert pr;
        ERP_Sales_Prices_SAP__c v =new ERP_Sales_Prices_SAP__c();
        
        v.isPriceHolder__c=false;
        //v.Key_Combination__c='Sales Org./Sold to/Project Id/PH1/PH2/PH3/PH4/PH5/PH6/Material Price Group';
        v.Key_Combination__c='Sales Org./Material';
        v.Sales_Org_Code__c='D660';
        v.BU__c = 'BI AP Surfaces';
        v.Price_Holder__c =System.label.PriceHolder_Id_for_batch;
        
        ERP_Sales_Prices_SAP__c v1 =new ERP_Sales_Prices_SAP__c();
        
        v1.isPriceHolder__c=false;
        v1.Sales_Org_Code__c='D660';
        //v1.Key_Combination__c='Sales Org./Sold to/Project Id/PH1/PH2/PH3/PH4/PH5/PH6/Material Price Group';
        v1.Key_Combination__c='Sales Org./Material';
        v1.BU__c = 'BI AP Surfaces';
        v1.Price_Holder__c =System.label.PriceHolder_Id_for_batch;
        
     list<sObject> c=new list<ERP_Sales_Prices_SAP__c>();
     c.add(v);
     c.add(v1);

     upsert c;
    

     test.startTest();
     BatchToMapHolder_New bc=new BatchToMapHolder_New();
     Database.executeBatch(bc, 200); 
     test.stopTest(); 
    
    }

}