objects/ERP_Export_to_SAP__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel_Code__c</fullName>
        <label>Dist. Channel Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <label>Division Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Org. Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ERP-Export to SAP</label>
    <nameField>
        <displayFormat>EEXP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP-Export to SAP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP-Export to SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Organizational_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items (Business1)</relationshipLabel>
        <relationshipName>Organizational_Group_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>OrgGroup</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>Organizational_Group_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Organizational Group Item</label>
    <nameField>
        <displayFormat>OGI-{00000}</displayFormat>
        <label>Organizational Group Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Organizational_Group_User__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <formula>Organizational_Group_Item__r.Business__r.Business__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group Item</label>
        <referenceTo>Organizational_Group_Item__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <formula>OrgGroup__r.ERP_Sales_Org_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org Code</label>
        <type>Text</type>
    </fields>
    <label>Organizational Group Users</label>
    <nameField>
        <displayFormat>OGU-{00000}</displayFormat>
        <label>Organizational Group User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ERP_Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>The DuPont Business (Business Unit) or legal entity</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SFDC_SAP_Price_Sync__c.object
<CustomObject>
    <description>Price comparison results between SAP and SFDC are stored in this object</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>SFDC_SAP_Sync</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SAP_BU__c</fullName>
        <description>Store Business name for SFDC SAP sync If In SAP Not SFDC</description>
        <label>SAP BU</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Dist_Channel_Code__c</fullName>
        <description>Stores Dist Channel Code from SAP If in SAP not in SFDC</description>
        <label>SAP Dist Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Division_Code__c</fullName>
        <description>Store SAP Div Code from SAP for If in SAP not SFDC</description>
        <label>SAP Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Sales_Org_Code__c</fullName>
        <description>Store Sales Org Code for In SAP Not SFDC</description>
        <label>SAP Sales Org Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_PA_BU__c</fullName>
        <label>SFDC PA BU</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFDC_PA_Price_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SFDC PA Price Record</label>
        <referenceTo>ERP_Export_to_SAP__c</referenceTo>
        <relationshipLabel>SFDC SAP Price Sync</relationshipLabel>
        <relationshipName>SFDC_SAP_Price_Sync</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SFDC SAP Price Sync</label>
    <nameField>
        <label>SFDC SAP Price Sync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SFDC SAP Price Sync</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SFDCSAPPriceSyncShareHandler.cls
/*
 * Name     :   SFDCSAPPriceSyncShareHandler
 * Description  :  This class will handle all logic for SFDCSAPPriceSyncShare trigger
 * Author     :   Infosys Limited <GT20150519>
 * Created Date :   19 May 2015
 *
 * Version   Modified Date     Modified By           Modification
     1            Dec.1.2015    Sumit Gupta            Added logic that work for In SAP Not SFDC.
 * ---------------------------------------------------------------------------------------------------- 
 *

*/
public class SFDCSAPPriceSyncShareHandler extends TriggerHandlerBase {
  
    List<SFDC_SAP_Price_Sync__c> syncRecList=(List<SFDC_SAP_Price_Sync__c>)Trigger.New;
    Map<Id,SFDC_SAP_Price_Sync__c> mapIdOldSyncRec;
    List<SFDC_SAP_Price_Sync__share> syncShareList ;
  
  
  //Handle the set of operations on after event of trigger
    public override void  bulkAfter(){
        syncShareList = new List<SFDC_SAP_Price_Sync__share>();
        //List<SFDC_SAP_Price_Sync__c> syncRecList = (List<SFDC_SAP_Price_Sync__c>)Trigger.New;
        mapIdOldSyncRec =  (Map<Id,SFDC_SAP_Price_Sync__c>)Trigger.oldMap;
      
        // Handle updates and share the records to respective assignee if any change in assignee
        if(trigger.isUpdate)
        {
          for(SFDC_SAP_Price_Sync__c syncRec:syncRecList )
          {
            if(syncRec.Assigned_To__c!=null && mapIdOldSyncRec.get(syncRec.id).Assigned_To__c!=syncRec.Assigned_To__c)
            {
                    prepShareRec(syncRec,new List<Id>{syncRec.Assigned_To__c},'Edit', 'Assignee');
            }
          }
          
          insertSyncShare();
        }
        
        //Handle insert cases and share defects with all viewers belongs to the repective business, sales area
        if(trigger.isInsert)
        {
            //Map<String,string> idSalesAreaMap = new Map<String,string>();
            Set<ID> priceIds = new Set<ID>();
            list<String> SalesOrgCode = new List<String>();
            list<String> DistCode = new List<String>();
            list<String> DivCode = new List<String>();
            list<String> bus = new List<String>();
            Boolean withRecordId = false;
            Boolean withoutRecordId = false;
            for(SFDC_SAP_Price_Sync__c syncRec: syncRecList){
                if(syncRec.SFDC_PA_Price_Record__c!=null){
                    priceIds.add(syncRec.SFDC_PA_Price_Record__c);
                    bus.add(syncRec.SFDC_PA_BU__c);
                    withRecordId = true;
                }
                else{
                    if(syncRec.SAP_BU__c != null && syncRec.SAP_Dist_Channel_Code__c != null && syncRec.SAP_Division_Code__c != null && syncRec.SAP_Sales_Org_Code__c != null){
                        SalesOrgCode.add(syncRec.SAP_Sales_Org_Code__c);
                        DistCode.add(syncRec.SAP_Dist_Channel_Code__c);
                        DivCode.add(syncRec.SAP_Division_Code__c);
                        if(syncRec.SAP_BU__c.contains(',')){
                          String[] buString = syncRec.SAP_BU__c.split(',');
                            for(String s:buString){
                                bus.add(s);
                            }
                        }else{
                          bus.add(syncRec.SAP_BU__c);
                        }
                        withoutRecordId=true;
                    }
                }   
            }
            if(withRecordId){
                InSfdcNotSAPOrBoth(priceIds, bus);
                withRecordId = false;
            }
            if(withoutRecordId){
                InSapNotSfdc(SalesOrgCode,DistCode,DivCode,bus);
                withoutRecordId = false;
            }
        }        
    }
    public void InSfdcNotSAPOrBoth(Set<ID> priceIds,list<String> bus){        
        Map<String,string> idSalesAreaMap = new Map<String,string>();
        list<String> SalesOrgCode = new List<String>();
        list<String> DistCode = new List<String>();
        list<String> DivCode = new List<String>();
        Boolean fourShareFieldExist = false;
        for(ERP_Export_to_SAP__c price:[select id,BU__c,Sales_Org_Code__c,Distribution_Channel_Code__c,Division_Code__c from ERP_Export_to_SAP__c where id in :priceIds]){
            if(price.bu__c != null && price.Sales_Org_Code__c != null && price.Distribution_Channel_Code__c!= null && price.Division_Code__c != null){  
                idSalesAreaMap.put(price.id, price.bu__c+price.Sales_Org_Code__c+price.Distribution_Channel_Code__c+price.Division_Code__c);
                SalesOrgCode.add(price.Sales_Org_Code__c);
                DistCode.add(price.Distribution_Channel_Code__c);
                DivCode.add(price.Division_Code__c);
                fourShareFieldExist=true;
            }   
        }
        system.debug('>>>>>>SOC>>>>>>>'+SalesOrgCode+'<>DIST<>'+DistCode+'<>DIV<>'+DivCode+'<>BUS<>'+bus);
        if(fourShareFieldExist){
            GetOrgUsers(SalesOrgCode,DistCode,DivCode,bus,idSalesAreaMap);
            fourShareFieldExist=false;
        }   
    }  
    
    /**********Added logic for sharing Prices If in SAP but not in SFDC**************/
    public void InSapNotSfdc(list<String> SalesOrgCode,list<String> DistCode,list<String> DivCode,list<String> bus){
        Map<String,string> idSalesAreaMap = new Map<String,string>();
        /*
        for(ERP_Export_to_SAP__c price:[select id,BU__c,Sales_Org_Code__c,Distribution_Channel_Code__c,Division_Code__c from ERP_Export_to_SAP__c 
            where BU__c IN: bus AND Sales_Org_Code__c IN: SalesOrgCode AND Distribution_Channel_Code__c IN: DistCode AND Division_Code__c IN: DivCode])
        {
            idSalesAreaMap.put(price.id, price.bu__c+price.Sales_Org_Code__c+price.Distribution_Channel_Code__c+price.Division_Code__c);
            
        }
        */
        system.debug('>>>>>>SOC>>>>>>>'+SalesOrgCode+'<>DIST<>'+DistCode+'<>DIV<>'+DivCode+'<>BUS<>'+bus);
        
        GetOrgUsers(SalesOrgCode,DistCode,DivCode,bus,null); //,idSalesAreaMap
    }
    
    public void GetOrgUsers(list<String> SalesOrgCode,list<String> DistCode,list<String> DivCode,list<String> bus,Map<String,string> idSalesAreaMap){   
        Map<String,List<Id>> saViewUsrMap = new Map<String,List<Id>>();
        string key;
        for(Organizational_Group_User__c orgUsr : [select Related_User__c,OrgGroup__r.ERP_Sales_Org_Code__c,OrgGroup__r.ERP_Distribution_Channel_Code__c,
                        OrgGroup__r.ERP_Division_Code__c,Organizational_Group_Item__r.Business__r.Business__c from Organizational_Group_User__c where 
                            OrgGroup__r.ERP_Sales_Org_Code__c in :SalesOrgCode and OrgGroup__r.ERP_Distribution_Channel_Code__c in :DistCode 
                            and OrgGroup__r.ERP_Division_Code__c in :DivCode and Related_User__r.Profile.name='Price Approval-Viewer'
                            and Organizational_Group_Item__r.Business__r.Business__c in :bus ]){
            key = orgUsr.Organizational_Group_Item__r.Business__r.Business__c+orgUsr.OrgGroup__r.ERP_Sales_Org_Code__c+orgUsr.OrgGroup__r.ERP_Distribution_Channel_Code__c+orgUsr.OrgGroup__r.ERP_Division_Code__c;
            List<Id> userIds = new List<Id>();
            if(saViewUsrMap.containsKey(key)){
                userIds = saViewUsrMap.get(key);
                userIds.add(orgUsr.Related_User__c);
                saViewUsrMap.put(key,userIds);
            }
            else{
                userIds.add(orgUsr.Related_User__c);
                saViewUsrMap.put(key,userIds);
            }
        }
      
      for(SFDC_SAP_Price_Sync__c syncRec:syncRecList)
      {
        /*
        if(idSalesAreaMap != null){
            List<Id> userIds = saViewUsrMap.get(idSalesAreaMap.get(syncRec.SFDC_PA_Price_Record__c));
        }else{
        }*/ 
        List<id> userIds = saViewUsrMap.get(key);
        
        prepShareRec(syncRec,userIds,'Read', 'Viewers');
      }
      
      insertSyncShare();
    }
  
  
  //Prepare the the sharing records with respective access level
    public void prepShareRec(SFDC_SAP_Price_Sync__c Rec,List<Id> usrIds, string accessLevel, String shareRecordto){
        try{
            for(Id usrId:usrIds){
          
                SFDC_SAP_Price_Sync__share syncShare = new SFDC_SAP_Price_Sync__share();
                syncShare.ParentId = Rec.id;
                syncShare.AccessLevel = accessLevel;          
                syncShare.UserOrGroupId = usrId;
                if(shareRecordto =='Viewers')
                    syncShare.RowCause = Schema.SFDC_SAP_Price_Sync__share.RowCause.Share_with_all_viewers__c;
                if(shareRecordto =='Assignee')
                    syncShare.RowCause = Schema.SFDC_SAP_Price_Sync__share.RowCause.Share_with_assignee__c;
                    syncShareList.add(syncShare);
            }
        }
        catch(Exception e){
          Rec.addError('Unable to share the records at SFDC end');
        }
    }
  
  //Insert the sharing records
    public void insertSyncShare(){
        if(syncShareList.size()>0){
            try{
              database.insert (syncShareList,false);
            }
            catch(Exception e){
              System.debug('Exception from Class SFDCSAPPriceSyncShareHandler, Message:'+e.getMessage());
            }
        }
    }
}