objects/ERP_Sales_Prices_SAP__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <label>Campaign Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <label>Contract No.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Hierarchy_Code__c</fullName>
        <label>Customer Hierarchy Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Hierarchy__c</fullName>
        <label>Customer Hierarchy</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Price_Group_Code__c</fullName>
        <label>Customer Price Group Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Price_Group__c</fullName>
        <label>Customer Price Group</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Use_Code__c</fullName>
        <label>End Use Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Use__c</fullName>
        <label>End Use</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms1__c</fullName>
        <label>Incoterms</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms_1_Code__c</fullName>
        <label>Incoterms Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Kcode__c</fullName>
        <label>Kcode</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment_Code__c</fullName>
        <label>Market Segment Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Group_5_Key_Code__c</fullName>
        <label>Material Group 5 Key Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Group_5_Key__c</fullName>
        <label>Material Group 5 Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Price_Group_Code__c</fullName>
        <label>Material Price Group Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Price_Group__c</fullName>
        <label>Material Price Group</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_List_Type_Code__c</fullName>
        <label>Price List Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Ref_Partner_Code__c</fullName>
        <label>Price Ref. Partner Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Ref_Partner__c</fullName>
        <label>Price Ref. Partner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District_Code__c</fullName>
        <label>Sales District Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Sales District</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <label>Sales Office Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Type_Code__c</fullName>
        <label>Sales Order Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Type__c</fullName>
        <label>Sales Order Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Org. Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment_Code__c</fullName>
        <label>Terms of Payment Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment__c</fullName>
        <label>Terms of Payment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variant_Code__c</fullName>
        <label>Variant Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <label>Variant</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPriceHolder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPriceHolder</label>
        <type>Checkbox</type>
    </fields>
    <label>ERP Sales Prices - SAP</label>
    <nameField>
        <displayFormat>SPSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP Sales Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Sales Prices - SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_Of_Payment_Code__c</fullName>
        <label>Terms_Of_Payment_Code</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_Of_Payment__c</fullName>
        <label>Terms Of Payment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricing_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <formula>Pricing_Request__r.BU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Code__c</fullName>
        <label>Campaign Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <label>Contract Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract__c</fullName>
        <label>Contract</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Hierarchy_Code__c</fullName>
        <label>Customer Hierarchy Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Hierarchy__c</fullName>
        <label>Customer Hierarchy</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Price_Group_Code__c</fullName>
        <label>Customer Price Group Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Price_Group__c</fullName>
        <label>Customer Price Group</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Prices_SAP__c</fullName>
        <label>ERP Sales Prices - SAP</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Use_Code__c</fullName>
        <label>End Use Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Use__c</fullName>
        <label>End Use</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Kcode__c</fullName>
        <label>Kcode</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment_Code__c</fullName>
        <label>Market Segment Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Segment__c</fullName>
        <label>Market Segment</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Group_5_Key_Code__c</fullName>
        <label>Material Group 5 Key Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Group_5_Key__c</fullName>
        <label>Material Group 5 Key</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Price_Group_Code__c</fullName>
        <label>Material Price Group Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Price_Group__c</fullName>
        <label>Material Price Group</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_List_Type_Code__c</fullName>
        <label>Price List Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Ref_Partner_Code__c</fullName>
        <label>Price Ref. Partner Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Ref_Partner__c</fullName>
        <label>Price Ref. Partner</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>32</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District_Code__c</fullName>
        <label>Sales District Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_District__c</fullName>
        <label>Sales District</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <label>Sales Office Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Type_Code__c</fullName>
        <label>Sales Order Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Order_Type__c</fullName>
        <label>Sales Order Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Code__c</fullName>
        <label>State Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_Of_Payment_Code__c</fullName>
        <label>Terms of Payment Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_Of_Payment__c</fullName>
        <label>Terms Of Payment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variant_Code__c</fullName>
        <label>Variant Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Variant__c</fullName>
        <label>Variant</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Pricing Request Item</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Request Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Request Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/batchClassForUpdatePRItem_UT.cls
@isTest 
private class batchClassForUpdatePRItem_UT {

/****PKH

  static testMethod void batchClassForUpdateerpSAPTestMethod() {
    
    PAUtil.insertProfileRecordId();

     ERP_Sales_Prices_SAP__c v =new ERP_Sales_Prices_SAP__c();
     
     v.isPriceHolder__c=false;
     //v.Key_Combination__c='Sales Org./Sold to/Project Id/PH1/PH2/PH3/PH4/PH5/PH6/Material Price Group';
     v.Key_Combination__c='Sales Org./Material';
    v.Sales_Org_Code__c='D660';
    v.BU__c = 'BI AP Surfaces';
    v.Customer_Hierarchy_Code__c = '123456';
    v.Customer_Hierarchy__c = 'cust hierarchy';
    v.Variant_Code__c = '1234';
    v.Variant__c='test value';
    v.Contract_Code__c = '1234';
    v.Contract__c='test value';
    v.Sales_Order_Type_Code__c = '1234';
    v.Sales_Order_Type__c='test value';
    v.Material_Group_5_Key_Code__c = '1234';
    v.Material_Group_5_Key__c='test value';
    v.Material_Price_Group_Code__c = '1234';
    v.Material_Price_Group__c='test value';
    v.Customer_Price_Group_Code__c = '1234';
    v.Customer_Price_Group__c='test value';
    v.Terms_Of_Payment_Code__c = '1234';
    v.Terms_Of_Payment__c = 'terms';
    v.Incoterms_1_Code__c = '1234';
    v.Incoterms1__c='test value';
    v.Price_List_Type_Code__c = '1234';
    v.Price_List_Type__c='test value';
    v.Sales_Office_Code__c = '1234';
    v.Sales_Office__c='test value';
    v.Sales_District_Code__c = '1234';
    v.Sales_District__c='test value';
    v.Market_Segment_Code__c ='1234';
    v.Market_Segment__c='test value';
    v.End_Use_Code__c = '1234';
    v.End_Use__c='test value';
    v.Price_Ref_Partner_Code__c = '1234';
    v.Price_Ref_Partner__c = '1233';
    v.Project__c = '1241';
    v.KCode__c = '1234';
    v.Campaign_Code__c = '1234';
    v.Campaign__c='test value';
    v.State_Code__c = '1234';
    v.State__c='test value';
    v.Profit_Center__c = 'test';
    v.Profit_Center_Code__c = '1234';
    v.End_User_Code__c = '1234';
    v.End_User__c = '2352345';
    v.Customer_Hierarchy_Code__c = '1234';
    v.Customer_Hierarchy__c = 'test';
    v.ShipTo__c ='23525';
    v.ShipTo_Code__c='test value';
    v.Material_Group_1_Code__c = '1234';
    v.Material_Group_1__c='test value';
    
     ERP_Sales_Prices_SAP__c v1 =new ERP_Sales_Prices_SAP__c();
     
     v1.isPriceHolder__c=false;
     v1.Sales_Org_Code__c='D660';
     //v1.Key_Combination__c='Sales Org./Sold to/PH1/PH2/PH3/PH4/PH5/PH6';
     v1.Key_Combination__c='Sales Org./Material';
    v1.BU__c = 'BI AP Surfaces';
    v1.markfordeletion__c = false;
    
    
    
   list<ERP_Sales_Prices_SAP__c> c=new list<ERP_Sales_Prices_SAP__c>();
   c.add(v);
   c.add(v1);

     insert c;
  

   test.startTest();
    batchClassForUpdateerpSalesPrice bc=new batchClassForUpdateerpSalesPrice();
   Database.executeBatch(bc); 
     test.stopTest(); 
  
  }
    
  
 PKH***/ 

 // <SS20220826> removed commented below method to run 

  static testMethod void batchClassForUpdatePRItemTestMethod() {
    
    PAUtil.insertProfileRecordId();

     Pricing_Request__c pricingRequest = new Pricing_Request__c();
        pricingRequest.Bu__c = 'BI_EMEA_Surfaces';
        pricingRequest.Request_Approval_Status__c = 'Submitted';  
        
        insert pricingRequest;           
     Pricing_Request_Item__c v =new Pricing_Request_Item__c();
    v.Pricing_Request__c = pricingRequest.id; 
    v.Key_Combination__c='Sales Org./Material';
    v.Sales_Org_Code__c='D660';
    v.Approval_status__c = 'Submitted';
    v.Customer_Hierarchy_Code__c = '123456';
    v.Customer_Hierarchy__c = 'cust hierarchy';
    v.Variant_Code__c = '1234';
    v.Variant__c='test value';
    v.Contract_Code__c = '1234';
    v.Contract__c='test value';
    v.Sales_Order_Type_Code__c = '1234';
    v.Sales_Order_Type__c='test value';
    v.Sales_Order_Item__c = '1222';      
    v.Sales_Order_Item_Code__c ='test value';
   // <SS20230501> - START
    v.Value_Center__c = 'test value';
    v.Value_Center_Code__c ='1222';
    v.Ext_Matl_Grp__c ='test value';
    v.Ext_Matl_Grp_Code__c ='1222';
    v.Material_group_2__c='test value';
    v.Material_group_2_Code__c ='1222';
    v.Price_Zone__c ='test value';
    v.Price_Zone_Code__c ='1222';
    v.Shipping_Condition__c ='test value';
    v.Shipping_Condition_Code__c ='1234';
    // <SS20230501> - End
    v.Material_Group_5_Key_Code__c = '1234';
    v.Material_Group_5_Key__c='test value';
    v.Material_Price_Group_Code__c = '1234';
    v.Material_Price_Group__c='test value';
    v.Customer_Price_Group_Code__c = '1234';
    v.Customer_Price_Group__c='test value';
    v.Terms_Of_Payment_Code__c = '1234';
    v.Terms_Of_Payment__c = 'terms';
    v.Incoterms_Code__c = '1234';
    v.Inco_terms__c='test value';
    v.Price_List_Type_Code__c = '1234';
    v.Price_List_Type__c='test value';
    v.Sales_Office_Code__c = '1234';
    v.Sales_Office__c='test value';
    v.Sales_District_Code__c = '1234';
    v.Sales_District__c='test value';
    v.Market_Segment_Code__c ='1234';
    v.Market_Segment__c='test value';
    v.End_Use_Code__c = '1234';
    v.End_Use__c='test value';
    v.Price_Ref_Partner_Code__c = '1234';
    v.Price_Ref_Partner__c = '1233';
    v.Project__c = '1241';
    v.KCode__c = '1234';
    v.Campaign_Code__c = '1234';
    v.Campaign__c='test value';
    v.State_Code__c = '1234';
    v.State__c='test value';
    v.Profit_Center__c = 'test';
    v.Profit_Center_Code__c = '1234';
    v.End_User_Code__c = '1234';
    v.End_User__c = '2352345';
    v.Customer_Hierarchy_Code__c = '1234';
    v.Customer_Hierarchy__c = 'test';
    v.ShipTo__c ='23525';
    v.ShipTo_Code__c='test value';
    v.Material_Group_1_Code__c = '1234';
    v.Material_Group_1__c='test value';
    
     Pricing_Request_Item__c v1 =new Pricing_Request_Item__c();
     
     
     v1.Sales_Org_Code__c='D660';
     //v1.Key_Combination__c='Sales Org./Sold to/PH1/PH2/PH3/PH4/PH5/PH6';
     v1.Key_Combination__c='Sales Org./Material';
    v1.Pricing_Request__c = pricingRequest.id; 
    v1.Approval_status__c = 'Submitted';
    
    
    
   list<Pricing_Request_Item__c> c=new list<Pricing_Request_Item__c>();
   c.add(v);
   c.add(v1);

     insert c;
  

   test.startTest();
    batchClassForUpdatePRItem bc=new batchClassForUpdatePRItem();
   Database.executeBatch(bc); 
     test.stopTest(); 
  
  }
    
  
}