objects/ERP_Relationship__c.object
<CustomObject>
    <description>Used to manage the types of partner relationships an ERP customer might have (Sold-To, Ship-To, End User, Sales Rep, CSR etc.), as stored in SAP</description>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code + Partner Counter + Partner Function Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ERP Relationship</label>
    <nameField>
        <displayFormat>ERP-R{000000000}</displayFormat>
        <label>ERP Relationship  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BatchUpdate_ERPRelationship.cls
/*********************************************************************************************
Copyright © 2020 DuPont. All rights reserved. 
Author: Rajan Kumar Mishra
Email: rajankumar.mishra@tcs.com
Last Modified Date : 12th Feb 2020
Description: This Batch class will update the value of field External_ERP_ID__c for object ERP_Relationship__c.
***********************************************************************************************
<CRM-2021-04-0192>
Last Modified By    :   Harsh
Last Modified Date  :   02/07/2021
Description         :   Added OR and replace condition for the P80 requirements
************************************************************************************************/
global class BatchUpdate_ERPRelationship implements Database.Batchable<sObject>
{

    public List<ERP_Relationship__c> RelationshipList= new List<ERP_Relationship__c>();    
    global Database.QueryLocator start(Database.BatchableContext BC)
    {     
        string startQuery = 'SELECT id, External_ERP_ID__c,Name FROM ERP_Relationship__c where External_ERP_ID__c!=null';     
        return Database.getQueryLocator(startQuery);
    }
   
    global void execute(Database.BatchableContext BC, List<sObject> returnedRelationshipy)
    {
        List<ERP_Relationship__c> update_RelationshipList = new List<ERP_Relationship__c>();  
        RelationshipList = returnedRelationshipy;    
        
        for(ERP_Relationship__c e: RelationshipList)
        {
            //Start_<CRM-2021-04-0192> -- Adding OR condition
            if(e.External_ERP_ID__c.contains('Q23') || e.External_ERP_ID__c.contains('Q80'))
            {
                e.External_ERP_ID__c = e.External_ERP_ID__c.replace('Q23','P23').replace('Q80','P80') ; //-- Adding replace for <CRM-2021-04-0192>
            }//End_<CRM-2021-04-0192>
         
            update_RelationshipList.add(e);
        }
        if(update_RelationshipList.size()>0)
        {
            update update_RelationshipList;
        }
    }
    global void finish(Database.BatchableContext BC){}
}