objects/ERP_Customer__c.object
<CustomObject>
    <description>Contains customer master from SAP. Updated by SAP-SFDC interface only.</description>
    <fields>
        <fullName>Account_Group__c</fullName>
        <description>The account group is a classifying feature within customer masterrecords. The account group determines in which number range the customer account number should be;whether the number is assigned by the user or by the system;which specifications are necessary or possible in the master record.</description>
        <label>Account Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The city of this customer as stored in SAP.</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country af this customer as stored in SAP</description>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <description>Key with which the customer can be identified within the SAP system.Gives an alphanumeric key, which clearly identifies the customer or vendor in the SAP system.</description>
        <label>Customer Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Price_Group_Code__c</fullName>
        <description>A grouping of pricing conditions that you can apply to customers who share similar pricing requirements.</description>
        <label>Customer Price Group Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Price_Group__c</fullName>
        <description>A grouping of pricing conditions that you can apply to customers who share similar pricing requirements.</description>
        <label>Customer Price Group</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms_1_Code__c</fullName>
        <description>Commonly-used trading terms that comply with the standards established by the International Chamber of Commerce (ICC). Incoterms specify certain internationally recognised procedures that the shipper and the receiving party must follow for the shipping transaction to be successfully completed.</description>
        <label>Incoterms 1 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms_1__c</fullName>
        <description>Commonly-used trading terms that comply with the standards established by the International Chamber of Commerce (ICC). Incoterms specify certain internationally recognised procedures that the shipper and the receiving party must follow for the shipping transaction to be successfully completed.</description>
        <label>Incoterms 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms_2__c</fullName>
        <description>Commonly-used trading terms that comply with the standards established by the International Chamber of Commerce (ICC). Incoterms specify certain internationally recognised procedures that the shipper and the receiving party must follow for the shipping transaction to be successfully completed.</description>
        <label>Incoterms 2</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Organizational Group ( as ERP Sales Area )</description>
        <label>Sales Area</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>ERP Customers</relationshipLabel>
        <relationshipName>ERP_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PO_Box__c</fullName>
        <description>The Post Office Box of this customer as stored in SAP.</description>
        <label>PO Box</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_List_Type_Code__c</fullName>
        <description>Identifies a price list or other pricing condition (for example, a surcharge or discount).</description>
        <label>Price List Type Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_List_Type__c</fullName>
        <description>Identifies a price list or other pricing condition (for example, a surcharge or discount).</description>
        <label>Price List Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <description>A physical location (for example, a branch office) that has responsibility for the sale of certain products or services within a given geographical area.</description>
        <label>Sales Office Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <description>A physical location (for example, a branch office) that has responsibility for the sale of certain products or services within a given geographical area.</description>
        <label>Sales Office</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <description>Geographical region this customer is located as stored in SAP</description>
        <label>State/Province Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>Geographical region this customer is located as stored in SAP</description>
        <label>State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>The street of this customer as stored in SAP.</description>
        <label>Street</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment_Code__c</fullName>
        <description>Key for defining payment terms composed of cash discount percentages and payment periods. It is used in sales orders, purchase orders, and invoices.</description>
        <label>Terms of Payment Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment__c</fullName>
        <description>Key for defining payment terms composed of cash discount percentages and payment periods. It is used in sales orders, purchase orders, and invoices.</description>
        <label>Terms of Payment</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZIP_Postal_Code__c</fullName>
        <description>The postal (zip) code for the house address(street and city).</description>
        <label>ZIP/Postal Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Organizational_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items (Business1)</relationshipLabel>
        <relationshipName>Organizational_Group_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>OrgGroup</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>Organizational_Group_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Organizational Group Item</label>
    <nameField>
        <displayFormat>OGI-{00000}</displayFormat>
        <label>Organizational Group Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Organizational_Group_User__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <formula>Organizational_Group_Item__r.Business__r.Business__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group Item</label>
        <referenceTo>Organizational_Group_Item__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <formula>OrgGroup__r.ERP_Sales_Org_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org Code</label>
        <type>Text</type>
    </fields>
    <label>Organizational Group Users</label>
    <nameField>
        <displayFormat>OGU-{00000}</displayFormat>
        <label>Organizational Group User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ERP_Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PAChangeSalesArea.cls
/**********************************************************************************************************************
 ***********************************************Modification Log********************************************************
<PP20131021>
Last Modified By    :   Priyanka Pillala
Last Modified Date  :   21 October 2013
Description         :   ROLLOUT 2 SIT Issue # 11 FIX - Adding State__c and ZIP_Postal_Code__c to the query
 ***********************************************************************************************************************/
public with sharing class PAChangeSalesArea implements IPAComponent
{

	//variables
	public list<ERP_Customer__c> perm_custRecord {get;set;}
	public String soldToCode {get;set;}
	public Id CSAId {get;set;}
	public  Boolean flagCSA {get;set;}
	public String selectedBusiness {get;set;}
	//For setting current page label

	//constructor
	public PAChangeSalesArea()
	{
		perm_custRecord = new list<ERP_Customer__c>();
		system.debug('&&& soldToCode '+soldToCode);
		flagCSA = false;
		system.debug('&&& flagCSA '+flagCSA);
	}

	//Methods
	/*
	 * Author	   : 
	 * Method Name  :   action
	 * Parameters   :   
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference action(){
		return null;
	} 

	/*
	 * Author	   : 
	 * Method Name  :   displayPopUpWindowMethod
	 * Parameters   :  
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference displayPopUpWindow() {
		return actionCSA();
	}

	/*
	 * Author	   : 
	 * Method Name  :   searchCustomer
	 * Parameters   :  
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference dosearch() {
		return null;
	}
	/*
	 * Author	   : 
	 * Method Name  :   returnData
	 * Parameters   :  
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference returnData(){
		return closeActionCSA();
	}

	/*
	 * Author	   : 
	 * Method Name  :   closeWindow
	 * Parameters   :  
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference closeWindow(){
		return closeActionCSA();
	}

	/*
	 * Author	  : Anand Darshi
	 * Method Name : pro_fetchProjectMethod
	 * Parameters  : No parameters
	 * Return type : void 
	 * Description : Fetch current projects and completed projects on clicking Fetch Projects or Fetch All Projects.
	 */

	private PageReference closeActionCSA()
	{
		flagCSA = false;
		return null;
		//ApexPages.currentPage().getParameters().put('SAreaLink','true'); --commented on jan17th--refactoring
	}

	/*
	 * Author	  : Anand Darshi
	 * Method Name : actionCSA
	 * Parameters  : No parameters
	 * Return type : void 
	 * Description : Shows the customer details of multiple SalesArea.
	 */

	private PageReference actionCSA()
	{

		system.debug('###change sales area');
		flagCSA = true;
		system.debug('&&& flagCSA '+flagCSA);
		perm_custRecord = new list<ERP_Customer__c>();
		system.debug('&&& soldToCode '+soldToCode);

		List<String> OGSAId = new List<String>();
		List<String> salesOrgList = new List<String>();
		List<String>  distChannelList = new List<String>();
		List<String> divisionList = new List<String>(); 
		List<Organizational_Group_User__c> OGU = [SELECT Organizational_Group_Item__c,OrgGroup__c FROM Organizational_Group_User__c WHERE Related_User__c=:UserInfo.getUserId() AND Organizational_Group_Item__r.Business__c=:selectedBusiness];

		system.debug('&&& OGU '+OGU);

		for(Organizational_Group_User__c X:OGU)
		{
			OGSAId.add(X.OrgGroup__c);
		}

		system.debug('&&& OGSAId '+OGSAId);

		List<OrgGroup__c> OGSalesArea = [SELECT ERP_Sales_Org_Code__c,ERP_Distribution_Channel_Code__c,ERP_Division_Code__c FROM OrgGroup__c WHERE Id IN:OGSAId];

		system.debug('&&& OGSalesArea '+OGSalesArea);

		for(OrgGroup__c X:OGSalesArea)
		{
			salesOrgList.add(X.ERP_Sales_Org_Code__c);
			distChannelList.add(X.ERP_Distribution_Channel_Code__c);
			divisionList.add(X.ERP_Division_Code__c);
		}
		system.debug('&&& salesOrgList '+salesOrgList);
		system.debug('&&& distChannelList '+distChannelList);
		system.debug('&&& divisionList '+divisionList);
		//<PP20131021>
		perm_custRecord=[SELECT  Customer_Code__c,Name,Country__c,Street__c,Sales_Office__c,City__c,Account_Group__c,Distribution_Channel__c,Distribution_Channel_Code__c,
						Division__c,Division_Code__c,PO_Box__c,Sales_Org__c,Sales_Org_Code__c,State_Province__c,Terms_of_Payment_Code__c,Terms_of_Payment__c,
						Incoterms_1_Code__c,Incoterms_1__c,Incoterms_2__c,Customer_Price_Group_Code__c,Customer_Price_Group__c,Price_List_Type_Code__c,Price_List_Type__c,Sales_Office_Code__c,State__c,ZIP_Postal_Code__c
						FROM ERP_Customer__c WHERE Customer_Code__c = :soldToCode AND Sales_Org_Code__c IN:salesOrgList AND Distribution_Channel_Code__c IN:distChannelList AND Division_Code__c IN:divisionList];
		system.debug('&&& rec '+perm_custRecord);
		system.debug('&&& rec size'+perm_custRecord.size());
		return null;
	}
}