objects/ERP_Sales_Prices_SAP__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Holder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Holder</label>
        <referenceTo>ERP_Sales_Prices_SAP__c</referenceTo>
        <relationshipLabel>ERP Sales Prices - SAP</relationshipLabel>
        <relationshipName>ERP_Sales_Prices_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <externalId>true</externalId>
        <label>Sales Org. Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPriceHolder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPriceHolder</label>
        <type>Checkbox</type>
    </fields>
    <label>ERP Sales Prices - SAP</label>
    <nameField>
        <displayFormat>SPSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP Sales Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Sales Prices - SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/batchClassForHolder_UT.cls
@isTest 
private class batchClassForHolder_UT {

    static testMethod void batchClassForHolderTestMethod() {
        
        PAUtil.insertProfileRecordId();
        // 12/30/2016 - Merge&Spin - Create dummy price holder record and assign it to price records.         
        ERP_Sales_Prices_SAP__c holderRecord = new ERP_Sales_Prices_SAP__c();
        holderRecord.isPriceHolder__c=true;
        insert holderRecord;
        
        ERP_Sales_Prices_SAP__c v =new ERP_Sales_Prices_SAP__c();
        
        v.isPriceHolder__c=false;
        //v.Key_Combination__c='Sales Org./Sold to/Project Id/PH1/PH2/PH3/PH4/PH5/PH6/Material Price Group';
        v.Key_Combination__c='Sales Org./Material';
        v.Sales_Org_Code__c='D660';
        v.BU__c = 'BI AP Surfaces';
        v.Price_Holder__c =System.label.PriceHolder_Id_for_batch; //<SS20220826> to get price holder id from label
       // v.Price_Holder__c =holderRecord.id;
        v.Approved_Date__c = system.today(); //
        
        ERP_Sales_Prices_SAP__c v1 =new ERP_Sales_Prices_SAP__c();
        
        v1.isPriceHolder__c=false;
        v1.Sales_Org_Code__c='D660';
        //v1.Key_Combination__c='Sales Org./Sold to/Project Id/PH1/PH2/PH3/PH4/PH5/PH6/Material Price Group';
        v1.Key_Combination__c='Sales Org./Material';
        v1.BU__c = 'BI AP Surfaces';
        // v.Price_Holder__c =holderRecord.id;
        v1.Price_Holder__c =System.label.PriceHolder_Id_for_batch; //<SS20220826> to get price holder id from label
        v1.Approved_Date__c = system.today(); //
        
     list<sObject> c=new list<ERP_Sales_Prices_SAP__c>();
     c.add(v);
     c.add(v1);

       
     insert c;
    

     test.startTest();
     batchClassForHolder bc=new batchClassForHolder();
     Database.executeBatch(bc, 200); 
     test.stopTest();    
    }
}