objects/ERP_Sales_Prices_SAP__c.object
<CustomObject>
    <fields>
        <fullName>Calculation_Type__c</fullName>
        <label>Calculation Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Calculation_Type_Code__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Quantity</fullName>
                </value>
                <value>
                    <fullName>Percentage</fullName>
                </value>
                <value>
                    <fullName>Fixed Amount</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Check_Scale__c</fullName>
        <label>Check Scale</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Check_Scale_Code__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Descending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer_Price_Payment_Terms__c</fullName>
        <label>Customer Price Payment Terms</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>F_Product_Hierarchy_Code__c</fullName>
        <formula>PH1_Code__c &amp; PH2_Code__c &amp;  PH3_Code__c &amp; PH4_Code__c &amp;  PH5_Code__c &amp;  PH6_Code__c &amp;  PH7_Code__c  &amp; PH8_Code__c &amp;  PH9_Code__c</formula>
        <label>Product Hierarchy Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination_Code__c</fullName>
        <label>Key Combination Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Code__c</fullName>
        <label>Material Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCKC__c</fullName>
        <description>Concatenation of Pricing Condition and Key Combination</description>
        <formula>Pricing_Condition_Code__c &amp;Sales_Org_Code__c&amp; Distribution_Channel_Code__c &amp; Division_Code__c &amp; Sold_To_Code__c &amp; Material_Code__c&amp;F_Product_Hierarchy_Code__c&amp; ShipTo_Code__c &amp; Sales_Office_Code__c &amp; Customer_Price_Group_Code__c &amp; Material_Price_Group_Code__c &amp; Price_List_Type_Code__c&amp; Terms_of_Payment_Code__c &amp; Project_Id__c &amp;End_Use_Code__c&amp; Market_Segment_Code__c&amp; Variant_Code__c&amp; Contract_Code__c &amp; Sales_Order_Type_Code__c &amp; ComPartner_Code__c &amp; Material_Group_5_Key_Code__c &amp; Plant_Code__c &amp; Shipping_Condition_Code__c &amp; Destination_Country_Code__c &amp; Price_Ref_Partner_Code__c &amp; Country_Code__c&amp; End_User_Code__c &amp; Customer_Hierarchy_Code__c &amp; Profit_Center_Code__c &amp; Ship_To_Country_Code__c &amp; Incoterms_1_Code__c &amp; Kcode__c &amp; Material_Group_1_Code__c &amp; Sales_District_Code__c &amp; Partner_ZF_Code__c &amp; Payer_Code__c &amp; TEXT( FixValDate__c ) &amp; Disc_Ref_No__c &amp; Campaign_Code__c &amp; Document_Currency__c &amp; State_Code__c &amp; Distributor_Code__c &amp; Sales_Order_Item_Code__c &amp;  Value_Center_Code__c &amp;  Ext_Matl_Grp_Code__c &amp;  Material_group_2_Code__c &amp;  Price_Zone_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PCKC</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Terms_Fixed_Date__c</fullName>
        <description>This will hold the date of the payment term selected for the price record</description>
        <label>Payment Terms Fixed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Per__c</fullName>
        <label>Per</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plus_Minus__c</fullName>
        <label>Plus/Minus</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Plus_Minus_Code__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Condition_Code__c</fullName>
        <externalId>true</externalId>
        <label>Pricing Condition Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Request</label>
        <referenceTo>Pricing_Request__c</referenceTo>
        <relationshipLabel>ERP Sales Prices - SAP</relationshipLabel>
        <relationshipName>ERP_Sales_Prices_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>Product Hierarchy</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate10__c</fullName>
        <label>ScaleRate10</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate1__c</fullName>
        <label>ScaleRate1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate2__c</fullName>
        <label>ScaleRate2</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate3__c</fullName>
        <label>ScaleRate3</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate4__c</fullName>
        <label>ScaleRate4</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate5__c</fullName>
        <label>ScaleRate5</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate6__c</fullName>
        <label>ScaleRate6</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate7__c</fullName>
        <label>ScaleRate7</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate8__c</fullName>
        <label>ScaleRate8</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ScaleRate9__c</fullName>
        <label>ScaleRate9</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value10__c</fullName>
        <label>Scale Quantity/ Scale Value10</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value1__c</fullName>
        <label>Scale Quantity/ Scale Value1</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value2__c</fullName>
        <label>Scale Quantity/ Scale Value2</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value3__c</fullName>
        <label>Scale Quantity/ Scale Value3</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value4__c</fullName>
        <label>Scale Quantity/ Scale Value4</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value5__c</fullName>
        <label>Scale Quantity/ Scale Value5</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value6__c</fullName>
        <label>Scale Quantity/ Scale Value6</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value7__c</fullName>
        <label>Scale Quantity/ Scale Value7</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value8__c</fullName>
        <label>Scale Quantity/ Scale Value8</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Quantity_Scale_Value9__c</fullName>
        <label>Scale Quantity/ Scale Value9</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale_Type__c</fullName>
        <label>Scale Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Scale_Type_Code__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>To</fullName>
                </value>
                <value>
                    <fullName>Base-Scale</fullName>
                </value>
                <value>
                    <fullName>From</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Scale_UoM_Scale_Unit__c</fullName>
        <label>Scale UoM/Scale Unit</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scaled_Price_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Scaled Price Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isPriceHolder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPriceHolder</label>
        <type>Checkbox</type>
    </fields>
    <label>ERP Sales Prices - SAP</label>
    <nameField>
        <displayFormat>SPSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP Sales Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Sales Prices - SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Material__c.object
<CustomObject>
    <fields>
        <fullName>Per__c</fullName>
        <label>Per</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <description>Name of the concatenation of the 9 Product Hierarchy Levels, does not exist in SAP</description>
        <label>Product Hierarchy</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_to__c</fullName>
        <label>Valid to</label>
        <type>Date</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product_Hierarchy__c.object
<CustomObject>
    <description>Product Hierarchy Master storing all the PH available</description>
    <label>Product Hierarchy</label>
    <nameField>
        <displayFormat>PH-{00000}</displayFormat>
        <label>Product Hierarchy Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Hierarchy</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PAScalePrice.cls
public class PAScalePrice {

public string sapId{get;set;}
public boolean showScale{get;set;}
public ERP_Sales_Prices_SAP__c listOfPrices{get;set;}
public void showScale()
{
	showScale = true;
	system.debug(sapID);
	if(sapID!=null)
    {
    	listOfPrices = [select id,Pricing_Request__r.Name,Scale_Quantity_Scale_Value1__c ,ScaleRate1__c,
						Scale_Quantity_Scale_Value2__c ,ScaleRate2__c,Scale_Quantity_Scale_Value3__c ,ScaleRate3__c,
						Scale_Quantity_Scale_Value4__c ,ScaleRate4__c,Scale_Quantity_Scale_Value5__c ,ScaleRate5__c,
						Scale_Quantity_Scale_Value6__c,ScaleRate6__c,Scale_Quantity_Scale_Value7__c,Scale_Quantity_Scale_Value8__c,
						Scale_Quantity_Scale_Value9__c,	ScaleRate7__c,ScaleRate8__c,ScaleRate9__c,ScaleRate10__c,Scale_Quantity_Scale_Value10__c,
						Scale_UoM_Scale_Unit__c,F_Product_Hierarchy_Code__c,unit__c,pckc__C,Key_Combination__c,
						Sold_To_Code__c, Pricing_Condition_Code__c,Key_Combination_Code__c,Material_Code__c,rate__C,
						per__c, UOM__C,Valid_From__c,Valid_To__c,Scaled_Price_Flag__c,Customer_Price_Payment_Terms__c,
						Payment_Terms_Fixed_Date__c,Calculation_Type__c,Plus_Minus__c,Check_Scale__c,Product_Hierarchy__c ,Material__c,Scale_Type__c from ERP_Sales_Prices_SAP__c where isPriceHolder__c =false and id=:sapID];
		system.debug(listOfPrices);
    } 
} 

public void closeWindow()
	{
		showScale = false;
	}
}