objects/ERP_Customer__c.object
<CustomObject>
    <description>Contains customer master from SAP. Updated by SAP-SFDC interface only.</description>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <description>Key with which the customer can be identified within the SAP system.Gives an alphanumeric key, which clearly identifies the customer or vendor in the SAP system.</description>
        <label>Customer Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Organizational Group ( as ERP Sales Area )</description>
        <label>Sales Area</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>ERP Customers</relationshipLabel>
        <relationshipName>ERP_Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Pricing_Procedure__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Procedure_Code__c</fullName>
        <label>Pricing Procedure Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Procedure__c</fullName>
        <label>Pricing Procedure</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ERP Pricing Procedure</label>
    <nameField>
        <displayFormat>ERP_PP-{00000}</displayFormat>
        <label>ERP Pricing Procedure</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Pricing Procedures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Organizational_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items (Business1)</relationshipLabel>
        <relationshipName>Organizational_Group_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ERP_Pricing_Procedure__c</fullName>
        <label>ERP Pricing Procedure</label>
        <referenceTo>ERP_Pricing_Procedure__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>BU_Org_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>OrgGroup</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>Organizational_Group_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Organizational Group Item</label>
    <nameField>
        <displayFormat>OGI-{00000}</displayFormat>
        <label>Organizational Group Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Organizational_Group_User__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <formula>Organizational_Group_Item__r.Business__r.Business__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group Item</label>
        <referenceTo>Organizational_Group_Item__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <formula>OrgGroup__r.ERP_Sales_Org_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sales Org Code</label>
        <type>Text</type>
    </fields>
    <label>Organizational Group Users</label>
    <nameField>
        <displayFormat>OGU-{00000}</displayFormat>
        <label>Organizational Group User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ERP_Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>The DuPont Business (Business Unit) or legal entity</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PAChangeSalesArea_UT.cls
/*
 * Name		 :   PAChangeSalesArea_UT
 * Description  :   This is the test class for PAChangeSalesArea
 * Author	   :   Infosys Limited
 * Created Date :   20-03-2013
 *
 * Version	  Modified Date	   Modified By	 Modification
 * ------------------------------------------------------------------------------
 */
@isTest
private class PAChangeSalesArea_UT
{
	static testMethod void PAChangeSalesAreaTestMethod()
	{
		PAChangeSalesArea changeSA = new PAChangeSalesArea();
		List<ERP_Customer__c> erpCustList = new List<ERP_Customer__c>();
		ERP_Customer__c cust = new ERP_Customer__c();
		cust.Customer_Code__c = '123';
		cust.Sales_Org_Code__c='A640';
		cust.Distribution_Channel_Code__c='10';
		cust.Division_Code__c='02';
		erpCustList.add(cust);
		ERP_Customer__c cust1 = new ERP_Customer__c();
		cust1.Customer_Code__c = '123';
		cust1.Sales_Org_Code__c='A641';
		cust1.Distribution_Channel_Code__c='10';
		cust1.Division_Code__c='02';
		erpCustList.add(cust1);
		insert erpCustList;
		
		Recordtype recType = [select id,name from Recordtype where name = 'Business'];
		Recordtype recType1 = [select id,name from Recordtype where name = 'ERP Sales Area'];
		List<OrgGroup__c> orgGrpList = new List<OrgGroup__c>();
		OrgGroup__c orgGrp = new OrgGroup__c();
		orgGrp.Business__c = 'Surfaces';
		orgGrp.RecordTypeId = recType.id;
		orgGrpList.add(orgGrp);
		OrgGroup__c orgGrp1 = new OrgGroup__c();
		orgGrp1.ERP_Sales_Org_Code__c = 'A640';
		orgGrp1.ERP_Distribution_Channel_Code__c='10';
		orgGrp1.ERP_Division_Code__c='02';
		orgGrp1.RecordTypeId = recType1.id;
		orgGrpList.add(orgGrp1);
		OrgGroup__c orgGrp2 = new OrgGroup__c();
		orgGrp2.ERP_Sales_Org_Code__c = 'A641';
		orgGrp2.ERP_Distribution_Channel_Code__c='10';
		orgGrp2.ERP_Division_Code__c='02';
		orgGrp2.RecordTypeId = recType1.id;
		orgGrpList.add(orgGrp2);
		insert orgGrpList;
		
		ERP_Pricing_Procedure__c erpPP = new ERP_Pricing_Procedure__c();
		erpPP.Pricing_Procedure_Code__c = 'PP001';
		erpPP.Pricing_Procedure__c = 'PP Surfaces';
		insert erpPP;
		
		List<Organizational_Group_Item__c> ogItemList = new List<Organizational_Group_Item__c>();
		Organizational_Group_Item__c ogItem = new Organizational_Group_Item__c();
		ogItem.ERP_Pricing_Procedure__c = erpPP.Id;
		ogItem.Business__c = orgGrpList[0].id;
		ogItem.OrgGroup__c = orgGrpList[1].id;
		ogItemList.add(ogItem);
		Organizational_Group_Item__c ogItem1 = new Organizational_Group_Item__c();
		ogItem1.ERP_Pricing_Procedure__c = erpPP.Id;
		ogItem1.Business__c = orgGrpList[0].id;
		ogItem1.OrgGroup__c = orgGrpList[2].id;
		ogItemList.add(ogItem1);
		insert ogItemList;
		
		List<Organizational_Group_User__c> ogUserList = new List<Organizational_Group_User__c>();
		Organizational_Group_User__c ogUser = new Organizational_Group_User__c();
		ogUser.Organizational_Group_Item__c=ogItemList[0].id;
		ogUser.OrgGroup__c=orgGrpList[1].id;
		ogUser.Related_User__c=UserInfo.getUserId();
		ogUserList.add(ogUser);
		Organizational_Group_User__c ogUser1 = new Organizational_Group_User__c();
		ogUser1.Organizational_Group_Item__c=ogItemList[1].id;
		ogUser1.OrgGroup__c=orgGrpList[2].id;
		ogUser1.Related_User__c=UserInfo.getUserId();
		ogUserList.add(ogUser1);
		insert ogUserList;
		
		changeSA.selectedBusiness = orgGrpList[0].id;
		changeSA.action();
		changeSA.displayPopUpWindow();
		changeSA.dosearch();
		changeSA.returnData();
		changeSA.closeWindow();
		
		
	}
}