objects/ERP_Pricing_Procedure__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Procedure__c</fullName>
        <label>Pricing Procedure</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ERP Pricing Procedure</label>
    <nameField>
        <displayFormat>ERP_PP-{00000}</displayFormat>
        <label>ERP Pricing Procedure</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Pricing Procedures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Sales_Prices_SAP__c.object
<CustomObject>
    <label>ERP Sales Prices - SAP</label>
    <nameField>
        <displayFormat>SPSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP Sales Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Sales Prices - SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Organizational_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items (Business1)</relationshipLabel>
        <relationshipName>Organizational_Group_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ERP_Pricing_Procedure__c</fullName>
        <label>ERP Pricing Procedure</label>
        <referenceTo>ERP_Pricing_Procedure__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>BU_Org_Group</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>OrgGroup</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>Organizational_Group_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Organizational Group Item</label>
    <nameField>
        <displayFormat>OGI-{00000}</displayFormat>
        <label>Organizational Group Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Organizational_Group_User__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <formula>Organizational_Group_Item__r.Business__r.Business__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group Item</label>
        <referenceTo>Organizational_Group_Item__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Organizational Group Users</label>
    <nameField>
        <displayFormat>OGU-{00000}</displayFormat>
        <label>Organizational Group User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>The DuPont Business (Business Unit) or legal entity</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/activePrices_UT.cls
@isTest
public class activePrices_UT{
    public static  testmethod  void activePrices_Testmethod(){
        Test.startTest();
        activePrices ap=new activePrices();
        list<Organizational_Group_User__c> ogiList = new list<Organizational_Group_User__c>();
        string selectedBusiness='Test business';
        ERP_Pricing_Procedure__c epp=new ERP_Pricing_Procedure__c();
        epp.Pricing_Procedure__c='Test pricing procedure';
        insert epp;
        //ERP_Sales_Prices_SAP__c esps=new ERP_Sales_Prices_SAP__c ();
        
        OrgGroup__c og=new OrgGroup__c();
        //og.name='Test Org Group';
        og.Business__c='Test business';
        insert og;
        
        OrgGroup__c og1=new OrgGroup__c();
        //og.name='Test Org Group';
        og1.Business__c='Test business1';
        insert og1;
        
        Organizational_Group_Item__c ogi=new Organizational_Group_Item__c();
        //ogi.name='Test organization group item';
        ogi.Business__c=og.id;
        ogi.ERP_Pricing_Procedure__c=epp.id;
        ogi.OrgGroup__c=og.id;
        insert ogi;
        
        Organizational_Group_Item__c ogi1=new Organizational_Group_Item__c();
        //ogi.name='Test organization group item';
        ogi1.Business__c=og1.id;
        ogi1.ERP_Pricing_Procedure__c=epp.id;
        ogi1.OrgGroup__c=og.id;
        insert ogi1;
        ap.getBusinessList();
        
        Organizational_Group_User__c ogu=new Organizational_Group_User__c();
        //ogu.name='test organization group user';
        ogu.OrgGroup__c=og.id;
        ogu.Organizational_Group_Item__c=ogi.id;
        ogu.Related_User__c=UserInfo.getUserId();
        insert ogu;
        Organizational_Group_User__c ogu1=new Organizational_Group_User__c();
        //ogu.name='test organization group user';
        ogu1.OrgGroup__c=og1.id;
        ogu1.Organizational_Group_Item__c=ogi1.id;
        ogu1.Related_User__c=UserInfo.getUserId();
        insert ogu1;
        ogiList.add(ogu1);
        
        try{
            ap.getBusinessList();
            
            ap.selectedBusiness='DPT EMEA';
            ap.executeButton();
            ap.executeButton();
        }Catch(Exception e){
            System.debug('***Exception occurred '+e);
        }
        Test.stopTest();
    }
    
}