objects/ERP_Customer__c.object
<CustomObject>
    <description>Contains customer master from SAP. Updated by SAP-SFDC interface only.</description>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Source_Cluster__c</fullName>
        <description>Specific SAP box or cluster where the data of this record originates.</description>
        <label>Source Cluster</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Customer_Localization__c.object
<CustomObject>
    <description>Used to manage the translations of customer master data, as stored in SAP</description>
    <fields>
        <fullName>ERP_Customer__c</fullName>
        <description>Master record that this localization record is the translation of</description>
        <label>ERP Customer</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Customer Localizations</relationshipLabel>
        <relationshipName>ERP_Customer_Localizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Language to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ERP Customer Localization</label>
    <nameField>
        <displayFormat>CL-{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Customer Localizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ERP_Export_to_SAP__c.object
<CustomObject>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Condition__c</fullName>
        <label>Pricing Condition</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Request</label>
        <referenceTo>Pricing_Request__c</referenceTo>
        <relationshipLabel>ERP-Export to SAP</relationshipLabel>
        <relationshipName>ERP_Export_to_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ERP-Export to SAP</label>
    <nameField>
        <displayFormat>EEXP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP-Export to SAP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP-Export to SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Key_Combination__c.object
<CustomObject>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ERP Key Combination</label>
    <nameField>
        <displayFormat>ERP_KC-{00000}</displayFormat>
        <label>ERP Key Combination Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Key Combination</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Material_Conversion_Factor__c.object
<CustomObject>
    <description>Contains material conversion factors of Material records, as stored in SAP</description>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combination of Material.External_ERP_ID__c + Base UOM to identify a unique record</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <description>Identifies the Material record that this ERP Material Conversion Factor record belongs to</description>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>ERP Material Conversion Factors</relationshipLabel>
        <relationshipName>Material_Conversion_Factors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ERP Material Conversion Factor</label>
    <nameField>
        <displayFormat>MCF-{0000000000}</displayFormat>
        <label>ERP Material Conversion Factor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Material Conversion Factors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ERP_Pricing_Condition__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Condition__c</fullName>
        <label>Pricing Condition</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ERP Pricing Condition</label>
    <nameField>
        <displayFormat>ERP_PC-{0000}</displayFormat>
        <label>ERP Pricing Condition Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Pricing Conditions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Pricing_Procedure__c.object
<CustomObject>
    <fields>
        <fullName>Pricing_Procedure__c</fullName>
        <label>Pricing Procedure</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>ERP Pricing Procedure</label>
    <nameField>
        <displayFormat>ERP_PP-{00000}</displayFormat>
        <label>ERP Pricing Procedure</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Pricing Procedures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Relationship__c.object
<CustomObject>
    <description>Used to manage the types of partner relationships an ERP customer might have (Sold-To, Ship-To, End User, Sales Rep, CSR etc.), as stored in SAP</description>
    <fields>
        <fullName>ERP_Customer__c</fullName>
        <description>Identifies the ERP Customer this record belongs to</description>
        <label>ERP Customer</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Relationships</relationshipLabel>
        <relationshipName>ERP_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code + Partner Counter + Partner Function Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ERP Relationship</label>
    <nameField>
        <displayFormat>ERP-R{000000000}</displayFormat>
        <label>ERP Relationship  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ERP_Sales_Prices_SAP__c.object
<CustomObject>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Condition__c</fullName>
        <label>Pricing Condition</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Request</label>
        <referenceTo>Pricing_Request__c</referenceTo>
        <relationshipLabel>ERP Sales Prices - SAP</relationshipLabel>
        <relationshipName>ERP_Sales_Prices_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ERP Sales Prices - SAP</label>
    <nameField>
        <displayFormat>SPSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP Sales Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Sales Prices - SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Material__c.object
<CustomObject>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the  Source Cluster + Material Cod + Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Material_Localization__c.object
<CustomObject>
    <description>Used to manage the translations of material master data, as stored in SAP</description>
    <fields>
        <fullName>Material__c</fullName>
        <description>Master record that this localization record is the translation of</description>
        <label>Material</label>
        <referenceTo>Material__c</referenceTo>
        <relationshipLabel>Material Localizations</relationshipLabel>
        <relationshipName>Material_Localizations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Material Localization</label>
    <nameField>
        <displayFormat>ML-{0000000000}</displayFormat>
        <label>Material Localization Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Material Localizations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Condition__c</fullName>
        <label>Pricing Condition</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricing_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>ERP_Pricing_Procedure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ERP Pricing Procedure</label>
        <referenceTo>ERP_Pricing_Procedure__c</referenceTo>
        <relationshipLabel>Pricing Request Item</relationshipLabel>
        <relationshipName>Pricing_Request_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Prices_SAP__c</fullName>
        <label>ERP Sales Prices - SAP</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Condition__c</fullName>
        <label>Pricing Condition</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <label>Pricing Request</label>
        <referenceTo>Pricing_Request__c</referenceTo>
        <relationshipLabel>Pricing Request Item</relationshipLabel>
        <relationshipName>Pricing_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pricing Request Item</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Request Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Request Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Prices__c.object
<CustomObject>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Condition__c</fullName>
        <label>Pricing Condition</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pricing Request</label>
        <referenceTo>Pricing_Request__c</referenceTo>
        <relationshipLabel>Sales Prices - Non SAP</relationshipLabel>
        <relationshipName>Sales_Prices_Non_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Prices - Non SAP</label>
    <nameField>
        <displayFormat>SPNSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Sales Prices - Non SAP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Prices - Non SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SandBoxRefreshUpdateBatch_UT.cls
/*********************************************************************************************
Copyright © 2020 DuPont. All rights reserved. 
Author: Rajan Kumar Mishra
Email: rajankumar.mishra@tcs.com
Last Modified Date : 12th Feb 2020
Description: This is the test class for all batch class which are being used for PostRefreshSandbox requirement.
**********************************************************************************************/
@isTest
public class SandBoxRefreshUpdateBatch_UT {
    @testSetup 
    static void setup() {
        List<ERP_Customer__c> erpcList = new List<ERP_Customer__c>();
        List<Material__c> matList = new List<Material__c>();
        List<ERP_Material_Conversion_Factor__c> matcList = new List<ERP_Material_Conversion_Factor__c>();
        List<ERP_Relationship__c> erprList = new List<ERP_Relationship__c>();
        List<ERP_Pricing_Procedure__c> ppList = new List<ERP_Pricing_Procedure__c>();
        List<ERP_Pricing_Condition__c> pcList = new List<ERP_Pricing_Condition__c>();
        List<ERP_Key_Combination__c> kcList = new List<ERP_Key_Combination__c>();
		List<Pricing_Request__c> prList = new List<Pricing_Request__c>();
        List<Pricing_Request_Item__c> priList = new List<Pricing_Request_Item__c>();
        List<ERP_Customer_Localization__c> clList = new List<ERP_Customer_Localization__c>();
		List<Material_Localization__c> mlList = new List<Material_Localization__c>();
        List<ERP_Export_to_SAP__c> etList = new List<ERP_Export_to_SAP__c>();
        List<Sales_Prices__c> spList = new List<Sales_Prices__c>();
        List<ERP_Sales_Prices_SAP__c> psList = new List<ERP_Sales_Prices_SAP__c>();

        for (Integer i=0;i<3;i++) {
                erpcList.add(new ERP_Customer__c(name='TestERP '+i, 
                    Source_Cluster__c='P23', External_ERP_ID__c='P23-ExtERP'+i));
                
                matList.add(new Material__c(name='TestMat'+i, 
                    ERP_Source_Cluster__c='P23', External_ERP_ID__c='P23-ExtERP'+i));
                
                ppList.add(new ERP_Pricing_Procedure__c(Pricing_Procedure__c ='TestPP'+i, 
                    SAP_Cluster__c='P23'));
                
                pcList.add(new ERP_Pricing_Condition__c(Pricing_Condition__c ='TestPC'+i, 
                    SAP_Cluster__c='P23'));
                
                kcList.add(new ERP_Key_Combination__c(Key_Combination__c ='TestKC'+i, 
                    SAP_Cluster__c='P23'));
                
                prList.add(new Pricing_Request__c(Project_Name__c ='TestKC'+i, 
                    SAP_Cluster__c='P23', BU__c = 'TestBU'+i));
                
                etList.add(new ERP_Export_to_SAP__c(Material__c ='TestMaterial'+i, 
                    SAP_Cluster__c='P23'));
                
                spList.add(new Sales_Prices__c(Material__c ='TestMaterial'+i, 
                    SAP_Cluster__c='P23', BU__c = 'TestBU'+i));
            
            	psList.add(new ERP_Sales_Prices_SAP__c(Material__c ='TestMaterial'+i, 
                    SAP_Cluster__c='P23', BU__c = 'TestBU'+i));
            }

        	insert erpcList;
        	insert matList;
        	insert ppList;
        	insert pcList;
        	insert kcList;
        	insert prList;
        	insert etList;
        	insert spList;
        	insert psList;
        
            for (Integer j=0;j<2;j++) {
                matcList.add(new ERP_Material_Conversion_Factor__c(External_ERP_ID__c='P23-ExtERP'+j,
                    Material__c = matList[0].id, Base_UOM_Text__c = 'TestBaseUOM' +j));
                
                erprList.add(new ERP_Relationship__c(External_ERP_ID__c='P23-ExtERP'+j,
                    ERP_Customer__c = erpcList[0].id, Name__c = 'TestERPRelationship' +j));
                
                priList.add(new Pricing_Request_Item__c(Pricing_Condition__c='TestPriceCon'+j,
                    Pricing_Request__c = prList[0].id, SAP_Cluster__c='P23'));
                
                clList.add(new ERP_Customer_Localization__c(External_ERP_ID__c='P23-ExtERP'+j,
                    ERP_Customer__c = erpcList[0].id, Customer_Name__c='TestCustomer'+j));
                
                mlList.add(new Material_Localization__c(External_ERP_ID__c='P23-ExtERP'+j,
                    Material__c = matList[0].id, Material_Name__c='TestMaterial'+j));
            }
        
        	insert matcList;
        	insert erprList;
        	insert priList;
        	insert clList;
        	insert mlList;        
    }    
    
    @isTest
    static void testBatchUpdate_ERPCustomer() {
        Test.startTest();
            BatchUpdate_ERPCustomer erpc = new BatchUpdate_ERPCustomer();
            Id batchId = Database.executeBatch(erpc);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from ERP_Customer__c where name like '%TestERP%']);
    }
    
    @isTest
    static void testBatchUpdate_Materials() {
        Test.startTest();
            BatchUpdate_Materials mat = new BatchUpdate_Materials();
            Id batchId = Database.executeBatch(mat);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from Material__c where name like '%TestMat%']);
    }
    
    @isTest
    static void testBatchUpdate_MaterialConversion() {
        Test.startTest();
            BatchUpdate_MaterialConversion matc = new BatchUpdate_MaterialConversion();
            Id batchId = Database.executeBatch(matc);
        Test.stopTest();
        
        System.assertEquals(2, [select count() from ERP_Material_Conversion_Factor__c where Base_UOM_Text__c like '%TestBaseUOM%']);
    }
    
    @isTest
    static void testBatchUpdate_ERPRelationship() {
        Test.startTest();
            BatchUpdate_ERPRelationship erpr = new BatchUpdate_ERPRelationship();
            Id batchId = Database.executeBatch(erpr);
        Test.stopTest();
        
        System.assertEquals(2, [select count() from ERP_Relationship__c where Name__c like '%TestERPRelationship%']);
    }
    
    @isTest
    static void testBatchUpdate_PricingProcedure() {
        Test.startTest();
            BatchUpdate_PricingProcedure pp = new BatchUpdate_PricingProcedure();
            Id batchId = Database.executeBatch(pp);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from ERP_Pricing_Procedure__c where Pricing_Procedure__c like '%TestPP%']);
    }
    
    @isTest
    static void testBatchUpdate_PricingCondition() {
        Test.startTest();
            BatchUpdate_PricingCondition pc = new BatchUpdate_PricingCondition();
            Id batchId = Database.executeBatch(pc);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from ERP_Pricing_Condition__c where Pricing_Condition__c like '%TestPC%']);
    }
    
    @isTest
    static void testBatchUpdate_KeyCombinition() {
        Test.startTest();
            BatchUpdate_KeyCombinition kc = new BatchUpdate_KeyCombinition();
            Id batchId = Database.executeBatch(kc);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from ERP_Key_Combination__c where Key_Combination__c like '%TestKC%']);
    }
    
    @isTest
    static void testBatchUpdate_PricingRequest() {
        Test.startTest();
            BatchUpdate_PricingRequest pr = new BatchUpdate_PricingRequest();
            Id batchId = Database.executeBatch(pr);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from Pricing_Request__c where Project_Name__c like '%TestKC%']);
    }
    
    @isTest
    static void testBatchUpdate_PricingRequestItem() {
        Test.startTest();
            BatchUpdate_PricingRequestItem pri = new BatchUpdate_PricingRequestItem();
            Id batchId = Database.executeBatch(pri);
        Test.stopTest();
        
        System.assertEquals(2, [select count() from Pricing_Request_Item__c where Pricing_Condition__c like '%TestPriceCon%']);
    }
    
    @isTest
    static void testBatchUpdate_CustomerLocalization() {
        Test.startTest();
            BatchUpdate_CustomerLocalization cl = new BatchUpdate_CustomerLocalization();
            Id batchId = Database.executeBatch(cl);
        Test.stopTest();
        
        System.assertEquals(2, [select count() from ERP_Customer_Localization__c where Customer_Name__c like '%TestCustomer%']);
    }
    
    @isTest
    static void testBatchUpdate_MaterialLocalization() {
        Test.startTest();
            BatchUpdate_MaterialLocalization ml = new BatchUpdate_MaterialLocalization();
            Id batchId = Database.executeBatch(ml);
        Test.stopTest();
        
        System.assertEquals(2, [select count() from Material_Localization__c where Material_Name__c like '%TestMaterial%']);
    }
    
    @isTest
    static void testBatchUpdate_ExportSap_Timeline() {
        Test.startTest();
            BatchUpdate_ExportSap_Timeline et = new BatchUpdate_ExportSap_Timeline();
            Id batchId = Database.executeBatch(et);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from ERP_Export_to_SAP__c where Material__c like '%TestMaterial%']);
    }
    
    @isTest
    static void testBatchUpdate_SalesPriceNonSAP() {
        Test.startTest();
            BatchUpdate_SalesPriceNonSAP sp = new BatchUpdate_SalesPriceNonSAP();
            Id batchId = Database.executeBatch(sp);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from Sales_Prices__c where Material__c like '%TestMaterial%']);
    }
    
    @isTest
    static void testBatchUpdate_PricesSAP() {
        Test.startTest();
            BatchUpdate_PricesSAP ps = new BatchUpdate_PricesSAP();
            Id batchId = Database.executeBatch(ps);
        Test.stopTest();
        
        System.assertEquals(3, [select count() from ERP_Sales_Prices_SAP__c where Material__c like '%TestMaterial%']);
    }
}