objects/ERP_Sales_Prices_SAP__c.object
<CustomObject>
    <label>ERP Sales Prices - SAP</label>
    <nameField>
        <displayFormat>SPSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP Sales Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Sales Prices - SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Outbond_Notifier__c.object
<CustomObject>
    <description>Object to track the outbound messages sent from SFDC</description>
    <fields>
        <fullName>Object_ID__c</fullName>
        <label>Object ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Type__c</fullName>
        <label>Object Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Outbond Notifier</label>
    <nameField>
        <label>Outbond Notifier Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Outbond Notifiers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Price_Posting_Status__c.object
<CustomObject>
    <description>This is a generic template for Custom Object. With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>ERP_Sales_Price_SAP__c</fullName>
        <label>ERP Sales Prices - SAP</label>
        <referenceTo>ERP_Sales_Prices_SAP__c</referenceTo>
        <relationshipLabel>Price Posting Status</relationshipLabel>
        <relationshipName>Price_Posting_Status</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Price_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Record Id</label>
        <referenceTo>ERP_Sales_Prices_SAP__c</referenceTo>
        <relationshipLabel>Price Posting Status (Price Record Id)</relationshipLabel>
        <relationshipName>Price_Posting_Status1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>TextArea</type>
    </fields>
    <label>Price Posting Status</label>
    <nameField>
        <label>Price Posting Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Price Posting Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PANotificationFailureOnSAPUpdate_UT.cls
@isTest
public class PANotificationFailureOnSAPUpdate_UT {
	
	
	static testmethod void insertPostingStatus()
	{
		ERP_Sales_Prices_SAP__C price = new ERP_Sales_Prices_SAP__C();
		price.CurrencyIsoCode = 'USD';
		insert price;
	
		Outbond_Notifier__c notifier = new Outbond_Notifier__c();
		notifier.Object_ID__c = price.id;
		notifier.Object_Type__c='ERP_Sales_Prices_SAP__C';
		insert notifier;
		
		Price_Posting_Status__c post = new Price_Posting_Status__c();
		post.Price_Record__c = price.id;
		post.ERP_Sales_Price_SAP__c=price.id;
		post.status__C='52';
		insert post;
		
		Price_Posting_Status__c post2 = new Price_Posting_Status__c();
		post2.Price_Record__c = price.id;
		post2.ERP_Sales_Price_SAP__c=price.id;
		post2.status__C='54';
		insert post2;
	}

}