objects/ERP_Customer__c.object
<CustomObject>
    <description>Contains customer master from SAP. Updated by SAP-SFDC interface only.</description>
    <fields>
        <fullName>Account_Group_Code__c</fullName>
        <description>The account group is a classifying feature within customer masterrecords. The account group determines in which number range the customer account number should be;whether the number is assigned by the user or by the system;which specifications are necessary or possible in the master record.</description>
        <label>Account Group Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>The city of this customer as stored in SAP.</description>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>The country af this customer as stored in SAP</description>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <description>Key with which the customer can be identified within the SAP system.Gives an alphanumeric key, which clearly identifies the customer or vendor in the SAP system.</description>
        <label>Customer Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Customer_Material_Key__c.object
<CustomObject>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Used to differentiate the Component and its assosicated values in the record.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Price Group</fullName>
                </value>
                <value>
                    <fullName>Material Price Group</fullName>
                </value>
                <value>
                    <fullName>Price List Type</fullName>
                </value>
                <value>
                    <fullName>Sales Office</fullName>
                </value>
                <value>
                    <fullName>Country</fullName>
                </value>
                <value>
                    <fullName>Material Group 3</fullName>
                </value>
                <value>
                    <fullName>Material Group 4</fullName>
                </value>
                <value>
                    <fullName>Terms of Payment</fullName>
                </value>
                <value>
                    <fullName>Pricing Exception</fullName>
                </value>
                <value>
                    <fullName>Incoterms</fullName>
                </value>
                <value>
                    <fullName>Sales Type</fullName>
                </value>
                <value>
                    <fullName>Variant</fullName>
                </value>
                <value>
                    <fullName>Sales Order Type</fullName>
                </value>
                <value>
                    <fullName>Sales District</fullName>
                </value>
                <value>
                    <fullName>Material Group 1</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Campaign</fullName>
                </value>
                <value>
                    <fullName>Document Currency</fullName>
                </value>
                <value>
                    <fullName>Material Group 5</fullName>
                </value>
                <value>
                    <fullName>Plant</fullName>
                </value>
                <value>
                    <fullName>Customer Group 4</fullName>
                </value>
                <value>
                    <fullName>Distributor Code</fullName>
                </value>
                <value>
                    <fullName>Shipping Condition</fullName>
                </value>
                <value>
                    <fullName>Sales Order Item</fullName>
                </value>
                <value>
                    <fullName>Value Center</fullName>
                </value>
                <value>
                    <fullName>Ext Matl Grp</fullName>
                </value>
                <value>
                    <fullName>Material Group 2</fullName>
                </value>
                <value>
                    <fullName>Price Zone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>ERP Customer - Material Key</label>
    <nameField>
        <displayFormat>CMK-{00000}</displayFormat>
        <label>ERP Customer - Material Key Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Customer - Material Key</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/ERP_Relationship__c.object
<CustomObject>
    <description>Used to manage the types of partner relationships an ERP customer might have (Sold-To, Ship-To, End User, Sales Rep, CSR etc.), as stored in SAP</description>
    <fields>
        <fullName>ERP_Customer__c</fullName>
        <description>Identifies the ERP Customer this record belongs to</description>
        <label>ERP Customer</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Relationships</relationshipLabel>
        <relationshipName>ERP_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Source Cluster + Customer Code + Sales Org Code + Distribution Channel Code + Division Code + Partner Counter + Partner Function Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Identifies the CSR or Sales Representative as stored in SAP.</description>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Function_Code__c</fullName>
        <description>Partner Function of the partner (Related ERP Customer) identified in this record</description>
        <label>Partner Function Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Related_ERP_Customer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the ERP Customer partner record (eg the Ship-to)</description>
        <label>Related ERP Customer</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Relationships (Related ERP Customer)</relationshipLabel>
        <relationshipName>ERP_Relationships1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ERP Relationship</label>
    <nameField>
        <displayFormat>ERP-R{000000000}</displayFormat>
        <label>ERP Relationship  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Org_Group_ERP_Key__c.object
<CustomObject>
    <fields>
        <fullName>ERP_Cus_Mat_Compt_Key__c</fullName>
        <label>ERP Customer - Material Key</label>
        <referenceTo>ERP_Customer_Material_Key__c</referenceTo>
        <relationshipLabel>Org Group ERP Key</relationshipLabel>
        <relationshipName>Org_Group_ERP_Key</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group Item</label>
        <referenceTo>Organizational_Group_Item__c</referenceTo>
        <relationshipLabel>Org Group ERP Key</relationshipLabel>
        <relationshipName>Org_Group_ERP_Key</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Org Group ERP Key</label>
    <nameField>
        <displayFormat>OGK-{00000}</displayFormat>
        <label>Org Group Key Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Org Group ERP Key</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>Combines the Sales Org Code + Distribution Channel Code + Division Code to identify a unique record.</description>
        <externalId>true</externalId>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>To identify the type of Organizational Group record this is</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ERP</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <recordTypes>
        <fullName>Business</fullName>
        <active>true</active>
        <description>The DuPont Business (Business Unit) or legal entity</description>
        <label>Business</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>E_Pass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems - found in MyAccess &amp; in the User&apos;s NAB Entry</description>
        <label>E-Pass ID</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</inlineHelpText>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED KINGDOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PA_ShipToSelection_UT.cls
/*
Date : 29/12/2016
Change : Merge & Spin- Updated the test  class to update the insert of UserRole and User.
*/
@isTest
public class  PA_ShipToSelection_UT{
    
    
   static testMethod void  PAShipToSelection_UT() { 
        //Start: Updated as a part of Merge & Spin to the change the UserRole name.
       Profile p =[SELECT Id FROM Profile where name='Price Approval-Price requester'];
      
      //UserRole r=[SELECT Id FROM UserRole WHERE developerName='BI_EMEA_D630']; 
      /*
      UserRole r=[SELECT Id FROM UserRole WHERE developerName='BI_EMEA_Surfaces']; 
      system.debug('roleeeeeeeeee'+r);              
        //[27122016] Merge&Spin: Updated External ERP Id to Dummy Value 
      User u= new User(Firstname='test2test2',Alias='Hill', Email='ambili_vinay@infosys.com', 
                         User_Country__c='UNITED KINGDOM',E_Pass_ID__c='rr9847',
                         External_ERP_ID__c='DummyTest1',profileid = p.id,
                         Username='testingtset2676@dupont.com.uttest2',UserRoleId=r.id, LastName='Hill', CommunityNickname='mm', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
      */
       UserRole Ur = TestUserUtil.createTestUserRole('BI-EMEA-Surfaces');
       insert Ur;
       User usr = TestUserUtil.createTestUser(Ur.Id,p.Id,'User1 FirstName','User1 LastName');
       insert usr;
       //End: Updated as a part of Merge & Spin to the change the UserRole name.
      system.runAs(usr){
      
      ERP_Customer__c customer=new ERP_Customer__c();
      customer.Account_Group_Code__c='Z002';
      customer.Customer_Code__c='Sample-0001';
      insert customer;
      
      ERP_Relationship__c relationship=new ERP_Relationship__c();
      relationship.ERP_Customer__c=customer.id;
      relationship.Partner_Function_Code__c='ZH';
      relationship.ERP_Customer__c=customer.id;
      //relationship.ERP_Customer__r.Customer_Code__c=customer.Customer_Code__c;
      relationship.Related_ERP_Customer__c = customer.id;
      insert relationship;
                  
      PAShipToSelection ShipToSelection=new PAShipToSelection();
      ShipToSelection.shipToCustomerCode='Sample-0001';
      ShipToSelection.componentType='PriceRefPartner';
      ShipToSelection.action();
      ShipToSelection.displayPopUpWindow();
      ShipToSelection.dosearch();
      ShipToSelection.returnData();
      ShipToSelection.closeWindow();
      
      PAShipToSelection ShipToSelection1=new PAShipToSelection();
      ShipToSelection1.shipToCode='Sample';
      ShipToSelection.shipToCustomerCode='Sample-0001';
      ShipToSelection.componentType='CustomerHierarchy';
      ShipToSelection1.action();
      ShipToSelection1.displayPopUpWindow();
      //ShipToSelection1.dosearch();
      ShipToSelection1.returnData();
      ShipToSelection1.closeWindow();
      
      PAShipToSelection ShipToSelection2=new PAShipToSelection();
      ShipToSelection2.shipToCode='Sample';   
      ShipToSelection2.componentType='PriceRefPartner';
      ShipToSelection2.action();
      ShipToSelection2.displayPopUpWindow();
      //ShipToSelection2.dosearch();
      ShipToSelection2.returnData();
      ShipToSelection2.closeWindow();
      
      PAShipToSelection ShipToSelection3=new PAShipToSelection();
      ShipToSelection3.shipToCode='Sample';  
      ShipToSelection3.componentType='';
      ShipToSelection3.action();
      ShipToSelection3.displayPopUpWindow();
      //ShipToSelection3.dosearch();
      ShipToSelection3.returnData();
      ShipToSelection3.closeWindow();     
      ShipToSelection3.shipToCustomerCode='Sample-0001';
      
      PAShipToSelection ShipToSelection4=new PAShipToSelection();
      ShipToSelection4.shipToCustomerCode='Sample-0001';
      ShipToSelection4.componentType='EndUser';
      ShipToSelection4.action();
      ShipToSelection4.displayPopUpWindow();
      //ShipToSelection4.dosearch();
      ShipToSelection4.returnData();
      ShipToSelection4.closeWindow();
      
      PAShipToSelection ShipToSelection5=new PAShipToSelection();
      ShipToSelection5.shipToCustomerCode='Sample-0001';
      ShipToSelection5.shipToCode='Sample'; 
      ShipToSelection5.componentType='EndUser';
      ShipToSelection5.action();
      ShipToSelection5.displayPopUpWindow();
      //ShipToSelection5.dosearch();
      ShipToSelection5.returnData();
      ShipToSelection5.closeWindow();
      
      PAShipToSelection ShipToSelection6=new PAShipToSelection();
      ShipToSelection6.shipToCode='';    
      ShipToSelection6.componentType='';
      ShipToSelection6.action();
      ShipToSelection6.displayPopUpWindow();
      //ShipToSelection6.dosearch();
      ShipToSelection6.returnData();
      ShipToSelection6.closeWindow();     
      ShipToSelection6.shipToCustomerCode='Sample-0001';
      ShipToSelection6.enablePopUpBoolean= null;
      
      }                
                         
   }
   //pooja
   static testMethod void  PAShipToSelection1_UT() { 
       Profile p =[SELECT Id FROM Profile where name='Price Approval-Price requester'];
      
      //UserRole r=[SELECT Id FROM UserRole WHERE developerName='BI_EMEA_D630']; 
      /*
      UserRole r=[SELECT Id FROM UserRole WHERE developerName='BI_EMEA_Surfaces']; 
      system.debug('roleeeeeeeeee'+r);              
    // [27122016] Merge&Spin: Updated External ERP Id to Dummy Value
      User u= new User(Firstname='test2test2',Alias='Hill', Email='ambili_vinay@infosys.com', 
                         User_Country__c='UNITED KINGDOM',E_Pass_ID__c='rr9847',
                         External_ERP_ID__c='DummyTest2',profileid = p.id,
                         Username='testingtset2676@dupont.com.uttest2',UserRoleId=r.id, LastName='Hill', CommunityNickname='mm', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
      */
      UserRole Ur = TestUserUtil.createTestUserRole('BI-EMEA-Surfaces');
      insert Ur;
      User usr = TestUserUtil.createTestUser(Ur.Id,p.Id,'User1 FirstName','User1 LastName');
      insert usr;
      //End: Updated as a part of Merge & Spin to the change the UserRole name.
      system.runAs(usr){
      
      ERP_Customer__c customer=new ERP_Customer__c();
      customer.Account_Group_Code__c='Z012';
      customer.Customer_Code__c=' ';
      customer.City__c=' ';
      customer.Country__c=' ';
      customer.Name=' ';
      insert customer;
      
      ERP_Relationship__c relationship=new ERP_Relationship__c();
      relationship.ERP_Customer__c=customer.id;
      relationship.Partner_Function_Code__c='ZV';
      relationship.ERP_Customer__c=customer.id;
      //relationship.ERP_Customer__r.Customer_Code__c=customer.Customer_Code__c;
      relationship.Related_ERP_Customer__c = customer.id;
      insert relationship;
      
      ERP_Relationship__c relationship1=new ERP_Relationship__c();
      relationship1.ERP_Customer__c=customer.id;
      relationship1.Partner_Function_Code__c='ZF';
      relationship1.ERP_Customer__c=customer.id;
      //relationship1.ERP_Customer__r.Customer_Code__c=customer.Customer_Code__c;
      relationship1.Related_ERP_Customer__c = customer.id;
      insert relationship1;
      
      
      ERP_Relationship__c relationship2=new ERP_Relationship__c();
      relationship2.ERP_Customer__c=customer.id;
      relationship2.Partner_Function_Code__c='RG';
      relationship2.ERP_Customer__c=customer.id;
      //relationship2.ERP_Customer__r.Customer_Code__c=customer.Customer_Code__c;
      relationship2.Related_ERP_Customer__c = customer.id;
      insert relationship2;
      
      /*List<Org_Group_ERP_Key__c> orgERPKeyCountry = new List<Org_Group_ERP_Key__c>();
      
      Org_Group_ERP_Key__c trial = new Org_Group_ERP_Key__c();
      trial.ERP_Cus_Mat_Compt_Key__r.Type__c = 'Country';
      trial.ERP_Cus_Mat_Compt_Key__r.Code__c='Bond007';
      trial.ERP_Cus_Mat_Compt_Key__r.Name__c='JamesBond';
      trial.Organizational_Group_Item__r.Business__c='BI_EMEA_Surfaces';
      trial.Organizational_Group_Item__r.OrgGroup__r.ERP_Sales_Org_Code__c='G250';
      trial.Organizational_Group_Item__r.OrgGroup__r.ERP_Distribution_Channel_Code__c='10';
      trial.Organizational_Group_Item__r.OrgGroup__r.ERP_Division_Code__c='02';
      
      insert trial;
      
      Org_Group_ERP_Key__c trial1 = [select ERP_Cus_Mat_Compt_Key__r.Name__c from Org_Group_ERP_Key__c where Id = :trial.Id];
      
      //orgERPKeyCountry.add(trial);
      
      //insert orgERPKeyCountry;
      
      List<SelectOption> countrySelectList = new List<SelectOption>();
      countrySelectList.add(new selectoption(trial1.ERP_Cus_Mat_Compt_Key__r.Name__c,trial1.ERP_Cus_Mat_Compt_Key__r.Name__c));*/
      
  
      PAShipToSelection ShipToSelection=new PAShipToSelection();
      ShipToSelection.shipToCustomerCode='Sample-0001';
      ShipToSelection.componentType='CustomerHierarchy';
      //ShipToSelection.listOfCountry=countrySelectList;
      ShipToSelection.action();
      ShipToSelection.displayPopUpWindow();
      ShipToSelection.dosearch();
      ShipToSelection.returnData();
      ShipToSelection.closeWindow();
      
      
      PAShipToSelection ShipToSelection1=new PAShipToSelection();
      ShipToSelection1.shipToCode='Sample';    
      ShipToSelection1.componentType='Partner ZF';
      ShipToSelection1.action();
      ShipToSelection1.displayPopUpWindow();
      //ShipToSelection1.dosearch();
      ShipToSelection1.returnData();
      ShipToSelection1.closeWindow();     
      ShipToSelection1.shipToCustomerCode='Sample-0001';
      

      PAShipToSelection ShipToSelection2=new PAShipToSelection();
      ShipToSelection2.shipToCode='Sample';    
      ShipToSelection2.componentType='Payer';
      ShipToSelection2.action();
      ShipToSelection2.displayPopUpWindow();
      //ShipToSelection2.dosearch();
      ShipToSelection2.returnData();
      ShipToSelection2.closeWindow();     
      ShipToSelection2.shipToCustomerCode='Sample-0001';
      
      
      PAShipToSelection ShipToSelection7=new PAShipToSelection();
      ShipToSelection7.shipToCode='Sample';    
      ShipToSelection7.componentType='ComPartner';
      ShipToSelection7.action();
      ShipToSelection7.displayPopUpWindow();
      //ShipToSelection7.dosearch();
      ShipToSelection7.returnData();
      ShipToSelection7.closeWindow();     
      ShipToSelection7.shipToCustomerCode='Sample-0001';
      //ShipToSelection7.helpLink();


      PAShipToSelection ShipToSelection8=new PAShipToSelection();
      ShipToSelection8.business='BI EMEA';
      //ShipToSelection8.listOfCountry;
      ShipToSelection8.label='Home';
      ShipToSelection8.hasNext=true;
      ShipToSelection8.hasPrevious=true;
      ShipToSelection8.pageNumber=5;
      ShipToSelection8.first();
      ShipToSelection8.last();
      ShipToSelection8.previous();
      ShipToSelection8.next();
      Boolean abc = ShipToSelection8.enablePopUpBoolean;
      
      }
    }
}