objects/ERP_Sales_Prices_SAP__c.object
<CustomObject>
    <fields>
        <fullName>Approved_Date__c</fullName>
        <label>Approved Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCKC__c</fullName>
        <description>Concatenation of Pricing Condition and Key Combination</description>
        <formula>Pricing_Condition_Code__c &amp;Sales_Org_Code__c&amp; Distribution_Channel_Code__c &amp; Division_Code__c &amp; Sold_To_Code__c &amp; Material_Code__c&amp;F_Product_Hierarchy_Code__c&amp; ShipTo_Code__c &amp; Sales_Office_Code__c &amp; Customer_Price_Group_Code__c &amp; Material_Price_Group_Code__c &amp; Price_List_Type_Code__c&amp; Terms_of_Payment_Code__c &amp; Project_Id__c &amp;End_Use_Code__c&amp; Market_Segment_Code__c&amp; Variant_Code__c&amp; Contract_Code__c &amp; Sales_Order_Type_Code__c &amp; ComPartner_Code__c &amp; Material_Group_5_Key_Code__c &amp; Plant_Code__c &amp; Shipping_Condition_Code__c &amp; Destination_Country_Code__c &amp; Price_Ref_Partner_Code__c &amp; Country_Code__c&amp; End_User_Code__c &amp; Customer_Hierarchy_Code__c &amp; Profit_Center_Code__c &amp; Ship_To_Country_Code__c &amp; Incoterms_1_Code__c &amp; Kcode__c &amp; Material_Group_1_Code__c &amp; Sales_District_Code__c &amp; Partner_ZF_Code__c &amp; Payer_Code__c &amp; TEXT( FixValDate__c ) &amp; Disc_Ref_No__c &amp; Campaign_Code__c &amp; Document_Currency__c &amp; State_Code__c &amp; Distributor_Code__c &amp; Sales_Order_Item_Code__c &amp;  Value_Center_Code__c &amp;  Ext_Matl_Grp_Code__c &amp;  Material_group_2_Code__c &amp;  Price_Zone_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PCKC</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Holder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Holder</label>
        <referenceTo>ERP_Sales_Prices_SAP__c</referenceTo>
        <relationshipLabel>ERP Sales Prices - SAP</relationshipLabel>
        <relationshipName>ERP_Sales_Prices_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Marks the active prices in a PCKC</description>
        <label>isActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPriceHolder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPriceHolder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>markForDeletion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>markForDeletion</label>
        <type>Checkbox</type>
    </fields>
    <label>ERP Sales Prices - SAP</label>
    <nameField>
        <displayFormat>SPSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>ERP Sales Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Sales Prices - SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/MarkActivePrices.cls
/*
 * Name      :      MarkActivePrices
 * Description  :   This Batch class marks all active prices for the provided business.
 * Author      :    Tata Consultancy Services <CC20191007>
 * Created Date :   07 October 2019
 *
 *   Ver.                     Developer                           Changes                                          Dependancies
---------------------------------------------------------------------------------------------------------------------------------------
 *
 
*/

global class MarkActivePrices implements Database.Batchable<sObject>, Database.Stateful{
    global final String selectedBu;
    global Map<String,ERP_Sales_Prices_SAP__c> allPrices= new Map<String,ERP_Sales_Prices_SAP__c>();
    global List<ERP_Sales_Prices_SAP__c> allActivePrices= new List<ERP_Sales_Prices_SAP__c>();
    global List<ERP_Sales_Prices_SAP__c> allNonPrices=new List<ERP_Sales_Prices_SAP__c>();
    
    global MarkActivePrices(String bu){
        selectedBu=bu;
    }

    global Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'select id,Price_Holder__c,PCKC__c,markForDeletion__c,isActive__c,Valid_From__c,Valid_To__c from ERP_Sales_Prices_SAP__c where isPriceHolder__c=false and Price_Holder__c!=null and BU__c like \'%'+selectedBu+'%\' order by PCKC__c,Approved_Date__c desc';
        system.debug('***query '+query);
        system.debug('***bu'+selectedBu);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<ERP_Sales_Prices_SAP__c> scope){
        if(scope!=null){
            for(ERP_Sales_Prices_SAP__c price : scope){
                if(allPrices!=null && allPrices.containsKey(price.PCKC__c)){
                    if(price.isActive__c==true){
                        price.isActive__c=false;
                        allNonPrices.add(price);
                    }
                }
                else{
                    system.debug('****pckc '+price.PCKC__c+' **valid from '+price.Valid_From__c+' ****valid to '+price.Valid_To__c+' **deletion '+price.markForDeletion__c+' **active '+price.isActive__c);
                    if(price.Valid_From__c<= System.today() && price.Valid_To__c>= System.today()){
                        allPrices.put(price.PCKC__c,price);
                        if(price.markForDeletion__c==false){
                            if(price.isActive__c==false){
                                price.isActive__c=true;
                                allActivePrices.add(price);
                            }
                        }
                        else{
                            if(price.isActive__c==true){
                                price.isActive__c=false;
                                allNonPrices.add(price);
                            }
                        }
                    }
                    else{
                        if(price.isActive__c==true){
                            price.isActive__c=false;
                            allNonPrices.add(price);
                        }
                    }
                }
            }
            System.debug('Count of allActivePrices '+allActivePrices.size());
            System.debug('Count of allNonPrices '+allNonPrices.size());
            System.debug('Count of allPrices '+allPrices.size());
            if(allActivePrices!=null && allActivePrices.size()>0){
                update allActivePrices;
                allActivePrices.clear();
            }
            if(allNonPrices!=null && allNonPrices.size()>0){
                update allNonPrices; 
                allNonPrices.clear();
            }
            
            // to work for Bulk data
            if(allPrices.size()>=48000){
                Set<String> allPricesKeySet=allPrices.keySet();
                List<String> allPricesKeyList= new List<String>();
                allPricesKeyList.addall(allPricesKeySet);
                String lastElement=allPricesKeyList[allPricesKeyList.size()-1];
                ERP_Sales_Prices_SAP__c lastPrice=allPrices.get(lastElement);
                allPrices.clear();
                allPrices.put(lastElement,lastPrice);
            }
        }
        
    }

    global void finish(Database.BatchableContext BC){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        User userEmail=[select Email from user where id=:UserInfo.getUserId() limit 1];
        String[] toAddresses = new String[] {userEmail.Email};
        mail.setToAddresses(toAddresses);
        mail.setSubject('Active Price Reporting is Completed for '+selectedBu);
        string temp=EncodingUtil.urlEncode(selectedBu, 'UTF-8');
        String reportlink=System.Label.ActivePricesReportLink;
        mail.setHtmlBody('<html lang="ja"><body>Please <a href="'+reportlink+temp+'">click </a>to run the report of Active Prices for '+ selectedBu +'.<footer><p>Thank you,<br>Salesforce.com Price Approval</p></footer></body></html>');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
}