objects/ERP_Customer__c.object
<CustomObject>
    <description>Contains customer master from SAP. Updated by SAP-SFDC interface only.</description>
    <fields>
        <fullName>Currency_Code__c</fullName>
        <description>Customer&apos;s currency for a sales area. This currency will be used to settle the customer&apos;s charges for the given sales organization.</description>
        <label>Currency Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Code__c</fullName>
        <description>Key with which the customer can be identified within the SAP system.Gives an alphanumeric key, which clearly identifies the customer or vendor in the SAP system.</description>
        <label>Customer Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Deletion_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates in the future this record is to be deleted or not, however they are not physically deleted yet for history maintenance purposes. This deletion applies in the specified sales area only.</description>
        <label>Deletion Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>ERP Customer</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ERP Customers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/ERP_Relationship__c.object
<CustomObject>
    <description>Used to manage the types of partner relationships an ERP customer might have (Sold-To, Ship-To, End User, Sales Rep, CSR etc.), as stored in SAP</description>
    <fields>
        <fullName>Deletion_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates partner record is deleted or not at SAP, and record will be deleted in SFDC through batch jobs. This deletion applies for a specified Customer only.</description>
        <label>Deletion Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ERP_Customer__c</fullName>
        <description>Identifies the ERP Customer this record belongs to</description>
        <label>ERP Customer</label>
        <referenceTo>ERP_Customer__c</referenceTo>
        <relationshipLabel>ERP Relationships</relationshipLabel>
        <relationshipName>ERP_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>ERP Relationship</label>
    <nameField>
        <displayFormat>ERP-R{000000000}</displayFormat>
        <label>ERP Relationship  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ERP Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/batchDeletionOfSalesRep_UT.cls
@Istest
public class batchDeletionOfSalesRep_UT {
	
static testmethod void batchDeletionOfSalesRep_UT()
{
    ERP_Customer__c erpCustomer1 = new ERP_Customer__c();
    erpCustomer1.Customer_Code__c = 'T001';
    erpCustomer1.Sales_Org_Code__c = 'A640';
    erpCustomer1.Distribution_Channel_Code__c = '10';
    erpCustomer1.Division_Code__c = '02';
    erpCustomer1.Currency_Code__c = 'USD';
    insert erpCustomer1;
    
    ERP_Relationship__c  relation = new ERP_Relationship__c();
	relation.Deletion_Flag__c = true;
    relation.ERP_Customer__c = erpCustomer1.id;
	insert relation;
	
    // testing batch class
    batchDeletionOfSalesRep batch = new batchDeletionOfSalesRep();
    database.executeBatch(batch);
    
    // testing scheduler
    batchDeletionOfSalesRep scheduler = new batchDeletionOfSalesRep();
	String sch = '0 0 * * * ?';
	system.schedule('deleteSalesRep', sch, scheduler );
}
}