objects/License_Procurement__c.object
<CustomObject>
    <description>A child object with master-detail relationship to the above object contains licenses procured with month and year. A status field to capture if the licenses are still active or not.</description>
    <fields>
        <fullName>Available_Licenses_Name__c</fullName>
        <description>Type of Available Licenses in selected License Catagory</description>
        <inlineHelpText>Type of Available Licenses in selected License Catagory</inlineHelpText>
        <label>Available Licenses Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>License_Catagories__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Available_Licenses_Name</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Catagories__c</fullName>
        <description>Categories of Salesforce License Offerings</description>
        <inlineHelpText>Categories of Licenses</inlineHelpText>
        <label>License Catagories</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>License_Catagories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <description>Date at which licenses will get expired or to be renewed.</description>
        <inlineHelpText>Date at which licenses will get expired or to be renewed.</inlineHelpText>
        <label>License Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Licenses__c</fullName>
        <description>The license record procurement is attached to</description>
        <inlineHelpText>The license record, procurement is attached to</inlineHelpText>
        <label>License</label>
        <referenceTo>Licenses__c</referenceTo>
        <relationshipLabel>License Procurements</relationshipLabel>
        <relationshipName>License_Procurements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Number_of_licenses_procured__c</fullName>
        <description>Total number of licenses procured</description>
        <inlineHelpText>Total number of licenses procured</inlineHelpText>
        <label>Number of licenses procured</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Procurement_Date__c</fullName>
        <description>Date of License Procurement</description>
        <inlineHelpText>Date of License Procurement</inlineHelpText>
        <label>Procurement Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Procuring_Business__c</fullName>
        <description>Business procuring the licenses</description>
        <inlineHelpText>Business procuring the licenses</inlineHelpText>
        <label>Procuring Business</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Procuring_Business</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of procured licenses</description>
        <inlineHelpText>Status of procured licenses</inlineHelpText>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>License Procurement</label>
    <nameField>
        <label>License Procurement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Procurements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Licenses__c.object
<CustomObject>
    <description>License custom object to capture business unit and number of licenses procured. Store threshold limit and alert notification email list here.</description>
    <fields>
        <fullName>Available_Licenses_Name__c</fullName>
        <description>Name of the Licenses Available under License Category</description>
        <inlineHelpText>Name of the Licenses Available under License Category</inlineHelpText>
        <label>Available Licenses Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>License_Catagories__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Available_Licenses_Name</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Catagories__c</fullName>
        <description>Catagories of License Type</description>
        <inlineHelpText>Catagories of License Type</inlineHelpText>
        <label>License Catagories</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>License_Catagories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Number_of_licenses_procured__c</fullName>
        <description>rollup summary of all License Procurements related records with status = active and business = Procuring Business.</description>
        <inlineHelpText>rollup summary of all License Procurements related records with status = active and business = Procuring Business.</inlineHelpText>
        <label>Number of licenses procured</label>
        <summarizedField>License_Procurement__c.Number_of_licenses_procured__c</summarizedField>
        <summaryFilterItems>
            <field>License_Procurement__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>License_Procurement__c.Licenses__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Procuring_Business__c</fullName>
        <description>Business procuring the license.</description>
        <inlineHelpText>Business procuring the license.</inlineHelpText>
        <label>Procuring Business</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Procuring_Business</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold_Email_Notifications__c</fullName>
        <description>List of email addresses to send mail, when the threshold limit is reached.</description>
        <inlineHelpText>List of email addresses to send mail, when the threshold limit is reached.</inlineHelpText>
        <label>Threshold Email Notification List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Threshold_Limit__c</fullName>
        <description>Limit to monitor the licenses</description>
        <inlineHelpText>Limit when reached, will send mail to admins.</inlineHelpText>
        <label>Threshold Limit</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Licenses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Procuring_Business__c</fullName>
        <description>Name of Business Procuring the License for the user</description>
        <inlineHelpText>Business sponsored the license</inlineHelpText>
        <label>Procuring Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Procuring_Business</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>UserOwningSBUOrg__c</fullName>
        <description>Business responsible for this User</description>
        <label>User Owning SBU Org</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED STATES</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AGCP-CPC</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DCF</fullName>
                </value>
                <value>
                    <fullName>DEC</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>DTT</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IB</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>N&amp;H</fullName>
                </value>
                <value>
                    <fullName>P&amp;IP</fullName>
                </value>
                <value>
                    <fullName>PNR</fullName>
                </value>
                <value>
                    <fullName>Adhesives &amp; Fluids</fullName>
                </value>
                <value>
                    <fullName>Multibase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Region__c</fullName>
        <label>User Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>EMEA</fullName>
                </value>
                <value>
                    <fullName>Latin America</fullName>
                </value>
                <value>
                    <fullName>North America</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Available_Licenses_Name.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Community</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Community</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Community Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Analytics Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Sales User</fullName>
    </customValue>
    <customValue>
        <fullName>Company Community for Force.com</fullName>
    </customValue>
    <customValue>
        <fullName>Lightning Console</fullName>
    </customValue>
    <customValue>
        <fullName>Standard Einstein Activity Capture User</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Console User</fullName>
    </customValue>
    <customValue>
        <fullName>CRM User</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Search</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Next Best Action - Unlimited Requests</fullName>
    </customValue>
    <customValue>
        <fullName>Trust Card Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chatter Answers User</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud User</fullName>
    </customValue>
    <customValue>
        <fullName>Chat User</fullName>
    </customValue>
    <customValue>
        <fullName>Flow User</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing User</fullName>
    </customValue>
    <customValue>
        <fullName>Apex Mobile User</fullName>
    </customValue>
    <customValue>
        <fullName>Offline User</fullName>
    </customValue>
    <customValue>
        <fullName>Knowledge User</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce CRM Content User</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Meetings</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Chatter External</fullName>
    </customValue>
    <customValue>
        <fullName>Chatter Free</fullName>
    </customValue>
    <customValue>
        <fullName>Guest License</fullName>
    </customValue>
    <description>Name of licenses under license type</description>
    <masterLabel>Available Licenses Name</masterLabel>
</GlobalValueSet>

globalValueSets/License_Catagories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>User Licenses</fullName>
    </customValue>
    <customValue>
        <fullName>Permission Set Licenses</fullName>
    </customValue>
    <customValue>
        <fullName>Feature Licenses</fullName>
        <isActive>false</isActive>
        <label>Feature Licenses</label>
    </customValue>
    <description>Categories of License</description>
    <masterLabel>License Catagories</masterLabel>
</GlobalValueSet>

globalValueSets/Procuring_Business.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>S&amp;C Safety</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;C Shelter</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;C Water</fullName>
    </customValue>
    <customValue>
        <fullName>E&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>T&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Non Core</fullName>
    </customValue>
    <description>List of all the Businesses</description>
    <masterLabel>Procuring Business</masterLabel>
</GlobalValueSet>

classes/ctrlUpdateLicensesOnUserChange_UT.cls
/*******************************************************************************
Copyright © 2021 DuPont. All rights reserved. 
Author: Abhinav Bhatnagar
Email: abhinav.bhatnagar@dupont.com
Description:  This test class to test functionality of updating the licenses consumed for license object record when user record is updated. This class test, trigUser, UserHandler, batchUpdateLicenseOnUserChanges & ctrlUpdateLicensesOnUserChange

//<AB03182021> Resolved batch execution issue
********************************************************************************/
@isTest
public class ctrlUpdateLicensesOnUserChange_UT {//Test Class to verify the test conditions and coverage
    public static testMethod void LoadData() { //Entry Method
        Licenses__c[] licensesRecords = createLicensesRecords(); //Method to create Test Licenses
        createLicenseProcurement(licensesRecords); //Method to create and link Test License procurement record to Licenses
        
        createUpdateUserRecord(); //Create and update User record to test trigger for User, User Handler and controller
        
    }
    
    //Method to create Test Licenses
    private static Licenses__c[] createLicensesRecords(){
        Licenses__c[] licensesRecords = new Licenses__c[]{};

		//Test Licenses, this procuring business and license name will be different for each org like E&I, T&I, S&C Water, S&C Shelter, S&C Safety. This is dependent of type of license procured by business and global picklist enabled values in org         
        Licenses__c licensesRecord1 = new Licenses__c(Available_Licenses_Name__c='Service Cloud',License_Catagories__c='User Licenses',Name='S&C Water UL Service Cloud Licenses Jan 2021',Procuring_Business__c='S&C Water',Threshold_Email_Notifications__c='test@test.com.invalid',Threshold_Limit__c=1);
        Licenses__c licensesRecord2 = new Licenses__c(Available_Licenses_Name__c='CRM User',License_Catagories__c='Permission Set Licenses',Name='S&C Safety PSL CRM User Licenses Jan 2021',Procuring_Business__c='S&C Safety',Threshold_Email_Notifications__c='test@test.com.invalid',Threshold_Limit__c=4);
        Licenses__c licensesRecord3 = new Licenses__c(Available_Licenses_Name__c='CRM User',License_Catagories__c='Permission Set Licenses',Name='S&C Shelter PSL CRM User Licenses Jan 2021',Procuring_Business__c='S&C Shelter',Threshold_Email_Notifications__c='test@test.com.invalid',Threshold_Limit__c=4);
        Licenses__c licensesRecord4 = new Licenses__c(Available_Licenses_Name__c='Service Cloud',License_Catagories__c='User Licenses',Name='S&C Safety UL Service Cloud Licenses Jan 2021',Procuring_Business__c='S&C Safety',Threshold_Email_Notifications__c='test@test.com.invalid',Threshold_Limit__c=4);
        Licenses__c licensesRecord5 = new Licenses__c(Available_Licenses_Name__c='CRM User',License_Catagories__c='Permission Set Licenses',Name='S&C Water PSL CRM User Licenses Jan 2021',Procuring_Business__c='S&C Water',Threshold_Email_Notifications__c='test@test.com.invalid',Threshold_Limit__c=4);
        
        
        
        licensesRecords.add(licensesRecord1);
        licensesRecords.add(licensesRecord2);
        licensesRecords.add(licensesRecord3);
        licensesRecords.add(licensesRecord4);
        licensesRecords.add(licensesRecord5);
        
        insert licensesRecords;
        
        return licensesRecords;
    }
    
    //Method to create and link Test License procurement record to Licenses
    private static void createLicenseProcurement(Licenses__c[] licensesRecords){
        License_Procurement__c[] licensesProcurementRecords = new License_Procurement__c[]{};
        
        //Test License Procurement record, procurement name and Available License will be different for each org like E&I, T&I, S&C Water, S&C Shelter, S&C Safety. This is dependent of type of license procured by business and global picklist enabled values in org         
		License_Procurement__c licensesProcurementRecord1 = new License_Procurement__c(Available_Licenses_Name__c='Service Cloud',License_Catagories__c='User Licenses',Name='S&C Water UL Service Cloud Licenses Jan 2021',Procuring_Business__c='S&C Water',Licenses__c=licensesRecords[0].id,Number_of_licenses_procured__c=1,Status__c='Active',Procurement_Date__c=system.today(),License_Expiry_Date__c=system.today());
        License_Procurement__c licensesProcurementRecord2 = new License_Procurement__c(Available_Licenses_Name__c='CRM User',License_Catagories__c='Permission Set Licenses',Name='S&C Safety PSL CRM User Licenses Jan 2021',Procuring_Business__c='S&C Safety',Licenses__c=licensesRecords[1].id,Number_of_licenses_procured__c=5,Status__c='Active',Procurement_Date__c=system.today(),License_Expiry_Date__c=system.today());
        License_Procurement__c licensesProcurementRecord3 = new License_Procurement__c(Available_Licenses_Name__c='CRM User',License_Catagories__c='Permission Set Licenses',Name='S&C Shelter PSL CRM User Licenses Jan 2021',Procuring_Business__c='S&C Shelter',Licenses__c=licensesRecords[2].id,Number_of_licenses_procured__c=5,Status__c='Active',Procurement_Date__c=system.today(),License_Expiry_Date__c=system.today());
        License_Procurement__c licensesProcurementRecord4 = new License_Procurement__c(Available_Licenses_Name__c='Service Cloud',License_Catagories__c='User Licenses',Name='S&C Safety UL Service Cloud Licenses Jan 2021',Procuring_Business__c='S&C Safety',Licenses__c=licensesRecords[3].id,Number_of_licenses_procured__c=5,Status__c='Active',Procurement_Date__c=system.today(),License_Expiry_Date__c=system.today());
        License_Procurement__c licensesProcurementRecord5 = new License_Procurement__c(Available_Licenses_Name__c='CRM User',License_Catagories__c='Permission Set Licenses',Name='S&C Water PSL CRM User Licenses Jan 2021',Procuring_Business__c='S&C Water',Licenses__c=licensesRecords[4].id,Number_of_licenses_procured__c=5,Status__c='Active',Procurement_Date__c=system.today(),License_Expiry_Date__c=system.today());
        
        
        licensesProcurementRecords.add(licensesProcurementRecord1);
        licensesProcurementRecords.add(licensesProcurementRecord2);
        licensesProcurementRecords.add(licensesProcurementRecord3);
        licensesProcurementRecords.add(licensesProcurementRecord4);
        licensesProcurementRecords.add(licensesProcurementRecord5);
        
        insert licensesProcurementRecords;
        
    }
    
    //Method to Create and Udpate User Record for License Testing
    private static void createUpdateUserRecord(){
        Test.startTest();
        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()]; //Run the test from current user context
        
        system.runAs(thisUser){
            User userRecord = new User(FirstName = 'Test', Procuring_Business__c = 'S&C Safety', LastName = 'Test User 20211', ProfileId = getProfileId('Standard User'), Alias = 'Test0001', Email = 'testEmail1@salesforce.com.invalid', Username = 'testUserName1@salesforce.com.invalid.devab1', CommunityNickname = 'TestUser1', IsActive = TRUE, EmailEncodingKey = 'UTF-8',  User_Country__c = 'UNITED STATES', User_Region__c = 'Asia Pacific', User_Owning_Org__c = 'M&S-IT', UserOwningSBUOrg__c = 'Corporate', Approving_Business__c = 'Corporate - IT-PA',  TimeZoneSidKey = 'America/New_York', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', CurrencyIsoCode = 'USD', DefaultCurrencyIsoCode = 'USD', ReceivesAdminInfoEmails = FALSE, ReceivesInfoEmails = FALSE);
            insert userRecord;
            
            PermissionSetLicense pslRecord = [Select id from PermissionSetLicense where DeveloperName='CRMUserPsl'];            
            PermissionSetLicenseAssign pslaRecord = new PermissionSetLicenseAssign(AssigneeId=userRecord.id,PermissionSetLicenseId=pslRecord.id);
            insert pslaRecord;
            
            pslRecord = [Select id from PermissionSetLicense where DeveloperName='SalesConsoleUser'];
            pslaRecord = new PermissionSetLicenseAssign(AssigneeId=userRecord.id,PermissionSetLicenseId=pslRecord.id);
            insert pslaRecord;
            
            userRecord.Procuring_Business__c = 'S&C Water';
            update userRecord;
            userRecord.IsActive = FALSE;
            update userRecord;
            
            User userRecord1 = new User(FirstName = 'Test1', Procuring_Business__c = 'S&C Safety', LastName = 'Test User 20212', ProfileId = getProfileId('Standard User'), Alias = 'Test0002', Email = 'testEmail2@salesforce.com.invalid', Username = 'testUserName2@salesforce.com.invalid.devab1', CommunityNickname = 'TestUser2', IsActive = TRUE, EmailEncodingKey = 'UTF-8',  User_Country__c = 'UNITED STATES', User_Region__c = 'Asia Pacific', User_Owning_Org__c = 'S&C', UserOwningSBUOrg__c = 'Corporate', Approving_Business__c = 'Corporate - IT-PA',  TimeZoneSidKey = 'America/New_York', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', CurrencyIsoCode = 'USD', DefaultCurrencyIsoCode = 'USD', ReceivesAdminInfoEmails = FALSE, ReceivesInfoEmails = FALSE);
            insert userRecord1;
            userRecord1.IsActive = FALSE;
            userRecord1.Procuring_Business__c = 'S&C Shelter';
            update userRecord1;
            
            User userRecord2 = new User(FirstName = 'Test2', Procuring_Business__c = 'S&C Safety', LastName = 'Test User 20213', ProfileId = getProfileId('Standard User'), Alias = 'Test0003', Email = 'testEmail3@salesforce.com.invalid', Username = 'testUserName3@salesforce.com.invalid.devab1', CommunityNickname = 'TestUser3', IsActive = TRUE, EmailEncodingKey = 'UTF-8',  User_Country__c = 'UNITED STATES',  User_Region__c = 'Asia Pacific', User_Owning_Org__c = 'S&C', UserOwningSBUOrg__c = 'Corporate', Approving_Business__c = 'Corporate - IT-PA',  TimeZoneSidKey = 'America/New_York', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', CurrencyIsoCode = 'USD', DefaultCurrencyIsoCode = 'USD', ReceivesAdminInfoEmails = FALSE, ReceivesInfoEmails = FALSE);
            insert userRecord2;
            pslaRecord = new PermissionSetLicenseAssign(AssigneeId=userRecord2.id,PermissionSetLicenseId=pslRecord.id);
            insert pslaRecord;
            userRecord2.Procuring_Business__c = 'S&C Shelter';
            update userRecord2;
            userRecord2.IsActive = FALSE;
            update userRecord2;
            userRecord2.IsActive = TRUE;
            update userRecord2;            
            
            User userRecord3 = new User(FirstName = 'Test3', Procuring_Business__c = 'S&C Water', LastName = 'Test User 20213', ProfileId = getProfileId('Standard User'), Alias = 'Test0004', Email = 'testEmail4@salesforce.com.invalid', Username = 'testUserName4@salesforce.com.invalid.devab1', CommunityNickname = 'TestUser4', IsActive = TRUE, EmailEncodingKey = 'UTF-8',  User_Country__c = 'UNITED STATES',  User_Region__c = 'Asia Pacific', User_Owning_Org__c = 'S&C', UserOwningSBUOrg__c = 'Corporate', Approving_Business__c = 'Corporate - IT-PA', TimeZoneSidKey = 'America/New_York', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', CurrencyIsoCode = 'USD', DefaultCurrencyIsoCode = 'USD', ReceivesAdminInfoEmails = FALSE, ReceivesInfoEmails = FALSE);
            insert userRecord3;
            userRecord.IsActive = TRUE;
            update userRecord;
            
            batchUpdateLicenseOnUserChanges obj = new batchUpdateLicenseOnUserChanges();
            DataBase.executeBatch(obj); 
            Test.stopTest(); //<AB03182021>
            Licenses__c[] licensesUpdatedRecords = [Select Available_Licenses_Name__c,CreatedById,CreatedDate,fRemaining_Licenses__c,Id,IsDeleted,Licenses_Consumed__c,License_Catagories__c,License_Number__c,Name,Number_of_licenses_procured__c,OwnerId,Procuring_Business__c,SystemModstamp,Threshold_Email_Notifications__c,Threshold_Limit__c FROM Licenses__c ORDER BY Id DESC NULLS LAST limit 1];
            for(Licenses__c licensesRecord:licensesUpdatedRecords){
                if(licensesRecord.Procuring_Business__c=='S&C Water' && licensesRecord.Available_Licenses_Name__c=='Service Cloud'){
                    System.assertEquals(0, licensesRecord.fRemaining_Licenses__c);// No Licenses should remain from total 2 procured licenses as both are assigned to userRecord and userRecord3 as both are active
                }else if(licensesRecord.Procuring_Business__c=='S&C Safety' && licensesRecord.Available_Licenses_Name__c=='Service Cloud'){
                    System.assertEquals(5, licensesRecord.fRemaining_Licenses__c); // All 5 licenses are free as earlier assigned procuring business is changed
                }else if(licensesRecord.Procuring_Business__c=='S&C Shelter' && licensesRecord.Available_Licenses_Name__c=='Service Cloud'){
                    System.assertEquals(4, licensesRecord.fRemaining_Licenses__c); //Only 1 license is assigned to UserRecord2
                }
            }
            
            
            String scheduledOn = '0 0 2 * * ?';
            system.schedule('Test License Schedule', scheduledOn, new schedUpdateLicenseOnUserChanges()); 
        }
    }
    
    //Method to fetch profile Id based on name
    private static Id getProfileId(string profileName){
        return [Select id from Profile where name =: profileName LIMIT 1].Id;
    }
    
}