objects/Licenses__c.object
<CustomObject>
    <description>License custom object to capture business unit and number of licenses procured. Store threshold limit and alert notification email list here.</description>
    <fields>
        <fullName>Available_Licenses_Name__c</fullName>
        <description>Name of the Licenses Available under License Category</description>
        <inlineHelpText>Name of the Licenses Available under License Category</inlineHelpText>
        <label>Available Licenses Name</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <controllingField>License_Catagories__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>Available_Licenses_Name</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Catagories__c</fullName>
        <description>Catagories of License Type</description>
        <inlineHelpText>Catagories of License Type</inlineHelpText>
        <label>License Catagories</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>License_Catagories</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>License_Number__c</fullName>
        <description>Auto Number Generated which is unique to each license with year and month, record is created</description>
        <displayFormat>LN#{YYYY}-{MM}-{000000}</displayFormat>
        <inlineHelpText>Unique Identifier generated for each license with year and month, given when record is created.</inlineHelpText>
        <label>License Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Licenses_Consumed__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of Licenses consumed</description>
        <inlineHelpText>Number of Licenses consumed</inlineHelpText>
        <label>Licenses Consumed</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_licenses_procured__c</fullName>
        <description>rollup summary of all License Procurements related records with status = active and business = Procuring Business.</description>
        <inlineHelpText>rollup summary of all License Procurements related records with status = active and business = Procuring Business.</inlineHelpText>
        <label>Number of licenses procured</label>
        <summarizedField>License_Procurement__c.Number_of_licenses_procured__c</summarizedField>
        <summaryFilterItems>
            <field>License_Procurement__c.Status__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </summaryFilterItems>
        <summaryForeignKey>License_Procurement__c.Licenses__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Procuring_Business__c</fullName>
        <description>Business procuring the license.</description>
        <inlineHelpText>Business procuring the license.</inlineHelpText>
        <label>Procuring Business</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Procuring_Business</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Threshold_Email_Notifications__c</fullName>
        <description>List of email addresses to send mail, when the threshold limit is reached.</description>
        <inlineHelpText>List of email addresses to send mail, when the threshold limit is reached.</inlineHelpText>
        <label>Threshold Email Notification List</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Threshold_Limit__c</fullName>
        <description>Limit to monitor the licenses</description>
        <inlineHelpText>Limit when reached, will send mail to admins.</inlineHelpText>
        <label>Threshold Limit</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>fRemaining_Licenses__c</fullName>
        <description>Formula to calculate the remaining license available for allotment.</description>
        <formula>FLOOR(Number_of_licenses_procured__c - Licenses_Consumed__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Remaining license(s) available for allotment.</inlineHelpText>
        <label>Remaining Licenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>Licenses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Licenses_Tracked_For_mailing__mdt.object
<CustomObject>
    <description>List of Licenses to be tracked which will later be mailed to functionality admins or record owners</description>
    <fields>
        <fullName>License_Catagories__c</fullName>
        <description>Type of license</description>
        <inlineHelpText>Suggested Values : UL/PSL/FL
UL: User License
PSL: Permission Set License
FL: Feature License</inlineHelpText>
        <label>License Catagories</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>UL</fullName>
                    <default>true</default>
                    <label>UL</label>
                </value>
                <value>
                    <fullName>PSL</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Licenses Tracked</label>
    <pluralLabel>Licenses Tracked</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Procuring_Business__c</fullName>
        <description>Name of Business Procuring the License for the user</description>
        <inlineHelpText>Business sponsored the license</inlineHelpText>
        <label>Procuring Business</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Procuring_Business</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

globalValueSets/Available_Licenses_Name.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Partner Community</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Community</fullName>
    </customValue>
    <customValue>
        <fullName>Customer Community Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Analytics Plus</fullName>
    </customValue>
    <customValue>
        <fullName>Sales User</fullName>
    </customValue>
    <customValue>
        <fullName>Company Community for Force.com</fullName>
    </customValue>
    <customValue>
        <fullName>Lightning Console</fullName>
    </customValue>
    <customValue>
        <fullName>Standard Einstein Activity Capture User</fullName>
    </customValue>
    <customValue>
        <fullName>B2B Commerce</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Console User</fullName>
    </customValue>
    <customValue>
        <fullName>CRM User</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Agent</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Search</fullName>
    </customValue>
    <customValue>
        <fullName>Einstein Next Best Action - Unlimited Requests</fullName>
    </customValue>
    <customValue>
        <fullName>Trust Card Manager</fullName>
    </customValue>
    <customValue>
        <fullName>Chatter Answers User</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud User</fullName>
    </customValue>
    <customValue>
        <fullName>Chat User</fullName>
    </customValue>
    <customValue>
        <fullName>Flow User</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing User</fullName>
    </customValue>
    <customValue>
        <fullName>Apex Mobile User</fullName>
    </customValue>
    <customValue>
        <fullName>Offline User</fullName>
    </customValue>
    <customValue>
        <fullName>Knowledge User</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce CRM Content User</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Meetings</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce Platform</fullName>
    </customValue>
    <customValue>
        <fullName>Chatter External</fullName>
    </customValue>
    <customValue>
        <fullName>Chatter Free</fullName>
    </customValue>
    <customValue>
        <fullName>Guest License</fullName>
    </customValue>
    <description>Name of licenses under license type</description>
    <masterLabel>Available Licenses Name</masterLabel>
</GlobalValueSet>

globalValueSets/License_Catagories.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>User Licenses</fullName>
    </customValue>
    <customValue>
        <fullName>Permission Set Licenses</fullName>
    </customValue>
    <customValue>
        <fullName>Feature Licenses</fullName>
        <isActive>false</isActive>
        <label>Feature Licenses</label>
    </customValue>
    <description>Categories of License</description>
    <masterLabel>License Catagories</masterLabel>
</GlobalValueSet>

globalValueSets/Procuring_Business.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>S&amp;C Safety</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;C Shelter</fullName>
    </customValue>
    <customValue>
        <fullName>S&amp;C Water</fullName>
    </customValue>
    <customValue>
        <fullName>E&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>T&amp;I</fullName>
    </customValue>
    <customValue>
        <fullName>Non Core</fullName>
    </customValue>
    <description>List of all the Businesses</description>
    <masterLabel>Procuring Business</masterLabel>
</GlobalValueSet>

classes/batchUpdateLicenseOnUserChanges.cls
/******************************************************************************* 
Copyright © 2021 DuPont. All rights reserved. 
Author: Abhinav Bhatnagar
Email: abhinav.bhatnagar@dupont.com
Description:  Batch Class for updating License Records based on user changes

Change Log
//AB<20210305> - To not send mail to original list if the org is not production or if it is test run.
//AB<20210305>1 - To not send mail when no records are found. Don't send empty mail.
//AB<20210305>2 - To attach Org Name in Mail Subject
//AB<20210408>  - Updated to track only the Licenses tracked via Custom Metadata Type
********************************************************************************/

global class batchUpdateLicenseOnUserChanges implements Database.Batchable<sObject>,Database.Stateful  {
    private static final integer MAXROWS = Limits.getLimitQueryRows(); //Governor limit to limit query from fetching allowed number of rows
    public Map<string,integer> mapLicenseCount; //Map to maintain procuring business, license type and associated licenses consumed
    public Map<string,integer> mapUnAssignedUsersCount; //Map to maintain procuring business, license type and associated licenses consumed which are not assigned to licenses record
    public static String[] adminEmailAddresses = Label.License_Tracking_Admin_Email_List.split(',');//Custom Label providing functionality admin list when licenses are not found or not available. 
    public static String strFrom = 'License Manager (Salesforce)'; //Name from which the mails will be send to functionality admins or threshold email list.
    public static boolean isProductionOrg = false;//AB<20210305>
    public static boolean isRunningTest = false;//AB<20210305>
    public static String[] testMailArray= new String[]{'test@SpecPA.test','test123@specpa.test','abhinav.bhatnagar@dupont.com'};//AB<20210305>
   
    //Default constructor to initialize the maps
    public batchUpdateLicenseOnUserChanges(){
        mapLicenseCount = new Map<string, integer>();
        mapUnAssignedUsersCount = new Map<string, integer>();        
    }
    
    //Entry method of batch
    global Database.QueryLocator start(Database.BatchableContext bc) {
        try{ 
            isProductionOrg = isProduction();//AB<20210305>
            isRunningTest = Test.isRunningTest();//AB<20210305>
            
            if(!Test.isRunningTest()){ //Fetch all users with procuring business available (Active status is not considered because the we have to unassign the licenses from the users deactivated)         
                return Database.getQueryLocator([SELECT FirstName,Id,IsActive,LastName,Name,ProfileId,Profile.UserLicense.Name,Username,UserType,Procuring_Business__c FROM User where isActive=true AND Procuring_Business__c!='' LIMIT :MAXROWS]);        
            }else{ //Fetch all test users with limited number
                return Database.getQueryLocator([SELECT FirstName,Id,IsActive,LastName,Name,ProfileId,Profile.UserLicense.Name,Username,UserType,Procuring_Business__c FROM User where isActive=true AND Procuring_Business__c!='' LIMIT 50]);        
            }
        }catch(Exception e){
            system.debug(e.getStackTraceString());
            return null;
        }
    }
    
    //Method to calculate the licenses for each user fetched in start method
    global void execute(Database.BatchableContext bc, List<User> userRecords) {
        try{
            calculateLicensesCount(userRecords);
        }catch(Exception e){
            system.debug(e.getStackTraceString());            
        }
    }
    
    //Exist method of batch
    global void finish(Database.BatchableContext bc) {
        try{
            updateLicenses();//Method to update licenses when licenses are calculated
            if(mapUnAssignedUsersCount.size()>0){ //if batch is not able to assign users to licenses
                sendRecordNotFoundMail(); //Send mail to functionality admins
            }                   
        }catch(Exception e){
            system.debug(e.getStackTraceString());            
        }
    }
    
    //Method to update licenses once calculated
    private void updateLicenses(){
        Licenses__c [] licensesToUpdate = new Licenses__c[]{};
            
            for(string licenseProcuringBusinessKey: mapLicenseCount.keySet()){//For each License in Map
                string licenseName =  licenseProcuringBusinessKey.split(':::')[0]; //Get current license name
                string procuringBusiness =  licenseProcuringBusinessKey.split(':::')[1]; //Get current procuring business
                //Fetch license record for current license name and current procuring business
                Licenses__c[] licenseRecords = [select id,Licenses_Consumed__c,Number_of_licenses_procured__c from Licenses__c where Available_Licenses_Name__c=:licenseName AND Procuring_Business__c=:procuringBusiness ORDER BY CreatedDate DESC LIMIT 1];
                if(licenseRecords!=null && licenseRecords.size()>0){ //If licenses found
                    if(licenseRecords[0].Number_of_licenses_procured__c>=mapLicenseCount.get(licenseProcuringBusinessKey)){ // And licenses available is greater than licenses required
                        licenseRecords[0].Licenses_Consumed__c = mapLicenseCount.get(licenseProcuringBusinessKey); //Assign required licenses to consumed licenses
                        licensesToUpdate.add(licenseRecords[0]); 
                    }else{ //Required licenses are greater than licenses available
                        licenseRecords[0].Licenses_Consumed__c = licenseRecords[0].Number_of_licenses_procured__c; //Assign maximum available to licenses consumed
                        licensesToUpdate.add(licenseRecords[0]);
                        mapUnAssignedUsersCount.put(licenseProcuringBusinessKey,(mapLicenseCount.get(licenseProcuringBusinessKey)-licenseRecords[0].Number_of_licenses_procured__c).intValue()); //For remaining unassigned licenses add to unassigned map
                    }
                }else{
                    mapUnAssignedUsersCount.put(licenseProcuringBusinessKey,mapLicenseCount.get(licenseProcuringBusinessKey)); //If licenses are not found altogether then put all required licenses to unassigned map
                }
            }
        
        if(Schema.sObjectType.Licenses__c.isUpdateable()){ //If licenses are udpatable then update the licenses
            update licensesToUpdate;
        }
        
        sendConsolidatedMail(); //Send Consolidated Report in Mail
    }
    
    //Method to calculate licenses consumed
    private void calculateLicensesCount(List<User> userRecords){
        For(User userRecord: userRecords){//For each user record 
            string userLicense = (userRecord.Profile.UserLicense.Name=='Salesforce')?'Service Cloud':userRecord.Profile.UserLicense.Name; //Fetch user license
            string userProcuringBusiness = userRecord.Procuring_Business__c;
            string[] userLicenseAssignments = getUserLicenseAssignments(userRecord.Id);//Fetch permission set license assignments
            
            updateLicenseMap(userLicense+':::'+userProcuringBusiness+':::User License', mapLicenseCount); //Store in license map
            
            For(string userLicenseAssignment:userLicenseAssignments){// For every permission set license assignments
                updateLicenseMap(userLicenseAssignment+':::'+userProcuringBusiness+':::Permission Set License', mapLicenseCount); //Store in license map
            }            
        }
    }
    
    //Method to store and update the licenses consumend for both user licenses and permission set licenses
    private void updateLicenseMap(string licenseKey, Map<string,integer> mapLicenseCountValue){
        if(!mapLicenseCountValue.containsKey(licenseKey)){ //If key/ license and procuring business pair is not in map
            mapLicenseCountValue.put(licenseKey, 1); //create the key and license consumed to 1
        }else{                
            mapLicenseCountValue.put(licenseKey,mapLicenseCountValue.get(licenseKey)+ 1); // Increment the license consumed by 1
        }
    }
    
    //Method to fetch all name of permission set licenses for user in string array
    private string[] getUserLicenseAssignments(string userId){
        PermissionSetLicenseAssign [] pslaRecords = [SELECT AssigneeId,PermissionSetLicenseId,PermissionSetLicense.MasterLabel FROM PermissionSetLicenseAssign WHERE AssigneeId =: userId ];
        
        string []pslaRecordsName = new string[]{};
            for(PermissionSetLicenseAssign pslaRecord: pslaRecords){//For each record
                pslaRecordsName.add(pslaRecord.PermissionSetLicense.MasterLabel); //Fetch Permission Set License Name and add to String Array
            }
        return pslaRecordsName;        
    }
    
    //Method to send Mail to Functionality Admins if License record not found
    private void sendRecordNotFoundMail(){
        try{
            if(mapUnAssignedUsersCount.size()<=0){
                return;
            }//AB<20210305>1
            
            //<AB20210408> Start
            boolean isMailEmpty = True;
            Licenses_Tracked_For_mailing__mdt [] licensesTracked = [SELECT MasterLabel,License_Catagories__c FROM Licenses_Tracked_For_mailing__mdt];
            
            String[] strLicensesNamesLst = new String[] {};
                for(Licenses_Tracked_For_mailing__mdt licenseTracked: licensesTracked){
                    strLicensesNamesLst.add(licenseTracked.MasterLabel);
                }
            //<AB20210408> End////// 
            
            string recordNotFoundDetails ='<table style="border:1px solid black;text-align:center" cellspacing="1" cellpadding="1"><tr style="border:0px solid black;text-align:center"><th style="border:0px solid black;text-align:center">Sr.No.</th><th style="border:0px solid black;text-align:center">License Name</th><th style="border:0px solid black;text-align:center">Business</th><th style="border:0px solid black;text-align:center">Type</th><th style="border:0px solid black;text-align:center"># Unassignable Licenses</th></tr>';
            integer srno = 1;
            for(string keyValue:mapUnAssignedUsersCount.keySet()){
                string licName = keyValue.split(':::')[0];
                string procBusiness = keyValue.split(':::')[1];
                string licType = keyValue.split(':::')[2];
                //<AB20210408> Start
                if(strLicensesNamesLst.contains(licName)){
                    recordNotFoundDetails += '<tr>'+'<td><b>'+srno+'</b></td>'+'<td>'+licName+'</td>'+'<td>'+procBusiness+'</td>'+'<td>'+licType+'</td>'+'<td>'+mapUnAssignedUsersCount.get(keyValue)+'</td>'+'</tr>';
                    srno+=1;
                    isMailEmpty = False;
                }
            }
            
            If(isMailEmpty){
                return;
            }
            //<AB20210408> End//////
            
            recordNotFoundDetails+='</table>';
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            isProductionOrg = isProduction();//AB<20210305>
        	isRunningTest = Test.isRunningTest();//AB<20210305>
            mail.setToAddresses((isProductionOrg && !isRunningTest)?adminEmailAddresses:testMailArray);//AB<20210305>
            mail.setSenderDisplayName(strFrom);
            mail.setSubject('Batch License Summary PA Org: Not Able to Assign Licenses'); //AB<20210305>2
            mail.setHtmlBody('Hi Admin(s),<br><br>While executing the batch, we are not able to find licenses for following -'+recordNotFoundDetails+'<br> Regards,<br>License Manager Salesforce');            
            
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }catch(Exception e){
            System.debug(LoggingLevel.ERROR, e.getStackTraceString());
        }
    }
    
    //Send final consolidated mail of threshold to funtionality admins
    private void sendConsolidatedMail(){
        
        boolean canSendMail = False;
        boolean isRecordEmpty = True;//AB<20210305>1

        try {
                Messaging.reserveSingleEmailCapacity(1);
                Messaging.reserveMassEmailCapacity(1);
                canSendMail = True;
            } catch (System.NoAccessException e) {
                System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            }
        
        if(canSendMail){
                try{
                
                Licenses__c[] licensesThresholdLimitReached = [Select Available_Licenses_Name__c,CreatedById,CreatedDate,fRemaining_Licenses__c,Id,IsDeleted,Licenses_Consumed__c,License_Catagories__c,License_Number__c,Name,Number_of_licenses_procured__c,OwnerId,Procuring_Business__c,SystemModstamp,Threshold_Email_Notifications__c,Threshold_Limit__c FROM Licenses__c ORDER BY Id DESC NULLS LAST];
                    if(licensesThresholdLimitReached.size()<=0){
                        return;
                    }//AB<20210305>1
                    
                string recordTable = '<table style="border:1px solid black;text-align:center" cellspacing="1" cellpadding="1"><tr><th>Sr.No.</th><th>Id</th><th>Name</th><th>Business</th><th>License Type</th><th>License Name</th><th>Total Licenses</th><th># Consumed</th><th># Remaining</th><th>Threshold</th></tr>';
                integer srno = 1;
                
                //<AB20210408> Start
                
                Licenses_Tracked_For_mailing__mdt [] licensesTracked = [SELECT MasterLabel,License_Catagories__c FROM Licenses_Tracked_For_mailing__mdt];
                
                String[] strLicensesNamesLst = new String[] {};
                    for(Licenses_Tracked_For_mailing__mdt licenseTracked: licensesTracked){
                        strLicensesNamesLst.add(licenseTracked.MasterLabel);
                    }
                //<AB20210408> End////// 
                
                
                For(Licenses__c licenseRecord : licensesThresholdLimitReached){
                    if(licenseRecord.fRemaining_Licenses__c <= licenseRecord.Threshold_Limit__c && strLicensesNamesLst.contains(licenseRecord.Available_Licenses_Name__c)){//<AB20210408>
                        recordTable +='<tr>'+'<td><b>'+srno+'</b></td>'+'<td>'+licenseRecord.id+'</td>'+'<td>'+licenseRecord.Name+'</td>'+'<td>'+licenseRecord.Procuring_Business__c+'</td>'+'<td>'+licenseRecord.License_Catagories__c+'</td>'+'<td>'+licenseRecord.Available_Licenses_Name__c+'</td>'+'<td>'+licenseRecord.Number_of_licenses_procured__c+'</td>'+'<td>'+licenseRecord.Licenses_Consumed__c+'</td>'+'<td>'+licenseRecord.fRemaining_Licenses__c+'</td>'+'<td>'+licenseRecord.Threshold_Limit__c+'</td>'+'</tr>';
                        srno+=1;
                        isRecordEmpty = false;//AB<20210305>1

                    }
                }
                recordTable+='</table>';
                if(isRecordEmpty){//AB<20210305>1
                     return;//AB<20210305>1
                }//AB<20210305>1
                Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                isProductionOrg = isProduction();//AB<20210305>
        		isRunningTest = Test.isRunningTest();//AB<20210305>
                mail.setToAddresses((isProductionOrg && !isRunningTest)?adminEmailAddresses:testMailArray);//AB<20210305>
                mail.setSenderDisplayName(strFrom);
                mail.setSubject('Batch License Summary PA Org: Licenses On/Below Threshold Limit'); //AB<20210305>2
                mail.setHtmlBody('Hi Admin(s),<br>While executing batch, we found out that following licenses are consumed are on or more than threshold limit. Here is the consolidated list.<br>'+recordTable+'<br> Regards,<br>License Manager Salesforce');            
                
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }catch(Exception e){
                System.debug(LoggingLevel.ERROR, e.getStackTraceString());
            }        
        }
    }
    
     /// Is Current instance production?//AB<20210305>
    public static boolean isProduction() {        
        Organization currOrg = [select id, name, isSandbox, instanceName from Organization limit 1];
        boolean isProd = false;
        if (currOrg != null && currOrg.isSandbox != null) 
            isProd = !currOrg.isSandbox;
        return isProd;
    }
}