objects/Material__c.object
<CustomObject>
    <fields>
        <fullName>Per__c</fullName>
        <label>Per</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price_list_type__c</fullName>
        <label>Price list type</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <description>Name of the concatenation of the 9 Product Hierarchy Levels, does not exist in SAP</description>
        <label>Product Hierarchy</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_to__c</fullName>
        <label>Valid to</label>
        <type>Date</type>
    </fields>
    <label>Material</label>
    <nameField>
        <label>Material Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Sales_Prices__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <label>Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division__c</fullName>
        <label>Division</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Use_Code__c</fullName>
        <label>End Use Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Use__c</fullName>
        <label>End Use</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms1__c</fullName>
        <label>Incoterms1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Incoterms_1_Code__c</fullName>
        <label>Incoterms 1 Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KC_SAP__c</fullName>
        <label>KC_SAP</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination_Code__c</fullName>
        <externalId>true</externalId>
        <label>Key Combination Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Code__c</fullName>
        <label>Material Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Price_Group_Code__c</fullName>
        <label>Material Price Group Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Price_Group__c</fullName>
        <label>Material Price Group</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material__c</fullName>
        <label>Material</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PCKC_SAP__c</fullName>
        <formula>KC_SAP__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PCKC SAP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH1_Code__c</fullName>
        <label>PH1 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH2_Code__c</fullName>
        <label>PH2 Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH3_Code__c</fullName>
        <label>PH3 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH4_Code__c</fullName>
        <label>PH4 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH5_Code__c</fullName>
        <label>PH5 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH6_Code__c</fullName>
        <label>PH6 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH7_Code__c</fullName>
        <label>PH7 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH8_Code__c</fullName>
        <label>PH8 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PH9_Code__c</fullName>
        <label>PH9 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Per__c</fullName>
        <label>Per</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Plus_Minus_Code__c</fullName>
        <label>Plus/Minus Code</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>X</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plus_Minus__c</fullName>
        <label>Plus/Minus</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Plus_Minus_Code__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Positive</fullName>
                </value>
                <value>
                    <fullName>Negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_Holder__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Holder</label>
        <referenceTo>Sales_Prices__c</referenceTo>
        <relationshipLabel>Sales Prices - Non SAP</relationshipLabel>
        <relationshipName>Sales_Prices_Non_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price_List_Type_Code__c</fullName>
        <label>Price List Type Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_List_Type__c</fullName>
        <label>Price List Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Condition_Code__c</fullName>
        <externalId>true</externalId>
        <label>Pricing Condition Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Condition__c</fullName>
        <label>Pricing Condition</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy_Code__c</fullName>
        <formula>PH1_Code__c &amp; PH2_Code__c &amp; PH3_Code__c &amp; PH4_Code__c &amp; PH5_Code__c &amp; PH6_Code__c &amp; PH7_Code__c &amp; 
PH8_Code__c &amp; PH9_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Hierarchy Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Hierarchy__c</fullName>
        <label>Product Hierarchy</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profit_Center_Code__c</fullName>
        <label>Profit Center Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Profit_Center__c</fullName>
        <label>Profit Center</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rate__c</fullName>
        <label>Rate</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Application_Id__c</fullName>
        <label>SAP Application Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Client_ID__c</fullName>
        <label>SAP Client ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Cluster__c</fullName>
        <label>SAP Cluster</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office_Code__c</fullName>
        <label>Sales Office Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Office__c</fullName>
        <label>Sales Office</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org__c</fullName>
        <label>Sales Org.</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Price_Type__c</fullName>
        <label>Sales Price Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Floor</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Net Floor</fullName>
                </value>
                <value>
                    <fullName>Net Reference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Pricing_Procedure__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Pricing Procedure</label>
        <referenceTo>ERP_Pricing_Procedure__c</referenceTo>
        <relationshipLabel>Sales Prices - Non SAP</relationshipLabel>
        <relationshipName>Sales_Prices_Non_SAP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ShipTo_Code__c</fullName>
        <label>ShipTo Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ShipTo__c</fullName>
        <label>ShipTo</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country_Code__c</fullName>
        <label>Ship-To Country Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ship_To_Country__c</fullName>
        <label>Ship-To Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_SAP__c</fullName>
        <formula>IF( ISBLANK(Sold_To_Code__c) ,NULL, LPAD(&apos;0000000000&apos;,10 - LEN(Sold_To_Code__c),&apos;0&apos;))+Sold_To_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sold To-SAP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <label>Sold To</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_of_Payment_Code__c</fullName>
        <label>Terms of Payment Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UoM__c</fullName>
        <label>UoM</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isPriceHolder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPriceHolder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>markForDeletion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>markForDeletion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pckc__c</fullName>
        <formula>Pricing_Condition_Code__c &amp; Sales_Org_Code__c  &amp; Dist_Channel_Code__c &amp; Division_Code__c &amp;  Sold_To_Code__c &amp;  Material_Code__c &amp;  PH1_Code__c &amp; PH2_Code__c &amp; PH3_Code__c &amp; PH4_Code__c &amp; PH5_Code__c &amp; PH6_Code__c &amp; PH7_Code__c &amp; PH8_Code__c &amp; PH9_Code__c &amp;  ShipTo_Code__c  &amp;  Sales_Office_Code__c &amp;  Customer_Price_Group_Code__c &amp; Material_Price_Group_Code__c &amp; Price_List_Type_Code__c &amp; Terms_of_Payment_Code__c &amp; End_Use_Code__c &amp; Market_Segment_Code__c &amp; Variant_Code__c &amp;  Contract_Code__c  &amp; Sales_Order_Type_Code__c &amp; Country_Code__c &amp; Profit_Center_Code__c &amp; Incoterms_1_Code__c &amp;  Ship_To_Country_Code__c &amp; Kcode__c &amp; Material_Group_1_Code__c &amp; Sales_District_Code__c &amp; Partner_ZF_Code__c &amp; Payer_Code__c &amp; IF( CONTAINS( Key_Combination__c , &apos;Landing Cost&apos;), IF(Landing_Cost__c , &apos;true&apos;, &apos;false&apos;),&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>pckc</label>
        <type>Text</type>
    </fields>
    <label>Sales Prices - Non SAP</label>
    <nameField>
        <displayFormat>SPNSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Sales Prices - Non SAP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Prices - Non SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/batchClassForHolderNonSAP.cls
/*Ver1.1 Neeharika -Removed rate references */
/***********************************************Modification Log************************************************
  <VR20130509>
 Last Modified By   :   Vinoth Rajapandian
 Last Modified Date :   09 May 2013
 Description        :   Adding Logic for extra key field Customer Hierarchy - APAC ROLLOUT1(1.2)
 *****************************************************************************************************************/
global class batchClassForHolderNonSAP implements Database.Batchable<sObject>
{
	public List<Sales_Prices__c> upsertList = new  List<Sales_Prices__c>();
	public Map<String,Sales_Prices__c> mapOfpriAndHolder = new  Map<String,Sales_Prices__c> ();
	global database.queryLocator start(Database.BatchableContext BC)
	{
		//<VR20130509> Ver 1.2 VR 2013-05-09 APAC Rollout1-Adding Extra field Customer Hierarchy in query
		return Database.getQueryLocator([SELECT Ship_To_Country_Code__c, Ship_To_Country__c,ShipTo__c, ShipTo_Code__c, markForDeletion__c, isPriceHolder__c, Valid_To__c, Valid_From__c, UoM__c, Unit__c,
										Terms_of_Payment_Code__c, SystemModstamp, Sold_To__c, Sold_To_SAP__c, Sold_To_Code__c,
										Sales_Pricing_Procedure__c, Sales_Price_Type__c, Sales_Org__c,
										Sales_Org_Code__c, Sales_Office__c, Sales_Office_Code__c, SAP_Cluster__c, SAP_Client_ID__c, SAP_Application_Id__c,
										Rate__c, Profit_Center__c, Profit_Center_Code__c,
										Product_Hierarchy__c,Pricing_Condition__c, Pricing_Condition_Code__c,
										Price_List_Type__c, Price_List_Type_Code__c, Price_Holder__c,
										Plus_Minus__c, Plus_Minus_Code__c, Per__c,PH9_Code__c,PH8_Code__c, PH7_Code__c,
										PH6_Code__c, PH5_Code__c, PH4_Code__c, PH3_Code__c, PH2_Code__c,
										PH1_Code__c, PCKC__c, PCKC_SAP__c, OwnerId, Name, Material__c,Product_Hierarchy_Code__c,
										Material_Price_Group__c, Material_Price_Group_Code__c, Material_Code__c,
										LastModifiedDate, LastModifiedById, LastActivityDate, Key_Combination__c, Key_Combination_Code__c, KC_SAP__c,
										Incoterms_1_Code__c, Incoterms1__c, Id, End_Use__c, End_Use_Code__c, Division__c, Division_Code__c,
										Dist_Channel_Code__c, Dist_Channel__c, Customer_Specific__c, Customer_Price_Group__c,
										Customer_Price_Group_Code__c, CurrencyIsoCode, CreatedDate, CreatedById, Country__c, Country_Code__c,
										Condition_Class__c, Condition_Class_Code__c, Calculation_Type__c, Calculation_Type_Code__c, BU__c,
										Approved_Date__c,Scale_UoM_Scale_Unit__c,Scale_Quantity_Scale_Value1__c,Scale_Quantity_Scale_Value2__c,
										Scale_Quantity_Scale_Value3__c,Scale_Quantity_Scale_Value4__c,Scale_Quantity_Scale_Value5__c,Scale_Quantity_Scale_Value6__c,
										Scale_Quantity_Scale_Value7__c,Scale_Quantity_Scale_Value8__c,Scale_Quantity_Scale_Value9__c,Scale_Quantity_Scale_Value10__c,
										ScaleRate1__c,ScaleRate2__c,ScaleRate3__c,ScaleRate4__c,ScaleRate5__c,ScaleRate6__c,ScaleRate7__c,ScaleRate8__c,
										ScaleRate9__c,ScaleRate10__c,Check_Scale__c,Check_Scale_Code__c,Scale_Basis__c,Scale_Basis_Code__c,Scale_Type__c,Scale_Type_Code__c,
										ComPartner__c,	ComPartner_Code__c, Material_Group_5_Key__c,Material_Group_5_Key_Code__c,Char_Name__c, Kcode__c, Material_Group_1__c, Material_Group_1_Code__c, Sales_District__c, Sales_District_Code__c, 
										Partner_ZF__c, Partner_ZF_Code__c, Payer__c, Payer_Code__c, Disc_Ref_No__c, FixValDate__c,
										Campaign__c, Campaign_Code__c, Document_Currency__c, Document_Currency_Code__c, State__c, State_Code__c      
										 FROM Sales_Prices__c WHERE Price_Holder__c = null AND isPriceHolder__c = false AND
										PCKC__c != null ORDER BY PCKC__c]);
	}
	global void execute(Database.BatchableContext BC,List<sObject> sList)
	{
		List<Sales_Prices__c> acList = sList;
		Map<String,List<Sales_Prices__c>> linkedPCKCHoldersMap = new Map<String,List<Sales_Prices__c>>();
		for(Sales_Prices__c h:acList)
		{
			if(!linkedPCKCHoldersMap.containskey(h.PCKC__c))
			{
				List<Sales_Prices__c> l = new List<Sales_Prices__c>();
				l.add(h);
				linkedPCKCHoldersMap.put(h.PCKC__c,l);
			}
			else
			{
				List<Sales_Prices__c> hList = linkedPCKCHoldersMap.get(h.PCKC__c);
				hList.add(h);
				linkedPCKCHoldersMap.put(h.PCKC__c,hList);
			}
		}
		for(String s:linkedPCKCHoldersMap.keySet())
		{
			List<Sales_Prices__c> pList = new List<Sales_Prices__c>();
			List<Sales_Prices__c> validFromList = new List<Sales_Prices__c>();
			List<Sales_Prices__c> validToList = new List<Sales_Prices__c>();
			Sales_Prices__c pri = new Sales_Prices__c();
			if(linkedPCKCHoldersMap.containsKey(s))
			{
				pList = linkedPCKCHoldersMap.get(s);
				if(pList.size() != 0)
				{
					pri = pList.get(0);
					validFromList = PAUtil.sortList(pList,'Valid_From__c','asc');
					validToList = PAUtil.sortList(pList,'Valid_To__c','desc');
				}
			}
			Sales_Prices__c newholder = new Sales_Prices__c();
			newHolder = pri.clone(false,true);
			newHolder.Approved_Date__c = validFromList.get(0).Valid_From__c;
			newholder.Valid_From__c = validFromList.get(0).Valid_From__c;
			newholder.Valid_To__c = validToList.get(0).Valid_To__c;
			//Since, holder should not have rate,unit,Per,UoM fields populated.
			newHolder.Rate__c = null;
			newHolder.Per__c = null;
			newHolder.UoM__c = null;
			newHolder.Unit__c = null;
			newHolder.OwnerId = pri.OwnerId;
			newHolder.isPriceHolder__c = true;
			mapOfpriAndHolder.put(s,newHolder);
		}
		Set<Sales_Prices__c> upsertHolderSet = new Set<Sales_Prices__c>();
		List<Sales_Prices__c> upsertHolderList = new List<Sales_Prices__c>();
		Map<Id,Sales_Prices__c> idHolderMap = new Map<Id,Sales_Prices__c>();

		for(Sales_Prices__c erp : mapOfpriAndHolder.values())
		{
			upsertHolderSet.add(erp);
		}

		for(Sales_Prices__c e1 : upsertHolderSet)
		{
			upsertHolderList.add(e1);
		}
		upsert upsertHolderList;
		//query the holder //iterate through key set of PCKC get the records, get the holder map
		for(String s1 : linkedPCKCHoldersMap.keySet())
		{
			List<Sales_Prices__c> pList = new List<Sales_Prices__c>();
			Sales_Prices__c hold = new Sales_Prices__c();
			if(linkedPCKCHoldersMap.containsKey(s1))
			{
				pList = linkedPCKCHoldersMap.get(s1);
			}
			if(mapOfpriAndHolder.containsKey(s1))
			{
				hold = mapOfpriAndHolder.get(s1);
			}
			for(Sales_Prices__c h : pList)
			{
				if(hold.Id != null)
					h.Price_Holder__c = hold.Id;
				h.Approved_Date__c = h.Valid_From__c;
				upsertList.add(h);
			}
		}
		upsert upsertList;
	}

	global void finish(Database.BatchableContext info)
	{
	}
}