objects/Organizational_Group_Item__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items (Business1)</relationshipLabel>
        <relationshipName>Organizational_Group_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enable_Request_Class__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enable Request Class</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>OrgGroup</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Items</relationshipLabel>
        <relationshipName>Organizational_Group_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request_Class__c</fullName>
        <label>Request Class</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2nd Life Material (2LM)</fullName>
                </value>
                <value>
                    <fullName>Accessories and Furniture</fullName>
                </value>
                <value>
                    <fullName>Aircraft</fullName>
                </value>
                <value>
                    <fullName>AM</fullName>
                </value>
                <value>
                    <fullName>Apexa</fullName>
                </value>
                <value>
                    <fullName>Apollo Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Apparel</fullName>
                </value>
                <value>
                    <fullName>Apple (PCo)</fullName>
                </value>
                <value>
                    <fullName>APPROVER ONLY</fullName>
                </value>
                <value>
                    <fullName>Aramid Intermediates</fullName>
                </value>
                <value>
                    <fullName>Aramids Intermediates</fullName>
                </value>
                <value>
                    <fullName>Artificial Graphite Sheet</fullName>
                </value>
                <value>
                    <fullName>Asia Pacific</fullName>
                </value>
                <value>
                    <fullName>Auto</fullName>
                </value>
                <value>
                    <fullName>Auto and Other</fullName>
                </value>
                <value>
                    <fullName>Automotive</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>BU Approval only</fullName>
                </value>
                <value>
                    <fullName>BU Approval only (EA)</fullName>
                </value>
                <value>
                    <fullName>BU Approval only (MENAF)</fullName>
                </value>
                <value>
                    <fullName>BU Approval only (WA)</fullName>
                </value>
                <value>
                    <fullName>C&amp;I</fullName>
                </value>
                <value>
                    <fullName>Carpet</fullName>
                </value>
                <value>
                    <fullName>Chemical Industrial</fullName>
                </value>
                <value>
                    <fullName>CHINA</fullName>
                </value>
                <value>
                    <fullName>CI ECEMEA</fullName>
                </value>
                <value>
                    <fullName>Circuit Imaging</fullName>
                </value>
                <value>
                    <fullName>CI WE</fullName>
                </value>
                <value>
                    <fullName>COATINGS</fullName>
                </value>
                <value>
                    <fullName>Commercial</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Organizational Group Item</label>
    <nameField>
        <displayFormat>OGI-{00000}</displayFormat>
        <label>Organizational Group Item Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Organizational_Group_User__c.object
<CustomObject>
    <fields>
        <fullName>Business__c</fullName>
        <formula>Organizational_Group_Item__r.Business__r.Business__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Business</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrgGroup__c</fullName>
        <label>Organizational Group</label>
        <referenceTo>OrgGroup__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Organizational_Group_Item__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Organizational Group Item</label>
        <referenceTo>Organizational_Group_Item__c</referenceTo>
        <relationshipLabel>Organizational Group Users</relationshipLabel>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Organizational_Group_Users</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Organizational Group Users</label>
    <nameField>
        <displayFormat>OGU-{00000}</displayFormat>
        <label>Organizational Group User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Group Users</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ERP_Distribution_Channel_Code__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Distribution_Channel__c</fullName>
        <description>The way in which products or services reach the customer. Typical examples of distribution channels are wholesale, retail, or direct sales.</description>
        <label>Dist. Channel</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Division_Code__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Division__c</fullName>
        <description>A way of grouping materials, products, or services. The system uses divisions to determine the sales areas and business areas to which a material, product, or service belongs. A product or service is always assigned to just one division.</description>
        <label>Division</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Org_Code__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org. Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Sales_Org__c</fullName>
        <description>An organizational unit responsible for the sale of certain products or services.</description>
        <label>Sales Org.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PAHelpLinks__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Help_Link__c</fullName>
        <label>Help Link</label>
        <type>Url</type>
    </fields>
    <label>PAHelpLinks</label>
</CustomObject>

classes/PASalesAreaSelection.cls
// bala - Added variable userIdComponent and modified the way to populate Sales Area
/**************************************************************************************************************
 ***********************************************Modification Log************************************************
<PP20130724>
Last Modified By    :   Priyanka Pillala
Last Modified Date  :   24 Jul 2013
Description         :   Added logic to query for Enable Request Class and Request Class of OGI - APAC ROLLOUT2
 *****************************************************************************************************************
<TJ20140519>
 Last Modified By   :   Tarun
 Last Modified Date :   19 May 2014
 Description        :   Label for Help Link.
 *****************************************************************************************************************/
public with sharing class PASalesAreaSelection implements IPAComponent
{
	//variables
	public List<Organizational_Group_Item__c> salesArea {get;set;}   //The list which will hold all the Sales Area belongs to the selected BU
	public string salesAreaSelected {get;set;}   //Used to display the selected Sales Area in the page
	public string divisionSelected {get;set;}
	public string distChannelSelected {get;set;}
	public string salesOrgSelected {get;set;}
	public boolean dispSAPopup {get;set;}   //flag used to render Sales Area pop up
	public string buIdComponent {get;set;}
	public string buCode {get;set;}   //Used to display the BuCode
	public List<Organizational_Group_Item__c> buOrgList {get;set;}   //The list which holds the BU Org Group for the selected BU
	public string userIdComponent{get;set;}//userIdFromPage
	public list<Organizational_Group_User__c> ogUsersSA {get;set;}
	public string salesAreaId {get;set;}   //used to hold the id of the Sales Area selected
	//For setting current page label

	// <SP20140603> - START
	private boolean displayBoolean = true;
	public boolean enablePopUpBoolean 
	{
		get
		{
			if(enablePopUpBoolean == null) 
			{  
				enablePopUpBoolean = false;
			}

			return enablePopUpBoolean;
		}
		set
		{
			enablePopUpBoolean = value;
			system.debug('enablePopUpBoolean'+enablePopUpBoolean);
			if(enablePopUpBoolean == true && displayBoolean == true)
			{
				displayPopUpWindow();
			}
		}
	}
	//<SP20140603> - END

	//<TJ20140519>
	public String label{get;set;}

	//constructor 
	public PASalesAreaSelection()
	{
		dispSAPopup=false;
	}//constructor ends

	/*
	 * Author      : 
	 * Method Name  :   action
	 * Parameters   :   
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference action()
	{
		return null;
	} 

	/*
	 * Author      : 
	 * Method Name  :   displayPopUpWindowMethod
	 * Parameters   :  
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference displayPopUpWindow()
	{
		return saPopUpOpen();
	}

	/*
	 * Author      : 
	 * Method Name  :   searchCustomer
	 * Parameters   :  
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference dosearch()
	{
		return null;
	}
	/*
	 * Author      : 
	 * Method Name  :   returnData
	 * Parameters   :  
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference returnData()
	{
		enablePopUpBoolean=false;
		return saPopUpClose();
	}

	/*
	 * Author      : 
	 * Method Name  :   closeWindow
	 * Parameters   :  
	 * Return type  :   PageReference
	 * Description  :   
	 */
	public PageReference closeWindow()
	{
		return saPopUpClose();
	}
	/*
	 * Author      :
	 * Method Name : saPopUpOpen
	 * Parameters  : None
	 * Return type : void
	 * Description : Used to display the Sales Area Pop Up
	 */
	public PageReference saPopUpOpen() 
	{
		dispSAPopup=true;
		displayBoolean = false; // <SP20140603> 
		ogUsersSA = new List<Organizational_Group_User__c>();
		if(String.isBlank(userIdComponent))
		{
			userIdComponent = userinfo.getUserId();
		}
		system.debug('@@@@ buIdComponent : ' +buIdComponent+'*** After UserId'+userIdComponent);  
		//<PP20130724>
		ogUsersSA = [SELECT OrgGroup__r.ERP_Sales_Org__c, OrgGroup__r.ERP_Sales_Org_Code__c,OrgGroup__r.ERP_Distribution_Channel__c,
		             OrgGroup__r.ERP_Distribution_Channel_Code__c,OrgGroup__r.ERP_Division__c,OrgGroup__r.ERP_Division_Code__c ,
		             Organizational_Group_Item__r.Request_Class__c,Organizational_Group_Item__r.Enable_Request_Class__c,
		             Organizational_Group_Item__r.Business__c,Organizational_Group_Item__r.Business__r.Business__c FROM Organizational_Group_User__c
		             WHERE Related_User__c =:userIdComponent AND (Organizational_Group_Item__r.Business__c=:buIdComponent OR
		            		 Organizational_Group_Item__r.Business__r.Business__c=:buIdComponent) ORDER BY OrgGroup__r.ERP_Sales_Org_Code__c];
		System.debug('*** After list size'+ogUsersSA );
		return null;
	}

	/*
	 * Author      : 
	 * Method Name : saPopUpClose
	 * Parameters  : None
	 * Return type : void
	 * Description : Used to close the Sales Area Pop Up
	 */
	private PageReference saPopUpClose() 
	{
		dispSAPopup=false;
		return null;
	}
	//<TJ20140519>
	public PageReference helpLink()
	{
		PAHelpLinks__c link;
		link = PAHelpLinks__c.getInstance(label);
		system.debug('**Link '+link.Help_Link__c);
		PageReference pref=new PageReference(link.Help_Link__c);
		pref.setRedirect(false);
		system.debug('**PREF '+pref);
		return pref;
	}
}