objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Owning_Business__c</fullName>
        <description>Owning Business of this record</description>
        <label>Owning Business</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Building Innovations</fullName>
                </value>
                <value>
                    <fullName>Corporate</fullName>
                </value>
                <value>
                    <fullName>Crop Protection</fullName>
                </value>
                <value>
                    <fullName>DuPont Chemicals &amp; Fluoroproducts</fullName>
                </value>
                <value>
                    <fullName>DuPont Protection Technologies</fullName>
                </value>
                <value>
                    <fullName>DuPont Sustainable Solutions</fullName>
                </value>
                <value>
                    <fullName>Electronics and Communications</fullName>
                </value>
                <value>
                    <fullName>Industrial Biosciences</fullName>
                </value>
                <value>
                    <fullName>Nutrition &amp; Health</fullName>
                </value>
                <value>
                    <fullName>Packaging &amp; Industrial Polymers</fullName>
                </value>
                <value>
                    <fullName>Performance Coatings</fullName>
                </value>
                <value>
                    <fullName>Performance Polymers</fullName>
                </value>
                <value>
                    <fullName>Pioneer</fullName>
                </value>
                <value>
                    <fullName>Solae</fullName>
                </value>
                <value>
                    <fullName>DuPont Titanium Technologies</fullName>
                </value>
                <value>
                    <fullName>ZZ - Field Not Used</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Profit_Center__c.object
<CustomObject>
    <fields>
        <fullName>ERP_Profit_Center_4_Code__c</fullName>
        <label>Profit Center 4 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_4__c</fullName>
        <label>Profit Center 4</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_5_Code__c</fullName>
        <label>Profit Center 5 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_5__c</fullName>
        <label>Profit Center 5</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_6_Code__c</fullName>
        <label>Profit Center 6 Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_6__c</fullName>
        <label>Profit Center 6</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_7_Code__c</fullName>
        <label>Profit Center 7 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_7__c</fullName>
        <label>Profit Center 7</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_8_Code__c</fullName>
        <label>Profit Center 8 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_8__c</fullName>
        <label>Profit Center 8</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_9_Code__c</fullName>
        <label>Profit Center 9 Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERP_Profit_Center_9__c</fullName>
        <label>Profit Center 9</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Profit Center</label>
    <nameField>
        <displayFormat>PC-{00000}</displayFormat>
        <label>Profit Center Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Profit Center</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/PAProfitCenterSelection_UT.cls
@isTest
public class PAProfitCenterSelection_UT{
    
    static testMethod void PAProfitCenterSelectionTestMethod()
    {

        
        
        OrgGroup__c orgGrp = new OrgGroup__c();
        orgGrp.Business__c ='Surfaces';
        orgGrp.Owning_Business__c='BUILDING INOVATIONS';
        insert orgGrp;
        
        OrgGroup__c orgGrp1 = new OrgGroup__c();
        orgGrp1.Business__c ='Surface';
        orgGrp1.Owning_Business__c='BUILDING INOVATIONS';
        insert orgGrp1;
        Profit_Center__c p1=new  Profit_Center__c();
        p1.ERP_Profit_Center_4__c='BUILDING INOVATIONS';
        p1.ERP_Profit_Center_4_Code__c='c4';
        p1.ERP_Profit_Center_5__c='f';
        p1.ERP_Profit_Center_5_Code__c='c5';
        p1.ERP_Profit_Center_6__c='f';
        p1.ERP_Profit_Center_6_Code__c='c6';
        p1.ERP_Profit_Center_7__c='f';
        p1.ERP_Profit_Center_7_Code__c='c7';
        p1.ERP_Profit_Center_8__c='f';
        p1.ERP_Profit_Center_8_Code__c='c8';
        p1.ERP_Profit_Center_9__c='f';
        p1.ERP_Profit_Center_9_Code__c='c9';
        
        insert p1;
        Profit_Center__c p2=new  Profit_Center__c();
        p2.ERP_Profit_Center_4__c='BUILDING INOVATIONS';
        p2.ERP_Profit_Center_4_Code__c='c4';
        p2.ERP_Profit_Center_5__c='';
        p2.ERP_Profit_Center_5_Code__c='';
        p2.ERP_Profit_Center_6__c='f';
        p2.ERP_Profit_Center_6_Code__c='c6';
        p2.ERP_Profit_Center_7__c='f';
        p2.ERP_Profit_Center_7_Code__c='c7';
        p2.ERP_Profit_Center_8__c='f';
        p2.ERP_Profit_Center_8_Code__c='c8';
        p2.ERP_Profit_Center_9__c='f';
        p2.ERP_Profit_Center_9_Code__c='c9';        
        insert p2;
        Profit_Center__c p3=new  Profit_Center__c();
        p3.ERP_Profit_Center_4__c='BUILDING INOVATIONS';
        p3.ERP_Profit_Center_4_Code__c='c4';
        p3.ERP_Profit_Center_5__c='';
        p3.ERP_Profit_Center_5_Code__c='';
        p3.ERP_Profit_Center_6__c='f';
        p3.ERP_Profit_Center_6_Code__c='c6';
        p3.ERP_Profit_Center_7__c='f';
        p3.ERP_Profit_Center_7_Code__c='c7';
        p3.ERP_Profit_Center_8__c='f';
        p3.ERP_Profit_Center_8_Code__c='c8';
        p3.ERP_Profit_Center_9__c='f';
        p3.ERP_Profit_Center_9_Code__c='c9';        
        insert p3;
        
        PAProfitCenterSelection  profitCenterSelection =new PAProfitCenterSelection ();
        profitCenterSelection.selectedBUFromPage=orgGrp.id;  
        profitCenterSelection.desiredAction='populateFRB';
        profitCenterSelection.action();
        profitCenterSelection.displayPopUpWindow();
        profitCenterSelection.selectedFRB4='C4';
        profitCenterSelection.selectedFRB5='C5';
        profitCenterSelection.selectedFRB6='C6';
        profitCenterSelection.selectedFRB7='C7';
        profitCenterSelection.selectedFRB8='C8';
        profitCenterSelection.selectedFRB9='C9';
        profitCenterSelection.dosearch();
        profitCenterSelection.returnData();
        profitCenterSelection.closeWindow();
        
        //level 1
        PAProfitCenterSelection  profitCenterSelection1 =new PAProfitCenterSelection ();
        profitCenterSelection1.selectedBUFromPage=orgGrp1.id;      
        profitCenterSelection1.desiredAction='populateFRB';
        profitCenterSelection.selectedFRB4='C4';
        profitCenterSelection.selectedFRB5=null;
        profitCenterSelection.selectedFRB6=null;
        profitCenterSelection.selectedFRB7=null;
        profitCenterSelection.selectedFRB8=null;
        profitCenterSelection.selectedFRB9=null;
        profitCenterSelection1.action();
        
        //Level 2
        profitCenterSelection.selectedFRB4='C4';
        profitCenterSelection.selectedFRB4='C5';
        profitCenterSelection1.action();
        
        //Level 3
        profitCenterSelection.selectedFRB4='C4';
        profitCenterSelection.selectedFRB4='C5';
         profitCenterSelection.selectedFRB4='C6';
        profitCenterSelection1.action();
        
        //Level < previousLevel
        profitCenterSelection.selectedFRB4='C4';
        profitCenterSelection.selectedFRB4='C5';
        profitCenterSelection.selectedFRB4=null;
        profitCenterSelection1.action();
        
        profitCenterSelection1.displayPopUpWindow();
        profitCenterSelection1.dosearch();
        profitCenterSelection1.returnData();
        profitCenterSelection1.closeWindow();
    
    }



    
    
    
}