objects/OrgGroup__c.object
<CustomObject>
    <description>Identifies a fundamental framework or collection of entities, assets. people, processes etc. which are related for administrative purposes in Force.com. (example of use cases: identify a Sales Area grouping of master data from SAP; identify metadata asset grouping for a CRM Program; identify security asset grouping used for a program sharing model, etc.)</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Used to define the Business Name and link Sales Area to this record.</description>
        <label>Business</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Organizational Group</label>
    <nameField>
        <displayFormat>OG-{0000000000}</displayFormat>
        <label>Org Group Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Organizational Groups</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/PA_Email_Template_Custom_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This will store the template Ids that are used for Approval flow.</description>
    <fields>
        <fullName>Template_Id__c</fullName>
        <label>Template Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>PA Email Template Custom Settings</label>
</CustomObject>

objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approver1_Date__c</fullName>
        <description>Identifies when the First Approver Approves the record</description>
        <label>Non-Object 1 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the First Approver who should approve the record</description>
        <label>Non-Object 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2_Date__c</fullName>
        <description>Identifies when the Second Approver Approves the record</description>
        <label>Non-Object 2 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Second Approver who should approve the record</description>
        <label>Non-Object 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3_Date__c</fullName>
        <description>Identifies when the Third Approver Approves the record</description>
        <label>Non-Object 3 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Third Approver who should approve the record</description>
        <label>Non-Object 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver4_Date__c</fullName>
        <description>Identifies when the Fourth Approver Approves the record</description>
        <label>Non-Object 4 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Fourth Approver who should approve the record</description>
        <label>Non-Object 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver5_Date__c</fullName>
        <description>Identifies when the Fifth Approver Approves the record</description>
        <label>Final Approval Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Fifth Approver who should approve the record</description>
        <label>Final Approval</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Backup_Level_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backup Level 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests8</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backup_Level_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backup Level 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests9</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backup_Level_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backup Level 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requestsn0Qh</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backup_Level_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backup Level 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requestsn0Qr</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Backup_Level_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Backup Level 5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requestsn0Qs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Current_Level__c</fullName>
        <description>Identifies approval level</description>
        <label>Current Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NPC_Status__c</fullName>
        <label>Net Price Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SoldTo_Code__c</fullName>
        <label>SoldTo Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricing_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>Approver1_Date__c</fullName>
        <label>Approver1 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2_Date__c</fullName>
        <label>Approver2 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Request_Item</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3_Date__c</fullName>
        <label>Approver3 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Request_Item1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver4_Date__c</fullName>
        <label>Approver4 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Request_Item2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver5_Date__c</fullName>
        <label>Approver5 Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Approver5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approver5</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Request_Item3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <formula>Pricing_Request__r.BU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Price_Status__c</fullName>
        <label>Net Price Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <label>Pricing Request</label>
        <referenceTo>Pricing_Request__c</referenceTo>
        <relationshipLabel>Pricing Request Item</relationshipLabel>
        <relationshipName>Pricing_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Pricing Request Item</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Request Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Request Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Out_of_Office_End_Date__c</fullName>
        <label>Out of Office End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Out_of_Office_Start_Date__c</fullName>
        <label>Out of Office Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Out_of_Office__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Out of Office</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TrigPricingRequest_UT.cls
@istest
public class TrigPricingRequest_UT {
    
    static testMethod void tiggerHandTest() {
        
        Profile p1 =[SELECT Id FROM Profile where name='Price Approval-BU Admin'];
        
        UserRole r= TestUserUtil.createTestUserRole('BI-EMEA-Surfaces');
        
        User user1 = TestUserUtil.createTestUser(r.id, p1.id, 'test fName', 'test lName');    
        insert user1;
        
        User user2 = TestUserUtil.createTestUser(r.id, p1.id, 'test fName', 'test lName',user1.id);    
        user2.out_of_office__c=true;
        user2.out_of_Office_start_date__c = system.today();
        user2.out_of_Office_End_date__c = system.today();
        insert user2;
        system.runas(user1){
            
            User user = user2;
            
            EmailTemplate e = [SELECT Id FROM EmailTemplate Limit 1];
            
            PA_Email_Template_Custom_Settings__c p = new PA_Email_Template_Custom_Settings__c();
            p.Name = 'EscalationNotificationToBackupApprover';
            p.Template_Id__c = e.Id;
            insert p;
            
            p = new PA_Email_Template_Custom_Settings__c();
            p.Name = 'EscalationNotificationtoBUAdmin';
            p.Template_Id__c = e.Id;
            insert p;            
            
            p = new PA_Email_Template_Custom_Settings__c();
            p.Name = 'EscalationNotificationNoBackup';
            p.Template_Id__c = e.Id;
            insert p;
            
            p = new PA_Email_Template_Custom_Settings__c();
            p.Name = 'escalatedToBuAdmin';
            p.Template_Id__c = e.Id;
            insert p;
            
            OrgGroup__c orgGrp = new OrgGroup__c();
            orgGrp.Business__c = 'BI EMEA Surfaces1';
            insert orgGrp;  
            
            Pricing_Request__c prObj = new Pricing_Request__c();
            prObj.Request_Approval_Status__c = 'Submitted';
            prObj.BU__c = 'BI EMEA Surfaces1';
            prObj.NPC_Status__c ='Waiting for Submission';
            insert prObj;  
            
            Pricing_Request_Item__c prItem2 = new Pricing_Request_Item__c();        
            prItem2.Pricing_Request__c = prObj.id;        
            prItem2.Key_Combination__c='Salea Area/Material';
            prItem2.Net_Price_Status__c = '';               
            insert prItem2;
            
            Pricing_Request_Item__c prItem = new Pricing_Request_Item__c();        
            prItem.Pricing_Request__c = prObj.id;        
            prItem.Key_Combination__c='Salea Area/Material'; 
            prItem.Net_Price_Status__c = 'Waiting For Net Price';           
            insert prItem;              
            
            update prObj;
            
            Pricing_Request__c prObjFromDB = [SELECT id FROM Pricing_Request__c WHERE id = :prObj.id];           
            
            prObjFromDB.Current_Level__c ='1';
            prObjFromDB.Approver1__c = user.id;
            prObjFromDB.Approver2__c = user.id;
            prObjFromDB.Approver3__c = user.id;
            prObjFromDB.Approver4__c = user.id;
            prObjFromDB.Approver5__c = user.id;
            /*******************/
            prObjFromDB.Backup_Level_1__c = user.Id;
            prObjFromDB.Backup_Level_2__c = user.Id;
            prObjFromDB.Backup_Level_3__c = user.Id;
            prObjFromDB.Backup_Level_4__c = user.Id;
            prObjFromDB.Backup_Level_5__c = user.Id;
            
            /******************/
            prObjFromDB.Approver1_Date__c = system.now();
            prObjFromDB.NPC_Status__c='Waiting For Submission';
            prObjFromDB.Request_Approval_Status__c='Canceled';      
            prObjFromDB.SoldTo_Code__c='Test';   
            prObjFromDB.Request_Approval_Status__c='Draft';
            upsert prObjFromDB;  
            
            /******************************/
            Pricing_Request_Item__c prItem1 = new Pricing_Request_Item__c();        
            prItem1.Pricing_Request__c = prObjFromDB.id;        
            prItem1.Key_Combination__c='Salea Area/Material'; 
            prItem1.Net_Price_Status__c = 'Waiting For Net Price';           
            insert prItem1; 
            /*****************************/
            
            prObjFromDB.Current_Level__c ='1';
            prObjFromDB.Approver1__c = user.id;
            prObjFromDB.Approver2__c = user.id;
            prObjFromDB.Approver3__c = user.id;
            prObjFromDB.Approver4__c = user.id;
            prObjFromDB.Approver5__c = user.id;
            /*******************/
            prObjFromDB.Backup_Level_1__c = user.Id;
            prObjFromDB.Backup_Level_2__c = user.Id;
            prObjFromDB.Backup_Level_3__c = user.Id;
            prObjFromDB.Backup_Level_4__c = user.Id;
            prObjFromDB.Backup_Level_5__c = user.Id;
            /******************/
            prObjFromDB.Approver1_Date__c = system.now();
            prObjFromDB.NPC_Status__c='Waiting For Submission';
            prObjFromDB.Request_Approval_Status__c='Submitted';      
            
            upsert prObjFromDB;
            
            prObjFromDB.Current_Level__c ='2';
            prObjFromDB.Approver1__c = user.id;
            prObjFromDB.Approver2__c = user.id;
            prObjFromDB.Approver3__c = user.id;
            prObjFromDB.Approver4__c = user.id;
            prObjFromDB.Approver5__c = user.id;
            prObjFromDB.Approver2_Date__c = system.now();
            prObjFromDB.NPC_Status__c='Waiting For Net Price';
            prObjFromDB.Request_Approval_Status__c='Validated'; 
            /*******************/
            prObjFromDB.Backup_Level_1__c = user.Id;
            prObjFromDB.Backup_Level_2__c = user.Id;
            prObjFromDB.Backup_Level_3__c = user.Id;
            prObjFromDB.Backup_Level_4__c = user.Id;
            prObjFromDB.Backup_Level_5__c = user.Id;
            /*******************/
            
            upsert prObjFromDB;
            
            
            prObjFromDB.Current_Level__c ='3';
            prObjFromDB.Approver1__c = user.id;
            prObjFromDB.Approver2__c = user.id;
            prObjFromDB.Approver3__c = user.id;
            prObjFromDB.Approver4__c = user.id;
            prObjFromDB.Approver5__c = user.id;
            prObjFromDB.Approver3_Date__c = system.now();
            /*******************/
            prObjFromDB.Backup_Level_1__c = user.Id;
            prObjFromDB.Backup_Level_2__c = user.Id;
            prObjFromDB.Backup_Level_3__c = user.Id;
            prObjFromDB.Backup_Level_4__c = user.Id;
            prObjFromDB.Backup_Level_5__c = user.Id;
            /*******************/
            prObjFromDB.Request_Approval_Status__c='Submitted';
            prObjFromDB.NPC_Status__c = 'Waiting for Net Price';
            upsert prObjFromDB;
            
            
            prObjFromDB.Current_Level__c ='4';
            prObjFromDB.Approver1__c = user.id;
            prObjFromDB.Approver2__c = user.id;
            prObjFromDB.Approver3__c = user.id;
            prObjFromDB.Approver4__c = user.id;
            prObjFromDB.Approver5__c = user.id;
            /*******************/
            prObjFromDB.Backup_Level_1__c = user.Id;
            prObjFromDB.Backup_Level_2__c = user.Id;
            prObjFromDB.Backup_Level_3__c = user.Id;
            prObjFromDB.Backup_Level_4__c = user.Id;
            prObjFromDB.Backup_Level_5__c = user.Id;
            /******************/
            prObjFromDB.Approver4_Date__c = system.now();
            //prObjFromDB.Request_Approval_Status__c='Approved';    
            prObjFromDB.SoldTo_Code__c='Test'; //   
            upsert prObjFromDB;
            
            
            prObjFromDB.Current_Level__c ='5';
            prObjFromDB.Approver1__c = user.id;
            prObjFromDB.Approver2__c = user.id;
            prObjFromDB.Approver3__c = user.id;
            prObjFromDB.Approver4__c = user.id;
            prObjFromDB.Approver5__c = user.id;
            /*******************/
            prObjFromDB.Backup_Level_1__c = user.Id;
            prObjFromDB.Backup_Level_2__c = user.Id;
            prObjFromDB.Backup_Level_3__c = user.Id;
            prObjFromDB.Backup_Level_4__c = user.Id;
            prObjFromDB.Backup_Level_5__c = user.Id;
            /******************/
            prObjFromDB.Approver5_Date__c = system.now();
            upsert prObjFromDB;
            
            PricingRequestHandler base = new PricingRequestHandler();
            //RType.SObjectRTypes type = base.rTypes;
            Pricing_Request__c so = new Pricing_Request__c();
            
            try{
                //delete prObjFromDB;
            }catch(exception e1){}
            Pricing_Request__c prObj22 = new Pricing_Request__c();
            prObj22.Request_Approval_Status__c = 'Submitted';
            prObj22.BU__c = 'BI EMEA Surfaces1';
            prObj22.NPC_Status__c ='Waiting for Submission';
            insert prObj22;  
            list<Pricing_Request__c> delpr = [Select id from Pricing_Request__c where id=:prObj22.id];
            delete delpr;
            
        }
    }
    
}