objects/PABusinessToNotify__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is to activate the daily notification for the mentioned business</description>
    <fields>
        <fullName>Daily_Notification__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Daily Notification</label>
        <type>Checkbox</type>
    </fields>
    <label>PABusinessToNotify</label>
</CustomObject>

objects/PAProfilePermissions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Name__c</fullName>
        <description>Stores the API Name of the permission sets</description>
        <label>API Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PAProfilePermissions</label>
</CustomObject>

objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Current Approver with whom the record is</description>
        <label>Current Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>E_Pass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems - found in MyAccess &amp; in the User&apos;s NAB Entry</description>
        <label>E-Pass ID</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</inlineHelpText>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED KINGDOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/BatchDailyNotifications_UT.cls
/*
Date : 29/12/2016
Change : Merge & Spin- Updated the test  class to update the insert of UserRole and User.
*/
@isTest 
//(SeeAllData=true)
private class BatchDailyNotifications_UT {
    
    
    static testMethod void BatchDailyNotificationsTestMethod() {
        
        Profile p =[SELECT Id FROM Profile where name='Price Approval-Viewer'];
        //Start: Updated as a part of Merge & Spin to the change the UserRole name.
        UserRole Ur = TestUserUtil.createTestUserRole('BI-EMEA-Surfaces');
        insert Ur;
        /*
        UserRole r=[SELECT Id FROM UserRole WHERE developerName='BI_EMEA_Surfaces'];  
        system.debug('roleeeeeeeeee'+r);                 
        User u3 =  new User(Alias='pcopp', Email='ambili_vinay@infosys.com', 
                         User_Country__c='UNITED KINGDOM',E_Pass_ID__c='rr9847',
                         External_ERP_ID__c='testDailyNotification',UserRoleId=r.id,profileid = p.id,
         
                        Username='pa_werner1@jhhgtestinfosys.com.test2', LastName='Coppens', CommunityNickname='acv', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US'); 
        insert u3; 
        */

  
        User usr= TestUserUtil.createTestUser(Ur.Id,p.Id,'Test FirstName','Test LastName');
        insert usr;
        //End: Updated as a part of Merge & Spin to the change the UserRole name.
                    
    System.RunAs(usr) 
    {
        List<PABusinessToNotify__c> NotifyList = new List<PABusinessToNotify__c>();
        PABusinessToNotify__c Notify1 = new PABusinessToNotify__c();
        Notify1.Name = 'BI EMEA';
        Notify1.Daily_Notification__c = True;
        NotifyList.add(Notify1);
        PABusinessToNotify__c Notify2 = new PABusinessToNotify__c();
        Notify2.Name = 'BI EMEA1';
        Notify2.Daily_Notification__c = True;
        NotifyList.add(Notify2);
        PABusinessToNotify__c Notify3 = new PABusinessToNotify__c();
        Notify3.Name = 'BI EMEA2';
        Notify3.Daily_Notification__c = True;
        NotifyList.add(Notify3);
        PABusinessToNotify__c Notify4 = new PABusinessToNotify__c();
        Notify4.Name = 'BI EMEA3';
        Notify4.Daily_Notification__c = True;
        NotifyList.add(Notify4);
        
        insert NotifyList;
        
        PAProfilePermissions__c paProfilePermissions1 = new PAProfilePermissions__c();
        paProfilePermissions1.Name = 'Approver';
        paProfilePermissions1.API_NAME__c = 'Price_Approval_Approver';
        insert paProfilePermissions1;
        PermissionSet ps = [SELECT ID From PermissionSet WHERE Name = :PAProfilePermissions__c.getInstance('Approver').API_Name__c];
               
        //String userid=[Select id from user where Alias='pcopp' and Email='ambili_vinay@infosys.com'].id;
        insert new PermissionSetAssignment(AssigneeId = usr.id, PermissionSetId = ps.Id );                    
        Pricing_Request__c s=new Pricing_Request__c();
        s.Current_Approver__c=usr.id;
        s.BU__c = 'BI EMEA';
        s.Request_Approval_Status__c='Submitted';
        
        insert s;
        

        
          BatchDailyNotifications bc=new BatchDailyNotifications();
          
         // Batch7DayDSULead dsulead = new Batch7DayDSULead(selectedday);
          bc.runTestMethod=true;
          Database.executeBatch( bc);
    // Test.startTest(); 

    }
    }    
   
}