objects/PABusinessForExpiryNotification__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Custom setting to store business Names region wise. It is used to identify business values for Customer Expiry Notification</description>
    <fields>
        <fullName>Business__c</fullName>
        <description>Business Names concatenated with &apos;,&apos; belonging to same region</description>
        <label>Business</label>
        <type>TextArea</type>
    </fields>
    <label>PABusinessForExpiryNotification</label>
</CustomObject>

objects/PANonCustomerBUForExpiryNotification__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds Business Name that are required for notification for Non Customer Prices</description>
    <fields>
        <fullName>BusinessNonCustomer__c</fullName>
        <description>Business to receive non customer prices</description>
        <label>BusinessNonCustomer</label>
        <type>TextArea</type>
    </fields>
    <label>PANonCustomerBUForExpiryNotification</label>
</CustomObject>

classes/PAScheduleCustomerPriceDueToExpire_UT.cls
@isTest
private class PAScheduleCustomerPriceDueToExpire_UT
{
    static testMethod void PAScheduleCustomerPriceDueToExpireTestMethod() 
    {   
        insert new PABusinessForExpiryNotification__c(Name='APBu',Business__c = 'P&IP ECP AP');
        insert new PABusinessForExpiryNotification__c(Name='EMEABu',Business__c = 'P&IP ECP EMEA');
        insert new PABusinessForExpiryNotification__c(Name='LABu',Business__c = 'P&IP ECP LA');
        insert new PABusinessForExpiryNotification__c(Name='NABu',Business__c = 'P&IP ECP NA');
        insert new PABusinessForExpiryNotification__c(Name='GlobalBu',Business__c = 'P&IP ECP NA');
        insert new PABusinessForExpiryNotification__c(Name='DPPGlobalBu',Business__c = 'P&IP ECP NA');
        insert new PANonCustomerBUForExpiryNotification__c(Name='EmeaBuNC',BusinessNonCustomer__c='NC_P&IP ECP EMEA');
        insert new PANonCustomerBUForExpiryNotification__c(Name='GlobalBuNC',BusinessNonCustomer__c='NC_DPP Global Kalrez & Vespel');
        
        /*
        BatchDailyNotifications sd=new BatchDailyNotifications();
        database.executebatch(sd, 8);*/
        PAScheduleCustomerPriceDueToExpire m = new PAScheduleCustomerPriceDueToExpire();
        String sch = '0 24 15 * * ? ';
        system.schedule('Merge Job',sch, m);
        
       
    } 
    
}