objects/PAKeyCombinationUpdate__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Used to store old and new key combination values as per SAP table changes</description>
    <fields>
        <fullName>NewKCCode__c</fullName>
        <label>NewKCCode</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>PAKeyCombinationUpdate</label>
</CustomObject>

objects/PAProfilePermissions__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>API_Name__c</fullName>
        <description>Stores the API Name of the permission sets</description>
        <label>API Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name of the profile</description>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>PAProfilePermissions</label>
</CustomObject>

objects/Skip_All_Triggers_PA__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Merge &amp; Spin: To skip all trigger logic while data load</description>
    <label>Skip All Triggers PA</label>
</CustomObject>

classes/TestCustomSettingUtil.cls
/*
 * 12/29/2016 - Merge&Spin - Created Util class for custom settings
 * */
@isTest
public class TestCustomSettingUtil {

    public static List<PAProfilePermissions__c> testPAProfilePermissions(){
         List<PAProfilePermissions__c> profilePermissionList = new List<PAProfilePermissions__c>();
                  profilePermissionList.add(new PAProfilePermissions__c(Name='Sales Admin',API_Name__c='Price_Approval_Sales_Admin'));
                  profilePermissionList.add(new PAProfilePermissions__c(Name='Approver',API_Name__c='Price Approval-Approver'));
                  profilePermissionList.add(new PAProfilePermissions__c(Name='CSR',API_Name__c='Price Approval-CSR'));
                  profilePermissionList.add(new PAProfilePermissions__c(Name='BU Admin',Name__c='Price Approval-BU Admin'));
                   profilePermissionList.add(new PAProfilePermissions__c(Name='IT Admin',Name__c='Price Approval-IT Admin'));
                  profilePermissionList.add(new PAProfilePermissions__c(Name='Price Requester',Name__c='Price Approval-Price Requester'));
                return profilePermissionList;        
        
    }
    //<20171403> Merge&Spin: Added method to create test data for PAKeyCombinationUpdate__c custom setting
    public static void PAKeyCombinationUpdateTestData(){
        List<PAKeyCombinationUpdate__c> PAKeyCombinationUpdateList = new List<PAKeyCombinationUpdate__c>();
        PAKeyCombinationUpdateList.add(new PAKeyCombinationUpdate__c(Name='A692',NewKCCode__c='A986'));
        PAKeyCombinationUpdateList.add(new PAKeyCombinationUpdate__c(Name='A920',NewKCCode__c='A578'));
        PAKeyCombinationUpdateList.add(new PAKeyCombinationUpdate__c(Name='A560',NewKCCode__c='A533'));
        PAKeyCombinationUpdateList.add(new PAKeyCombinationUpdate__c(Name='A691',NewKCCode__c='A534'));
        PAKeyCombinationUpdateList.add(new PAKeyCombinationUpdate__c(Name='A693',NewKCCode__c='A805'));
        PAKeyCombinationUpdateList.add(new PAKeyCombinationUpdate__c(Name='A949',NewKCCode__c='A674'));
        insert PAKeyCombinationUpdateList;
    }
    
  /*  public static void createSkipTriggerTestData(){
        Test.loadData(Skip_All_Triggers_PA__c.sObjectType,'Skip_All_Triggers_PA_TestData');
    }*/
}