objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Specific__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies if the record is customer specific / Non Customer Specific</description>
        <label>Customer Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dist_Channel_Code__c</fullName>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request_Type__c</fullName>
        <label>Pricing Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Project Pricing</fullName>
                </value>
                <value>
                    <fullName>Pricing Task</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Reference Price</fullName>
                </value>
                <value>
                    <fullName>Floor Price</fullName>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Pricing Request</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Net Floor</fullName>
                </value>
                <value>
                    <fullName>Net Reference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isNPCApplicable__c</fullName>
        <label>isNPCApplicable</label>
        <summaryFilterItems>
            <field>Pricing_Request_Item__c.isNPCApplicable__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryForeignKey>Pricing_Request_Item__c.Pricing_Request__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Pricing_Request_Item__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Requested</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <formula>Pricing_Request__r.BU__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BU</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Specific__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Customer Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dist_Channel_Code__c</fullName>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination_Code__c</fullName>
        <label>Key Combination Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Material_Code__c</fullName>
        <label>Material Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Price_Status__c</fullName>
        <label>Net Price Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_Rate__c</fullName>
        <label>New Rate</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Valid_From__c</fullName>
        <label>New Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>New_Valid_To__c</fullName>
        <label>New Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PH1_Code__c</fullName>
        <label>PH1 Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Condition_Code__c</fullName>
        <label>Pricing Condition Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request_Type__c</fullName>
        <label>Pricing Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Project</fullName>
                </value>
                <value>
                    <fullName>Spot</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Request__c</fullName>
        <label>Pricing Request</label>
        <referenceTo>Pricing_Request__c</referenceTo>
        <relationshipLabel>Pricing Request Item</relationshipLabel>
        <relationshipName>Pricing_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To_Code__c</fullName>
        <label>Sold To Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isNPCApplicable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isNPCApplicable</label>
        <type>Checkbox</type>
    </fields>
    <label>Pricing Request Item</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Request Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Request Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BU_PricingRequestItem_DuplicateCheck_UT.cls
/*
 * Name		 :   BU_PricingRequestItem_DuplicateCheck_UT
 * Description  :   This is the test class for BU_PricingRequestItem_DuplicateCheck
 * Author	   :   Infosys Limited
 * Created Date :   23-03-2013
 *
 * Version	  Modified Date	   Modified By	 Modification
 * ------------------------------------------------------------------------------
 */
@isTest
private class BU_PricingRequestItem_DuplicateCheck_UT
{
	static testMethod void BU_PricingRequestItem_DuplicateCheckTestMethod1()
	{
		try
		{
			Date d = Date.valueOf(System.NOW());
			//Inserting Pricing Requests
			List<Pricing_Request__c> pricingRequestList = new List<Pricing_Request__c>();
			Pricing_Request__c pricingReq1 = new Pricing_Request__c();
			pricingReq1.BU__c = 'BI EMEA Surfaces';
			pricingReq1.Sales_Org_Code__c = 'A640';
			pricingReq1.Dist_Channel_Code__c = '10';
			pricingReq1.Division_Code__c = '02';
			pricingReq1.Pricing_Request_Type__c = 'Permanent';
			pricingReq1.Request_Approval_Status__c = 'Draft';
			pricingReq1.Customer_Specific__c = true;
			pricingRequestList.add(pricingReq1);
			Pricing_Request__c pricingReq2 = new Pricing_Request__c();
			pricingReq2.BU__c = 'BI EMEA Surfaces';
			pricingReq2.Sales_Org_Code__c = 'A640';
			pricingReq2.Dist_Channel_Code__c = '10';
			pricingReq2.Division_Code__c = '02';
			pricingReq2.Pricing_Request_Type__c = 'Project Pricing';
			pricingReq2.Request_Approval_Status__c = 'Draft';
			pricingReq2.Customer_Specific__c = true;
			pricingRequestList.add(pricingReq2);
			insert pricingRequestList;

			//Inserting Pricing Request Items corresponding to the above request
			List<Pricing_Request_Item__c> pricingReqItemList = new List<Pricing_Request_Item__c>();
			Pricing_Request_Item__c priReqItem1 = new Pricing_Request_Item__c();
			priReqItem1.Sales_Org_Code__c = 'A640';
			priReqItem1.Dist_Channel_Code__c = '10';
			priReqItem1.Division_Code__c = '02';
			priReqItem1.Pricing_Request_Type__c = 'Permanent';
			priReqItem1.Approval_Status__c = 'Draft';
			priReqItem1.Customer_Specific__c = true;
			priReqItem1.Pricing_Request__c = pricingReq1.Id;
			priReqItem1.Pricing_Condition_Code__c = 'ZPSE';
			priReqItem1.Key_Combination_Code__c = 'A580';
			priReqItem1.Material_Code__c = 'D123456';
			priReqItem1.Sold_To_Code__c = '5512342';
			priReqItem1.PH1_Code__c = 'A6';
			priReqItem1.New_Valid_From__c = d;
			priReqItem1.New_Valid_To__c = d+30;
			pricingReqItemList.add(priReqItem1);
			Pricing_Request_Item__c priReqItem2 = new Pricing_Request_Item__c();
			priReqItem2.Sales_Org_Code__c = 'A640';
			priReqItem2.Dist_Channel_Code__c = '10';
			priReqItem2.Division_Code__c = '02';
			priReqItem2.Pricing_Request_Type__c = 'Permanent';
			priReqItem2.Approval_Status__c = 'Draft';
			priReqItem2.Customer_Specific__c = true;
			priReqItem2.Pricing_Request__c = pricingReq1.Id;
			priReqItem2.Pricing_Condition_Code__c = 'ZPSE';
			priReqItem2.Key_Combination_Code__c = 'A580';
			priReqItem2.Material_Code__c = 'D123456';
			priReqItem2.Sold_To_Code__c = '5512342';
			priReqItem2.PH1_Code__c = 'A6';
			priReqItem2.New_Valid_From__c = d+31;
			priReqItem2.New_Valid_To__c = d+60;
			pricingReqItemList.add(priReqItem2);
			insert pricingReqItemList;

			//Inserting Priicng Request Item which overlaps with the above Request Item
			Pricing_Request_Item__c priReqItem3 = new Pricing_Request_Item__c();
			priReqItem3.Sales_Org_Code__c = 'A640';
			priReqItem3.Dist_Channel_Code__c = '10';
			priReqItem3.Division_Code__c = '02';
			priReqItem3.Pricing_Request_Type__c = 'Permanent';
			priReqItem3.Approval_Status__c = 'Draft';
			priReqItem3.Customer_Specific__c = true;
			priReqItem3.Pricing_Request__c = pricingReq1.Id;
			priReqItem3.Pricing_Condition_Code__c = 'ZPSE';
			priReqItem3.Key_Combination_Code__c = 'A580';
			priReqItem3.Material_Code__c = 'D123456';
			priReqItem3.Sold_To_Code__c = '5512342';
			priReqItem3.PH1_Code__c = 'A6';
			priReqItem3.New_Valid_From__c = d+15;
			priReqItem3.New_Valid_To__c = d+30;
			priReqItem3.isNPCApplicable__c= true;
			priReqItem3.Net_Price_Status__c='Mat not found';
			insert priReqItem3;
			
			priReqItem3.Net_Price_Status__c='Waiting for Net Price';
			update priReqItem3;
			
			Pricing_Request_Item__c priReqItem4 = new Pricing_Request_Item__c();
			priReqItem4.Sales_Org_Code__c = 'A640';
			priReqItem4.Dist_Channel_Code__c = '10';
			priReqItem4.Division_Code__c = '02';
			priReqItem4.Pricing_Request_Type__c = 'Permanent';
			priReqItem4.Approval_Status__c = 'Draft';
			priReqItem4.Customer_Specific__c = true;
			priReqItem4.Pricing_Request__c = pricingReq1.Id;
			priReqItem4.Pricing_Condition_Code__c = 'ZPAE';
			priReqItem4.Key_Combination_Code__c = 'A580';
			priReqItem4.Sold_To_Code__c = '5512342';
			priReqItem4.New_Valid_From__c = d+15;
			priReqItem4.New_Valid_To__c = d+30;
			priReqItem4.isNPCApplicable__c= true;
			priReqItem4.Net_Price_Status__c='Mat not found';
			insert priReqItem4;
			
			priReqItem4.Net_Price_Status__c='Waiting for Net Price';
			update priReqItem4;
			
			priReqItem2.isNPCApplicable__c= true;
			priReqItem2.Net_Price_Status__c='Net Price Received';
			priReqItem2.Approval_Status__c='Submitted';
			update priReqItem2;
			
			priReqItem2.Approval_Status__c='Recalled';
			update priReqItem2;
			
			priReqItem2.Approval_Status__c='Recalled';
			update priReqItem2;
			
			priReqItem2.Approval_Status__c='Rejected';
			update priReqItem2;
			
			priReqItem2.Approval_Status__c='Rejected';
			update priReqItem2;
			
			Pricing_Request_Item__c priReqItem5 = new Pricing_Request_Item__c();
			priReqItem5.Sales_Org_Code__c = 'A640';
			priReqItem5.Dist_Channel_Code__c = '10';
			priReqItem5.Division_Code__c = '02';
			priReqItem5.Pricing_Request_Type__c = 'Permanent';
			priReqItem5.Approval_Status__c = 'Draft';
			priReqItem5.Customer_Specific__c = true;
			priReqItem5.Pricing_Request__c = pricingReq1.Id;
			priReqItem5.Pricing_Condition_Code__c = 'ZPAE';
			priReqItem5.Key_Combination_Code__c = 'A580';
			priReqItem5.Sold_To_Code__c = '5512342';
			priReqItem5.New_Valid_From__c = d+15;
			priReqItem5.New_Valid_To__c = d+30;
			insert priReqItem5;
			
		}
		catch(Exception e)
		{

		}		
	}
	static testMethod void BU_PricingRequestItem_DuplicateCheckTestMethod2()
	{
		try
		{
			Date d = Date.valueOf(System.NOW());			
			//Inserting Pricing Requests
			Pricing_Request__c pricingReq1 = new Pricing_Request__c();
			pricingReq1.BU__c = 'BI EMEA Surfaces';
			pricingReq1.Sales_Org_Code__c = 'A640';
			pricingReq1.Dist_Channel_Code__c = '10';
			pricingReq1.Division_Code__c = '02';
			pricingReq1.Pricing_Request_Type__c = 'Project Pricing';
			pricingReq1.Request_Approval_Status__c = 'Draft';
			pricingReq1.Customer_Specific__c = true;
			insert pricingReq1;

			//Inserting Pricing Request Items corresponding to the above request
			Pricing_Request_Item__c priReqItem1 = new Pricing_Request_Item__c();
			priReqItem1.Sales_Org_Code__c = 'A640';
			priReqItem1.Dist_Channel_Code__c = '10';
			priReqItem1.Division_Code__c = '02';
			priReqItem1.Pricing_Request_Type__c = 'Project';
			priReqItem1.Approval_Status__c = 'Draft';
			priReqItem1.Customer_Specific__c = false;
			priReqItem1.Pricing_Request__c = pricingReq1.Id;
			priReqItem1.Pricing_Condition_Code__c = 'ZD91';
			priReqItem1.Key_Combination_Code__c = 'A619';
			priReqItem1.Material_Code__c = 'D123456';
			priReqItem1.New_Valid_From__c = d;
			priReqItem1.New_Valid_To__c = d+30;
			insert priReqItem1;

			//Inserting Priicng Request Item which overlaps with the above Request Item
			Pricing_Request_Item__c priReqItem2 = new Pricing_Request_Item__c();
			priReqItem2.Sales_Org_Code__c = 'A640';
			priReqItem2.Dist_Channel_Code__c = '10';
			priReqItem2.Division_Code__c = '02';
			priReqItem2.Pricing_Request_Type__c = 'Project';
			priReqItem2.Approval_Status__c = 'Draft';
			priReqItem2.Customer_Specific__c = false;
			priReqItem2.Pricing_Request__c = pricingReq1.Id;
			priReqItem2.Pricing_Condition_Code__c = 'ZD91';
			priReqItem2.Key_Combination_Code__c = 'A619';
			priReqItem2.Material_Code__c = 'D123456';
			priReqItem2.New_Valid_From__c = d;
			priReqItem2.New_Valid_To__c = d+30;
			insert priReqItem2;
			
			priReqItem2.Net_Price_Status__c='Waiting for Net';
			update priReqItem2;
		}
		catch(Exception e)
		{

		}
	}
    
    static testMethod void BU_PricingRequestItem_DuplicateCheckTestMethod3()
	{
        try{
        Date d = Date.valueOf(System.NOW());
			//Inserting Pricing Requests
			
			Pricing_Request__c pricingReq1 = new Pricing_Request__c();
			pricingReq1.BU__c = 'BI EMEA Surfaces';
			pricingReq1.Sales_Org_Code__c = 'A640';
			pricingReq1.Dist_Channel_Code__c = '10';
			pricingReq1.Division_Code__c = '02';
			pricingReq1.Pricing_Request_Type__c = 'Permanent';
			pricingReq1.Request_Approval_Status__c = 'Draft';
			pricingReq1.Customer_Specific__c = true;
			insert pricingReq1;
			
        
        	Pricing_Request_Item__c priReqItem1 = new Pricing_Request_Item__c();
			priReqItem1.Sales_Org_Code__c = 'A640';
			priReqItem1.Dist_Channel_Code__c = '10';
			priReqItem1.Division_Code__c = '02';
			priReqItem1.Pricing_Request_Type__c = 'Permanent';
			priReqItem1.Approval_Status__c = 'Draft';
			priReqItem1.Customer_Specific__c = true;
			priReqItem1.Pricing_Request__c = pricingReq1.Id;
			priReqItem1.Pricing_Condition_Code__c = 'ZPSE';
			priReqItem1.Key_Combination_Code__c = 'A580';
			priReqItem1.Material_Code__c = 'D123456';
			priReqItem1.Sold_To_Code__c = '5512342';
			priReqItem1.PH1_Code__c = 'A6';
			priReqItem1.New_Valid_From__c = d+1;
			priReqItem1.New_Valid_To__c = d+10;
        	priReqItem1.New_Rate__c = '10';
			insert priReqItem1;
        
        	Pricing_Request__c pricingReq2 = new Pricing_Request__c();
			pricingReq2.BU__c = 'BI EMEA Surfaces';
			pricingReq2.Sales_Org_Code__c = 'A640';
			pricingReq2.Dist_Channel_Code__c = '10';
			pricingReq2.Division_Code__c = '02';
			pricingReq2.Pricing_Request_Type__c = 'Permanent';
			pricingReq2.Request_Approval_Status__c = 'Draft';
			pricingReq2.Customer_Specific__c = true;
			insert pricingReq2;
        
        	Pricing_Request_Item__c priReqItem2 = new Pricing_Request_Item__c();
			priReqItem2.Sales_Org_Code__c = 'A640';
			priReqItem2.Dist_Channel_Code__c = '10';
			priReqItem2.Division_Code__c = '02';
			priReqItem2.Pricing_Request_Type__c = 'Permanent';
			priReqItem2.Approval_Status__c = 'Draft';
			priReqItem2.Customer_Specific__c = true;
			priReqItem2.Pricing_Request__c = pricingReq2.Id;
			priReqItem2.Pricing_Condition_Code__c = 'ZPSE';
			priReqItem2.Key_Combination_Code__c = 'A580';
			priReqItem2.Material_Code__c = 'D123456';
			priReqItem2.Sold_To_Code__c = '5512342';
			priReqItem2.PH1_Code__c = 'A6';
			priReqItem2.New_Valid_From__c = d+2;
			priReqItem2.New_Valid_To__c = d+10;
        	priReqItem2.New_Rate__c = '10';
            insert priReqItem2;
        }
        catch(Exception e){
            
        }
    }
}