objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Specific__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies if the record is customer specific / Non Customer Specific</description>
        <label>Customer Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Default_Discount__c</fullName>
        <description>This field is used to store the default discount to be given for the line items in End User Rebate</description>
        <label>Default Discount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pricing_Request_Type__c</fullName>
        <label>Pricing Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Project Pricing</fullName>
                </value>
                <value>
                    <fullName>Pricing Task</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Reference Price</fullName>
                </value>
                <value>
                    <fullName>Floor Price</fullName>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Pricing Request</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Net Floor</fullName>
                </value>
                <value>
                    <fullName>Net Reference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <label>Project Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Name__c</fullName>
        <label>Project Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Price</label>
        <referenceTo>Project_Price__c</referenceTo>
        <relationshipLabel>Pricing Requests</relationshipLabel>
        <relationshipName>Pricing_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Reason__c</fullName>
        <label>Request Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Massive</fullName>
                </value>
                <value>
                    <fullName>Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Non Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Mass Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spot_Type__c</fullName>
        <label>Pricing Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spot Price</fullName>
                </value>
                <value>
                    <fullName>Rebate Agreement</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Other Pricing Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Price__c.object
<CustomObject>
    <fields>
        <fullName>Default_Discount__c</fullName>
        <label>Default Discount</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Id__c</fullName>
        <displayFormat>{0000000000}</displayFormat>
        <label>Project Id</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>Holds the Project status</description>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Volume__c</fullName>
        <label>Project Volume</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isApproved</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Price</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Prices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/ProjectDeletionOnRequestDeletion_UT.cls
@isTest
public class ProjectDeletionOnRequestDeletion_UT
{
    static testMethod void ProjectDeletionOnRequestDeletion()
    {
    
    Project_Price__c P1= new Project_Price__c();
   
        P1.Name='P1';
        P1.Valid_From__c=system.today();
        P1.Valid_To__c=system.today()+15;       
        P1.Project_Volume__c='100';
        P1.Default_Discount__c='10';
        p1.isApproved__c=false;
        p1.Project_status__c='Draft';       
        insert P1;    
        
        Project_Price__c P2= new Project_Price__c();
        P2.Name='P2';
        P2.Valid_From__c=system.today();
        P2.Valid_To__c=system.today()+15;       
        P2.Project_Volume__c='100';
        P2.Default_Discount__c='10';
        p2.isApproved__c=true;
        p2.Project_status__c='Draft';
        insert P2;
                
        Pricing_Request__c R1= new Pricing_Request__c();
        R1.BU__c='Test';
        R1.Request_Name__c='R1 For P1';
        R1.Request_Approval_Status__c='Draft';
        R1.Request_Reason__c='New Project';
        R1.Request_Type__c = 'Customer Specific';
        R1.Pricing_Request_Type__c = 'Project Pricing';
        R1.Spot_Type__c=null;
        R1.Customer_Specific__c = true;     
        R1.Project_Price__c=P1.id;
        R1.Project_Id__c=P1.Project_Id__c;
        R1.Project_Name__c=P1.Name;
        R1.Sales_Org_Code__c='A250';
        insert R1;
        
        Pricing_Request__c R2= new Pricing_Request__c();
        R2.BU__c='Test';
        R2.Request_Name__c='R2 For P2';
        R2.Request_Approval_Status__c='Draft';
        R2.Request_Reason__c='New Project';
        R2.Request_Type__c = 'Customer Specific';
        R2.Pricing_Request_Type__c = 'Project Pricing';
        R2.Spot_Type__c=null;
        R2.Customer_Specific__c = true;     
        R2.Project_Price__c=P2.id;
        R2.Project_Id__c=P2.Project_Id__c;
        R2.Project_Name__c=P2.Name;
        R2.Sales_Org_Code__c='A250';
        insert R2;
       
       
       delete R1;
        delete R2;      
    }
}