objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approver1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the First Approver who should approve the record</description>
        <label>Non-Object 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Second Approver who should approve the record</description>
        <label>Non-Object 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Third Approver who should approve the record</description>
        <label>Non-Object 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Fourth Approver who should approve the record</description>
        <label>Non-Object 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Approver5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the Fifth Approver who should approve the record</description>
        <label>Final Approval</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Level__c</fullName>
        <description>Identifies approval level</description>
        <label>Current Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dist_Channel_Code__c</fullName>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request_Type__c</fullName>
        <label>Pricing Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Project Pricing</fullName>
                </value>
                <value>
                    <fullName>Pricing Task</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Reference Price</fullName>
                </value>
                <value>
                    <fullName>Floor Price</fullName>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Pricing Request</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Net Floor</fullName>
                </value>
                <value>
                    <fullName>Net Reference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Massive</fullName>
                </value>
                <value>
                    <fullName>Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Non Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Mass Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SoldTo_Code__c</fullName>
        <label>SoldTo Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>E_Pass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems - found in MyAccess &amp; in the User&apos;s NAB Entry</description>
        <label>E-Pass ID</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</inlineHelpText>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED KINGDOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/PAReassign_UT.cls
@isTest
public class PAReassign_UT
{        
   /* static testMethod void reassignTestMethod(){
    
    Profile p1 =[SELECT Id FROM Profile where name='Price Approval-BU Admin'];
    //[27122016] Merge&Spin: Updated External ERP Id to Dummy Value 
    User u1 = new User(Alias='pcopp', Email='ambili_vinay@infosys.com', 
                    User_Country__c='UNITED KINGDOM',E_Pass_ID__c='rr9847',
                    External_ERP_ID__c='DUMMYTest1',profileid = p1.id,
                    Username='pa_werner1@jhhgtestinfosys.com.test2',
                    LastName='Coppens', CommunityNickname='acv',
                    TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
    insert u1;
    System.runAs(u1){
    Pricing_Request__c pricingRequest1 = new Pricing_Request__c();
    pricingRequest1.Pricing_Request_Type__c = 'Permanent';
    pricingRequest1.Request_Type__c = 'Customer Specific';
    pricingRequest1.BU__c = 'BI-EMEA';
    pricingRequest1.Sales_Org_Code__c = 'A640';
    pricingRequest1.Dist_Channel_Code__c = '10';
    pricingRequest1.Division_Code__c = '02';
    pricingRequest1.SoldTo_Code__c = 'T001';
    pricingRequest1.Current_Level__c='1';
    
    insert pricingRequest1;
    
    Pricing_Request__c pricingRequest2 = new Pricing_Request__c();
    pricingRequest2.Pricing_Request_Type__c = 'Permanent';
    pricingRequest2.Request_Type__c = 'Customer Specific';
    pricingRequest2.BU__c = 'BI';
    pricingRequest2.Sales_Org_Code__c = 'A640';
    pricingRequest2.Dist_Channel_Code__c = '10';
    pricingRequest2.Division_Code__c = '02';
    pricingRequest2.SoldTo_Code__c = 'T001';
    pricingRequest2.Current_Level__c='2';
    
    insert pricingRequest2;
    
    Pricing_Request__c pricingRequest3 = new Pricing_Request__c();
    pricingRequest3.Pricing_Request_Type__c = 'Permanent';
    pricingRequest3.Request_Type__c = 'Customer Specific';
    pricingRequest3.BU__c = 'BI';
    pricingRequest3.Sales_Org_Code__c = 'A640';
    pricingRequest3.Dist_Channel_Code__c = '10';
    pricingRequest3.Division_Code__c = '02';
    pricingRequest3.SoldTo_Code__c = 'T001';
    pricingRequest3.Current_Level__c='3';
    
    insert pricingRequest3;

    Pricing_Request__c pricingRequest4 = new Pricing_Request__c();
    pricingRequest4.Pricing_Request_Type__c = 'Permanent';
    pricingRequest4.Request_Type__c = 'Customer Specific';
    pricingRequest4.BU__c = 'BI';
    pricingRequest4.Sales_Org_Code__c = 'A640';
    pricingRequest4.Dist_Channel_Code__c = '10';
    pricingRequest4.Division_Code__c = '02';
    pricingRequest4.SoldTo_Code__c = 'T001';
    pricingRequest4.Current_Level__c='4';
    
    insert pricingRequest4;

    Pricing_Request__c pricingRequest5 = new Pricing_Request__c();
    pricingRequest5.Pricing_Request_Type__c = 'Permanent';
    pricingRequest5.Request_Type__c = 'Customer Specific';
    pricingRequest5.BU__c = 'BI';
    pricingRequest5.Sales_Org_Code__c = 'A640';
    pricingRequest5.Dist_Channel_Code__c = '10';
    pricingRequest5.Division_Code__c = '02';
    pricingRequest5.SoldTo_Code__c = 'T001';
    pricingRequest5.Current_Level__c='5';
        pricingRequest5.Approver1__c = u1.id;
            pricingRequest5.Approver2__c = u1.id;
            pricingRequest5.Approver3__c = u1.id;
            pricingRequest5.Approver4__c = u1.id;
            pricingRequest5.Approver5__c = u1.id;
    
    insert pricingRequest5;
    System.debug('pr5 '+pricingRequest5);
       // Test.StartTest();
    Approval.ProcessSubmitRequest req1 = 
            new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(pricingRequest1.id);
        req1.setSubmitterId(u1.id);
       // req1.setSkipEntryCriteria(true);
        Approval.ProcessResult result = Approval.process(req1);
        System.debug('ProcessResult&& '+result);
        List<Id> newWorkItemIds = result.getNewWorkitemIds();
      /*  Approval.ProcessWorkitemRequest req2 = 
            new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setWorkitemId(newWorkItemIds.get(0));
        req2.setNextApproverIds(new Id[] {u1.id,u1.id,u1.id,u1.id,u1.id});
        Approval.ProcessResult result2 =  Approval.process(req2);*/
   /* List<ProcessInstanceWorkItem> processesList = new List<ProcessInstanceWorkItem>();
    processesList = [SELECT p.ProcessInstanceId, p.OriginalActorId, p.Id, p.ActorId, processinstance.targetobjectid From ProcessInstanceWorkitem p where processinstance.targetobjectid=:pricingRequest5.id];
     system.debug('inside test 1 '+ processesList);
     
     
    PAReassign.reAssign(pricingRequest1.id,'',u1.id);
    PAReassign.reAssign(pricingRequest2.id,'',u1.id);  
    PAReassign.reAssign(pricingRequest3.id,'',u1.id);
    PAReassign.reAssign(pricingRequest4.id,'',u1.id);
    PAReassign.reAssign(pricingRequest5.id,'',u1.id);
    
  /*  try{  
    PAReassign.recallRequest(pricingRequest5.id,'abc');
    }
    catch(Exception e)
    {} */
  //  Test.StopTest();
  /*  }
    } */
    //Monika Added
    static testMethod void reassignTestMethod2(){
    
    Profile p1 =[SELECT Id FROM Profile where name='Price Approval-BU Admin'];
    
    User u1 = new User(Alias='pcopp', Email='ambili_vinay@infosys.com', 
                    User_Country__c='UNITED KINGDOM',E_Pass_ID__c='rr9847',
                    External_ERP_ID__c='DUMMYTest2',profileid = p1.id,
                    Username='pa_werner1@jhhgtestinfosys.com.test2',
                    LastName='Coppens', CommunityNickname='acv',
                    TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
    insert u1;
 
    System.runAs(u1){
    Pricing_Request__c pricingRequest1 = new Pricing_Request__c();
    pricingRequest1.Pricing_Request_Type__c = 'Permanent';
    pricingRequest1.Request_Type__c = 'Customer Specific';
    pricingRequest1.BU__c = 'BI';
    pricingRequest1.Sales_Org_Code__c = 'A640';
    pricingRequest1.Dist_Channel_Code__c = '10';
    pricingRequest1.Division_Code__c = '02';
    pricingRequest1.SoldTo_Code__c = 'T001';
    pricingRequest1.Current_Level__c='1';
    
    insert pricingRequest1;
    
    Pricing_Request__c pricingRequest2 = new Pricing_Request__c();
    pricingRequest2.Pricing_Request_Type__c = 'Permanent';
    pricingRequest2.Request_Type__c = 'Customer Specific';
    pricingRequest2.BU__c = 'BI';
    pricingRequest2.Sales_Org_Code__c = 'A640';
    pricingRequest2.Dist_Channel_Code__c = '10';
    pricingRequest2.Division_Code__c = '02';
    pricingRequest2.SoldTo_Code__c = 'T001';
    pricingRequest2.Current_Level__c='2';
    
    insert pricingRequest2;
    
    Pricing_Request__c pricingRequest3 = new Pricing_Request__c();
    pricingRequest3.Pricing_Request_Type__c = 'Permanent';
    pricingRequest3.Request_Type__c = 'Customer Specific';
    pricingRequest3.BU__c = 'BI';
    pricingRequest3.Sales_Org_Code__c = 'A640';
    pricingRequest3.Dist_Channel_Code__c = '10';
    pricingRequest3.Division_Code__c = '02';
    pricingRequest3.SoldTo_Code__c = 'T001';
    pricingRequest3.Current_Level__c='3';
    
    insert pricingRequest3;

    Pricing_Request__c pricingRequest4 = new Pricing_Request__c();
    pricingRequest4.Pricing_Request_Type__c = 'Permanent';
    pricingRequest4.Request_Type__c = 'Customer Specific';
    pricingRequest4.BU__c = 'BI';
    pricingRequest4.Sales_Org_Code__c = 'A640';
    pricingRequest4.Dist_Channel_Code__c = '10';
    pricingRequest4.Division_Code__c = '02';
    pricingRequest4.SoldTo_Code__c = 'T001';
    pricingRequest4.Current_Level__c='4';
    
    insert pricingRequest4;

    Pricing_Request__c pricingRequest5 = new Pricing_Request__c();
    pricingRequest5.Pricing_Request_Type__c = 'Permanent';
    pricingRequest5.Request_Type__c = 'Customer Specific';
    pricingRequest5.BU__c = 'BI';
    pricingRequest5.Sales_Org_Code__c = 'A640';
    pricingRequest5.Dist_Channel_Code__c = '10';
    pricingRequest5.Division_Code__c = '02';
    pricingRequest5.SoldTo_Code__c = 'T001';
    pricingRequest5.Current_Level__c='5';
    
    insert pricingRequest5;
        
    
    List<ProcessInstanceWorkItem> processesList = new List<ProcessInstanceWorkItem>();
    processesList = [SELECT p.ProcessInstanceId, p.OriginalActorId, p.Id, p.ActorId, processinstance.targetobjectid From ProcessInstanceWorkitem p where processinstance.targetobjectid=:pricingRequest5.id];
        system.debug('inside test 2 '+ processesList);
    Test.StartTest();
    
    
    PAReassign.reAssign(pricingRequest1.id,'',u1.id);
    PAReassign.reAssign(pricingRequest2.id,'',u1.id);  
    PAReassign.reAssign(pricingRequest3.id,'',u1.id);
    PAReassign.reAssign(pricingRequest4.id,'',u1.id);
    PAReassign.reAssign(pricingRequest5.id,'',u1.id);
    try{  
    PAReassign.recallRequest(pricingRequest5.id,'');
    }
    catch(Exception e)
    {}
    Test.StopTest();
    }
    }
    //Added by Sumida on 13/09/24 to increase code coverage
    static testMethod void reassignTestMethod1(){
        Profile p1 =[SELECT Id FROM Profile where name='Price Approval-BU Admin'];
        User u1 = new User(Alias='pcopp', Email='ambili_vinay@infosys.com', 
                           User_Country__c='UNITED KINGDOM',E_Pass_ID__c='rr9847',
                           External_ERP_ID__c='DUMMYTest2',profileid = p1.id,
                           Username='pa_werner1@jhhgtestinfosys.com.test2',
                           LastName='Coppens', CommunityNickname='acv',
                           TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert u1;
        
        System.runAs(u1){
            Pricing_Request__c pricingRequest1 = new Pricing_Request__c();
            pricingRequest1.Pricing_Request_Type__c = 'Permanent';
            pricingRequest1.Request_Type__c = 'Customer Specific';
            pricingRequest1.BU__c = 'BI';
            pricingRequest1.Sales_Org_Code__c = 'A640';
            pricingRequest1.Dist_Channel_Code__c = '10';
            pricingRequest1.Division_Code__c = '02';
            pricingRequest1.SoldTo_Code__c = 'T001';
            pricingRequest1.Current_Level__c='1';
            insert pricingRequest1;
            
            Test.StartTest();
            try{ 
                PAReassign.reAssign('jhj-jnsj','',u1.id);
                PAReassign.reAssign1(pricingRequest1.id,u1.id,u1.id);
            }
            catch(Exception e)
            {}
            Test.StopTest();
        }
    }
}