objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the User to whom the pricing Task is Assigned</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Specific__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies if the record is customer specific / Non Customer Specific</description>
        <label>Customer Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <description>Due Date assigned for the CSR to complete the Task</description>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Pricing_Request_Type__c</fullName>
        <label>Pricing Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Project Pricing</fullName>
                </value>
                <value>
                    <fullName>Pricing Task</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Reference Price</fullName>
                </value>
                <value>
                    <fullName>Floor Price</fullName>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Pricing Request</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Net Floor</fullName>
                </value>
                <value>
                    <fullName>Net Reference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Reason__c</fullName>
        <label>Request Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Massive</fullName>
                </value>
                <value>
                    <fullName>Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Non Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Mass Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spot_Type__c</fullName>
        <label>Pricing Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spot Price</fullName>
                </value>
                <value>
                    <fullName>Rebate Agreement</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Other Pricing Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Task_Subject__c</fullName>
        <label>Task Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Pricing_Task</fullName>
        <active>true</active>
        <description>Used to create Pricing Task for Project Prices and One of Sales</description>
        <label>Pricing Task</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/Task_CreationAfterApproval_UT.cls
@isTest
public class Task_CreationAfterApproval_UT
{
    
  static testMethod void TaskCreationAfterApproval()
  {
    //   public static final Id Task_Pricing_Task_RTYPE = Rtype.getIdByDevName('Task','Pricing_Task');
       Profile p =[SELECT Id FROM Profile where name='Price Approval-Price requester'];
      /* UserRole ur = new UserRole();
       ur.developerName ='BI_EMEA_D630';
       insert ur; */
        // 12/30/2016 - Merge&Spin -Updated the test  class to update the insert of UserRole and User
       UserRole r= TestUserUtil.createTestUserRole('BI-EMEA-Surfaces');
        User u1 = TestUserUtil.createTestUser(r.id, p.id, 'test fName', 'test lName');     
        insert u1;
       system.runAs(u1){
       
        Pricing_Request__c R1= new Pricing_Request__c();
        R1.Request_Name__c='R1 For P1';
        R1.Request_Approval_Status__c='Submitted';
        R1.Request_Reason__c='New Project';
        R1.Request_Type__c = 'Customer Specific';
        R1.Pricing_Request_Type__c = 'Pricing Task';
        R1.Spot_Type__c=null;
        R1.Customer_Specific__c = true; 
        R1.Sales_Org_Code__c='A200';
        R1.BU__c='AP';
        R1.Assigned_To__c=u1.id;   
        R1.Due_Date__c=system.today();  
        R1.Task_Subject__c='TestClassforTaskCreationAfterApproval';
       
        insert R1;
        
        R1.Request_Approval_Status__c='Approved';
        upsert R1;
        
   }      
  }
}