objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Level__c</fullName>
        <description>Identifies approval level</description>
        <label>Current Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Pricing_Request_Type__c</fullName>
        <label>Pricing Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Project Pricing</fullName>
                </value>
                <value>
                    <fullName>Pricing Task</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Reference Price</fullName>
                </value>
                <value>
                    <fullName>Floor Price</fullName>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Pricing Request</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Net Floor</fullName>
                </value>
                <value>
                    <fullName>Net Reference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Reason__c</fullName>
        <label>Request Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Massive</fullName>
                </value>
                <value>
                    <fullName>Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Non Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Mass Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Spot_Type__c</fullName>
        <label>Pricing Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spot Price</fullName>
                </value>
                <value>
                    <fullName>Rebate Agreement</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Other Pricing Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/batchDeletionOfAbandonedRequest_UT.cls
@isTest
public class batchDeletionOfAbandonedRequest_UT{
    static testMethod void batchDeletionOfAbandonedRequestTestMethod() {
                    
        Pricing_Request__c pr = new Pricing_Request__c();
      
      /*  Date myDate = date.newinstance(2014,6,1);
        pr.Request_Approval_Status__c = 'Abandoned';
        pr.Request_Type__c = 'Massive';
        pr.Pricing_Request_Type__c = 'Pricing Task';
        pr.Spot_Type__c = 'Rebate Agreement';
        pr.Current_Level__c = '1';
        pr.BU__c = 'Test Business';
        pr.Request_Reason__c = 'test';
        
        */
        
        //Commented bcz, i tried new staticResource by attaching 'BatchDeletionCSV.csv' file into 'BatchDeletionTest'
        
        List<sObject> ls = Test.loadData(Pricing_Request__c.sObjectType, 'batchDeletionTest');
        Pricing_Request__c req = (Pricing_Request__c)ls[0];
        
   //     pr.CreatedDate = {$Resource.TestdataTestclass};
       //pr.Request_Approval_Status__c = 'Submitted';
   //     upsert pr;
   		 
     // pr.Request_Approval_Status__c = 'Abandoned';
        
       /* list<sObject> c=new list<Pricing_Request__c>();
     c.add(pr);
     upsert c;*/
     //test.startTest();
     try{ 
       Test.startTest();  
        batchDeletionOfAbandonedRequest bc = new batchDeletionOfAbandonedRequest();
        database.executeBatch(bc,200);
        //Database.executeBatch(bc);  
        bc.startQuery = 'SELect id FROM Pricing_Request__c WHERE Request_Approval_Status__c=\'Abandoned\' and CreatedDate <LAST_N_DAYS:29';
        test.stopTest();
           }catch(Exception e){} 
      
     }

}