objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Price</label>
        <referenceTo>Project_Price__c</referenceTo>
        <relationshipLabel>Pricing Requests</relationshipLabel>
        <relationshipName>Pricing_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Price__c.object
<CustomObject>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>Holds the Project status</description>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isApproved</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Price</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Prices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/batchProjectStatusChange_UT.cls
@isTest 
//(SeeAllData=true)
private class batchProjectStatusChange_UT {  
    static testMethod void batchProjectStatusChange() {
        list<String> h=new list<String>();   
        String profileId=[select Id,name from Profile where name='XXX_Deactivated User' limit 1].Id;   
        user testuser=new user(firstname='abc',lastname='xyz',email='abc@xyz.com',username='abc_cba_salesforce_DuPont-123456@xyz.com',alias='abc',CommunityNickname='Test',profileId=profileId,EmailEncodingKey='UTF-8',LocaleSidKey='en_US',LanguageLocaleKey='en_US',TimeZoneSidKey='Asia/Kolkata'); 
          insert testuser;   h.add('prachi');     
          Project_Price__c c=new Project_Price__c();    
          c.Valid_To__c=system.today()-1;    
          c.Project_Status__c='Draft';    
          c.isApproved__c=true;    
          c.ownerId=testuser.Id;    
          insert c; 
          System.debug('Project Price'+c);     
          Pricing_Request__c s=new Pricing_Request__c();      
          s.BU__c = 'BI EMEA Surfaces';
          s.Project_Price__c=c.id;       
          insert s;       
          //pAUtil m=new PAUtil();        
          batchProjectStatusChange bc=new batchProjectStatusChange();              
          Database.executeBatch(bc, 200);               
          Test.startTest();   
          }
    }