objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identifies the User to whom the pricing Task is Assigned</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Pricing_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Discount__c</fullName>
        <description>This field is used to store the default discount to be given for the line items in End User Rebate</description>
        <label>Default Discount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project_Price__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project Price</label>
        <referenceTo>Project_Price__c</referenceTo>
        <relationshipLabel>Pricing Requests</relationshipLabel>
        <relationshipName>Pricing_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Project_Price__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Default_Discount__c</fullName>
        <label>Default Discount</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Status__c</fullName>
        <description>Holds the Project status</description>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Volume__c</fullName>
        <label>Project Volume</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_From__c</fullName>
        <label>Valid From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Valid_To__c</fullName>
        <label>Valid To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>isApproved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isApproved</label>
        <type>Checkbox</type>
    </fields>
    <label>Project Price</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Prices</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>E_Pass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems - found in MyAccess &amp; in the User&apos;s NAB Entry</description>
        <label>E-Pass ID</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</inlineHelpText>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED KINGDOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EmailNotificationOnTaskComplete_UT.cls
/*
Date : 29/12/2016
Change : Merge & Spin- Updated the test  class to update the insert of UserRole and User.
*/
@isTest 
private class EmailNotificationOnTaskComplete_UT {
    
   
    static testMethod void EmailNotificationOnTaskCompleteTestMethod() {
       //Start: Updated as a part of Merge & Spin to the change the UserRole name.
       Profile p =[SELECT Id FROM Profile where name='Price Approval-Price Requester'];
       /*
       UserRole r=[SELECT Id FROM UserRole WHERE developerName='BI_EMEA_Surfaces'];
    
       User u1= new User(Firstname='test2test2',Alias='Hill1', Email='test@test.com', 
                         User_Country__c='UNITED KINGDOM',E_Pass_ID__c='qw3214',External_ERP_ID__c='345678',profileid = p.id,
                         Username='testingtset2645@dupont.com.uttest2',UserRoleId=r.id, LastName='Hill', CommunityNickname='mm1', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
                         
                         insert u1;
                    
       system.debug('ProfileId '+p.id);
              system.debug('User '+r.id);
       */
       UserRole Ur = TestUserUtil.createTestUserRole('BI-EMEA-Surfaces');
       insert Ur;
       User usr = TestUserUtil.createTestUser(Ur.Id,p.Id,'User FirstName','User LastName');
       insert usr;
       //End: Updated as a part of Merge & Spin to the change the UserRole name.
       system.runAs(usr){
           
             
       List<Id> projId =new List<Id>();
       
       Project_Price__c P1= new Project_Price__c();   
       P1.Name='P1';
       P1.Valid_From__c=system.today();
       P1.Valid_To__c=system.today()+15;        
       P1.Project_Volume__c='100';
       P1.Default_Discount__c='10';
       p1.isApproved__c=false;
       p1.Project_status__c='Approved';
       p1.Assigned_To__c=usr.id; 
                      
       insert P1;     
    
       Task t = new Task();   
       t.whatId=p1.id; 
       t.Status='inprogress';       
       insert t;
       t.Status='completed';
       upsert t;        
       
       
 }
       }
 static testMethod void EmailNotificationOnTaskCompleteTestMethod1() {
 
       //Start: Updated as a part of Merge & Spin to the change the UserRole name.
       Profile p =[SELECT Id FROM Profile where name='Price Approval-Price Requester'];
       /*
       UserRole r=[SELECT Id FROM UserRole WHERE developerName='BI_EMEA_Surfaces'];
      // insert r;
       User u1= new User(Firstname='test2test2',Alias='Hill', Email='test@test.com', 
                         User_Country__c='UNITED KINGDOM',E_Pass_ID__c='1234qw',External_ERP_ID__c='234567',profileid = p.id,
                         Username='testingtset2676@dupont.com.uttest2',UserRoleId=r.id, LastName='Hill', CommunityNickname='mm', TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
                         
                         insert u1;
       */
       UserRole Ur = TestUserUtil.createTestUserRole('BI-EMEA-Surfaces');
       insert Ur;
       User usr = TestUserUtil.createTestUser(Ur.Id,p.Id,'User FirstName','User LastName');
       insert usr;
        //End: Updated as a part of Merge & Spin to the change the UserRole name.
       system.runAs(usr){
           
             
            
       
        List<Id> pricingId =new List<Id>();
        Pricing_Request__c v=new Pricing_Request__c();
        v.BU__c='p1';
        insert v;
        
        Task t1 = new Task();     
        t1.whatId=v.id;
        t1.Status='inprogress';     
        insert t1;
       t1.Status='Completed';     
        upsert t1;
 }
       }
 }