objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <description>Identifies the Business Unit</description>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Specific__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies if the record is customer specific / Non Customer Specific</description>
        <label>Customer Specific</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Dist_Channel_Code__c</fullName>
        <label>Dist. Channel Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Division_Code__c</fullName>
        <label>Division Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Request_Type__c</fullName>
        <label>Pricing Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Project Pricing</fullName>
                </value>
                <value>
                    <fullName>Pricing Task</fullName>
                </value>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Reference Price</fullName>
                </value>
                <value>
                    <fullName>Floor Price</fullName>
                </value>
                <value>
                    <fullName>Permanent</fullName>
                </value>
                <value>
                    <fullName>Pricing Request</fullName>
                </value>
                <value>
                    <fullName>Floor</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Net Floor</fullName>
                </value>
                <value>
                    <fullName>Net Reference</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Reason__c</fullName>
        <label>Request Reason</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Request_Type__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Import</fullName>
                </value>
                <value>
                    <fullName>Massive</fullName>
                </value>
                <value>
                    <fullName>Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Non Customer Specific</fullName>
                </value>
                <value>
                    <fullName>Mass Import</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SAP_Application_Id__c</fullName>
        <label>SAP Application Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAP_Client_Id__c</fullName>
        <label>SAP Client Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SoldTo_Code__c</fullName>
        <label>SoldTo Code</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sold_To__c</fullName>
        <label>Sold To</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Spot_Type__c</fullName>
        <label>Pricing Task Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Spot Price</fullName>
                </value>
                <value>
                    <fullName>Rebate Agreement</fullName>
                </value>
                <value>
                    <fullName>Free of Charge</fullName>
                </value>
                <value>
                    <fullName>Display</fullName>
                </value>
                <value>
                    <fullName>Other Pricing Task</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>E_Pass_ID__c</fullName>
        <description>Positive identification of individuals accessing DuPont computer systems - found in MyAccess &amp; in the User&apos;s NAB Entry</description>
        <label>E-Pass ID</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>External_ERP_ID__c</fullName>
        <description>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</description>
        <externalId>true</externalId>
        <inlineHelpText>SAP Partner Code / User ID (sales rep, CSR, etc.) of this user and is the unique record identifier for this person from SAP.</inlineHelpText>
        <label>External ERP ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User_Country__c</fullName>
        <description>Primary country this User belongs to</description>
        <label>User Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AFGHANISTAN</fullName>
                </value>
                <value>
                    <fullName>ALAND ISLANDS</fullName>
                </value>
                <value>
                    <fullName>ALBANIA</fullName>
                </value>
                <value>
                    <fullName>ALGERIA</fullName>
                </value>
                <value>
                    <fullName>AMERICAN SAMOA</fullName>
                </value>
                <value>
                    <fullName>ANDORRA</fullName>
                </value>
                <value>
                    <fullName>ANGOLA</fullName>
                </value>
                <value>
                    <fullName>ANGUILLA</fullName>
                </value>
                <value>
                    <fullName>ANTARCTICA</fullName>
                </value>
                <value>
                    <fullName>ANTIGUA AND BARBUDA</fullName>
                </value>
                <value>
                    <fullName>ARGENTINA</fullName>
                </value>
                <value>
                    <fullName>ARMENIA</fullName>
                </value>
                <value>
                    <fullName>ARUBA</fullName>
                </value>
                <value>
                    <fullName>AUSTRALIA</fullName>
                </value>
                <value>
                    <fullName>AUSTRIA</fullName>
                </value>
                <value>
                    <fullName>AZERBAIJAN</fullName>
                </value>
                <value>
                    <fullName>BAHAMAS</fullName>
                </value>
                <value>
                    <fullName>BAHRAIN</fullName>
                </value>
                <value>
                    <fullName>BANGLADESH</fullName>
                </value>
                <value>
                    <fullName>BARBADOS</fullName>
                </value>
                <value>
                    <fullName>BELARUS</fullName>
                </value>
                <value>
                    <fullName>BELGIUM</fullName>
                </value>
                <value>
                    <fullName>BELIZE</fullName>
                </value>
                <value>
                    <fullName>BENIN</fullName>
                </value>
                <value>
                    <fullName>BERMUDA</fullName>
                </value>
                <value>
                    <fullName>BHUTAN</fullName>
                </value>
                <value>
                    <fullName>BOLIVIA</fullName>
                </value>
                <value>
                    <fullName>BOSNIA AND HERZEGOVINA</fullName>
                </value>
                <value>
                    <fullName>BOTSWANA</fullName>
                </value>
                <value>
                    <fullName>BOUVET ISLAND</fullName>
                </value>
                <value>
                    <fullName>UNITED KINGDOM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/OverRideSystemAdmin_UT.cls
/*
 * Name      :   OverRideSystemAdmin_UT
 * Description  :   This is the test class for OverRideSystemAdmin
 * Author      :   Infosys Limited
 * Created Date :   
 Date : 29/12/2016
 Change : Merge & Spin- Updated the test  class to update the insert of UserRole and User.
 * Version    Modified Date    Modified By   Modification
 * ------------------------------------------------------------------------------
 */
@isTest
private class OverRideSystemAdmin_UT
{
    
    static testMethod void ctrlPAMainTestMethod()
    {
        //Start: Updated as a part of Merge & Spin to the change the UserRole name.
        Profile p1 =[SELECT Id FROM Profile where name='System Administrator'];
        Profile p2 =[SELECT Id FROM Profile where name='Price Approval-BU Admin'];
        /*
        UserRole r=[SELECT Id FROM UserRole WHERE developerName='BI_EMEA_Surfaces'];
        // 27122016 - Merge&Spin - Updated External ERP Id to Dummy Value   
        //sales Admin Permission Set
        User u1 = new User(Alias='pcopp', Email='test_user@dupont.com', 
                         User_Country__c='UNITED KINGDOM',E_Pass_ID__c='rr9847',
                         External_ERP_ID__c='DummyTest1',UserRoleId=r.id,profileid = p1.id,
                         Username='pa_werner1@jhhgtestinfosys.com.test2',
                         LastName='Coppens', CommunityNickname='acv',
                         TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert u1;
         // 27122016 - Merge&Spin - Updated External ERP Id to Dummy Value
        User u2 = new User(Alias='pcopp2', Email='test_user2@dupont.com', 
                         User_Country__c='UNITED KINGDOM2',E_Pass_ID__c='rr1235',
                         External_ERP_ID__c='DummyTest2',UserRoleId=r.id,profileid = p2.id,
                         Username='pa_werner21@jhhgtestinfosys.com.test2',
                         LastName='Coppens2', CommunityNickname='acv2',
                         TimeZoneSidKey='America/Los_Angeles', LocaleSidKey='en_US', EmailEncodingKey='UTF-8', LanguageLocaleKey='en_US');
        insert u2;
        */
       UserRole Ur = TestUserUtil.createTestUserRole('BI-EMEA-Surfaces');
       insert Ur;
       User usr1 = TestUserUtil.createTestUser(Ur.Id,p1.Id,'User1 FirstName','User1 LastName');
       usr1.External_ERP_ID__c='DummyTest1';
       insert usr1;
       User usr2 = TestUserUtil.createTestUser(Ur.Id,p2.Id,'User2 FirstName','User2 LastName');
       usr2.External_ERP_ID__c='DummyTest2';
       insert usr2;
       //End: Updated as a part of Merge & Spin to the change the UserRole name.
        system.runAs(usr1)
        {
            Pricing_Request__c prList = new Pricing_Request__c();
            prList = new Pricing_Request__c(Sold_To__c='Customer1',SoldTo_Code__c='5512345',Sales_Org_Code__c='A640',
                                    SAP_Client_Id__c='510',SAP_Application_Id__c='V',Request_Type__c='Customer Specific',Request_Reason__c='test;test1',
                                    Request_Name__c='test123',Pricing_Request_Type__c='Pricing Task',Division_Code__c='02',
                                    Dist_Channel_Code__c='10',Customer_Specific__c=true,BU__c='BI EMEA SURFACES',
                                    Request_Approval_Status__c='Draft',Spot_Type__c='not null');
             
            insert prList;
            Apexpages.StandardController stdController = new Apexpages.StandardController(prList);
        
            OverRideSystemAdmin sysAd = new OverRideSystemAdmin(stdController);
            sysAd.route();
        }
        system.runAs(usr2)
        {
            Pricing_Request__c prList = new Pricing_Request__c();
            prList = new Pricing_Request__c(Sold_To__c='Customer1',SoldTo_Code__c='5512345',Sales_Org_Code__c='A640',
                                    SAP_Client_Id__c='510',SAP_Application_Id__c='V',Request_Type__c='Customer Specific',Request_Reason__c='test;test1',
                                    Request_Name__c='test123',Pricing_Request_Type__c='Pricing Task',Division_Code__c='02',
                                    Dist_Channel_Code__c='10',Customer_Specific__c=true,BU__c='BI EMEA SURFACES',
                                    Request_Approval_Status__c='Draft',Spot_Type__c='not null');
             
            insert prList;
            Apexpages.StandardController stdController = new Apexpages.StandardController(prList);
        
            OverRideSystemAdmin sysAd = new OverRideSystemAdmin(stdController);
            sysAd.route();
            sysAd.routeToEdit();
        }
    }
}