objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Last_Modified_By__c</fullName>
        <formula>LastModifiedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Modified</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/batchClassForPRStatusAbandon.cls
/************************************************************************************************************
<HL20140902>
 Created By    :   Hema latha
 Description   :   To identify the Pricing Requests pending in Draft Recalled and Rejected status for 20 days.
***********************************************************************************************************************/
global class  batchClassForPRStatusAbandon implements Database.Batchable<sObject>{

    
    public Date vt=System.today();
    public string startQuery = 'SELect id,Request_Approval_Status__c FROM Pricing_Request__c WHERE (Request_Approval_Status__c=\'Draft\' or Request_Approval_Status__c=\'Rejected\' or Request_Approval_Status__c=\'Recalled\')  and Last_Modified_By__c<LAST_N_DAYS:60';
    global Database.QueryLocator start(Database.BatchableContext BC)
    { 
        return Database.getQueryLocator(startQuery);    
    }
    global void execute(Database.BatchableContext BC, List<sObject> sList)
    {
        List<Pricing_Request__c> tempList = new List<Pricing_Request__c>();
        List<Pricing_Request__c> prList=(List<Pricing_Request__c>)sList; 
        
        if(prList.size()>0)
        {
          for(Pricing_Request__c h:prList)
          {
           
            h.Request_Approval_Status__c='Abandoned';
            tempList.add(h);
          }
          update tempList;
        }
    }
    global void finish(Database.BatchableContext BC)
    {
    } 

}