objects/Pricing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Request_Approval_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Waiting for Net Price</fullName>
                </value>
                <value>
                    <fullName>Net Price Received</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Validated</fullName>
                </value>
                <value>
                    <fullName>Abandoned</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Pricing Request</label>
    <nameField>
        <displayFormat>PR:{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Request Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pricing Requests - System</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/batchDeletionOfAbandonedRequest.cls
/*
 * Name		 :   batchProjectStatusChange
 * Description  :   
 * Author	   :   Infosys Limited
 * Created Date :   Anand Darshi
 *
 * Version	 Modified Date	   Modified By   			  Modification
 *
 * ---------------------------------------------------------------------------------------------------- 
 */
 global class batchDeletionOfAbandonedRequest implements Database.Batchable<sObject>
 {
	public Date vt=System.today();
	public string startQuery = 'SELect id FROM Pricing_Request__c WHERE Request_Approval_Status__c=\'Abandoned\' and CreatedDate <LAST_N_DAYS:29';
	global Database.QueryLocator start(Database.BatchableContext BC)
	{ 
		return Database.getQueryLocator(startQuery);	
	}
	global void execute(Database.BatchableContext BC, List<sObject> returnedRequestsFromQuery)
	{
		if(returnedRequestsFromQuery.size()>0)
		{   
			delete returnedRequestsFromQuery;
		}	
	}
	global void finish(Database.BatchableContext BC)
	{
	} 
}