objects/Sales_Prices__c.object
<CustomObject>
    <fields>
        <fullName>BU__c</fullName>
        <externalId>true</externalId>
        <label>BU</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Combination__c</fullName>
        <label>Key Combination</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sales_Org_Code__c</fullName>
        <label>Sales Org. Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isPriceHolder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isPriceHolder</label>
        <type>Checkbox</type>
    </fields>
    <label>Sales Prices - Non SAP</label>
    <nameField>
        <displayFormat>SPNSAP:{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Sales Prices - Non SAP Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Prices - Non SAP</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/batchClassForHolderNonSAP_UT.cls
@isTest
public class batchClassForHolderNonSAP_UT {
    static testmethod void batchClassForHolderNonSAPTestMethod() {
        Sales_Prices__c sp = new Sales_Prices__c();
        sp.BU__c = 'BI AP Surfaces';
        sp.isPriceHolder__c = false;
        sp.Sales_Org_Code__c = 'A603';
        sp.Key_Combination__c = 'Sales Org./Material';
    
        Sales_Prices__c sp1 = new Sales_Prices__c();
        sp1.BU__c = 'BI AP Surfaces';
        sp1.isPriceHolder__c = false;
        sp1.Sales_Org_Code__c = 'A603';
        sp1.Key_Combination__c = 'Sales Org./Material';
        
    list<sObject> s =new list<Sales_Prices__c>();
    s.add(sp);
    s.add(sp1);
    
    upsert s;
    test.startTest();
    batchClassForHolderNonSAP bc = new batchClassForHolderNonSAP();
    Database.executeBatch(bc, 200);
    test.stopTest();
    }
}