objects/User_Access_Review__c.object
<CustomObject>
    <description>Overall Umbrella/Container Object for the Audit Process</description>
    <fields>
        <fullName>Snapshot_Date__c</fullName>
        <description>Date on which Snapshot is taken</description>
        <inlineHelpText>Enter Date on which Snapshot is taken for Both Prod and Util Org</inlineHelpText>
        <label>Snapshot Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Snapshot_Status__c</fullName>
        <description>To capture the state of Snapshot Process</description>
        <inlineHelpText>Enter state in which Snapshot Process is</inlineHelpText>
        <label>Snapshot Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Snapshot_Taken_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The person who has taken snapshot of prod.</description>
        <inlineHelpText>Enter user name who is responsible for taking snapshot for audit process</inlineHelpText>
        <label>Snapshot Taken By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Processes1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Access Review</label>
    <nameField>
        <label>Audit Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Access Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AUATakeSnapshot.cls
/******************************************************************************* 
Copyright © 2016 DuPont. All rights reserved. 
Author: Abhinav Bhatnagar
Email: abhinav.bhatnagar@dupont.com
Description:  Class for Taking Snapshot of User Information in object User Access Review Details Custom Object
through a batch class batchAUATakeSnapshot
********************************************************************************/
global class AUATakeSnapshot {
    private static final integer MAXROWS = Limits.getLimitQueryRows();
    webservice static AsyncApexJob startSnapshotProcess(Id AuditProcessId) {
        return captureUserInfo(AuditProcessId);
    }
    
    private static AsyncApexJob captureUserInfo(Id AuditProcessId){        
        try{
            User_Access_Review__c uar = [Select id,name,Snapshot_Date__c,Snapshot_Status__c,Snapshot_Taken_By__c From User_Access_Review__c where Id = : AuditProcessId Limit :MAXROWS];
            uar.Snapshot_Status__c='In Progress';
            uar.Snapshot_Taken_By__c= UserInfo.getUserId();
            upsert uar;
            
            ID batchprocessid = Database.executeBatch(new batchAUATakeSnapshot(AuditProcessId),50);            
            return [SELECT Id, Status, JobItemsProcessed, TotalJobItems, NumberOfErrors 
                    FROM AsyncApexJob WHERE ID =: batchprocessid Limit :MAXROWS];
           
        }catch(Exception e){
            System.debug('Exception Occured');
            e.getStackTraceString();           
        }
        
         return null;
    }
}