objects/User.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <description>This is the Salesforce.com program that the end user is associated with. It is used for reporting, etc.</description>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Adhesives &amp; Fluids</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>BI-AP</fullName>
                </value>
                <value>
                    <fullName>BI-EU</fullName>
                </value>
                <value>
                    <fullName>BI-LA</fullName>
                </value>
                <value>
                    <fullName>BI-NA</fullName>
                </value>
                <value>
                    <fullName>CPC</fullName>
                </value>
                <value>
                    <fullName>DCF</fullName>
                </value>
                <value>
                    <fullName>DCF-AP</fullName>
                </value>
                <value>
                    <fullName>DCF-EMEA</fullName>
                </value>
                <value>
                    <fullName>DCF-LA</fullName>
                </value>
                <value>
                    <fullName>DCF-NA</fullName>
                </value>
                <value>
                    <fullName>DEC</fullName>
                </value>
                <value>
                    <fullName>DEC-APT</fullName>
                </value>
                <value>
                    <fullName>DEC-AUTH</fullName>
                </value>
                <value>
                    <fullName>DEC-CMPT</fullName>
                </value>
                <value>
                    <fullName>DEC-CPM</fullName>
                </value>
                <value>
                    <fullName>DEC-DM</fullName>
                </value>
                <value>
                    <fullName>DEC-HLTH</fullName>
                </value>
                <value>
                    <fullName>DEC-ICS</fullName>
                </value>
                <value>
                    <fullName>DEC-LED Silicones</fullName>
                </value>
                <value>
                    <fullName>DEC-Litho</fullName>
                </value>
                <value>
                    <fullName>DEC-MCM</fullName>
                </value>
                <value>
                    <fullName>DEC-OLED</fullName>
                </value>
                <value>
                    <fullName>DEC-PG</fullName>
                </value>
                <value>
                    <fullName>DEC-PVFM</fullName>
                </value>
                <value>
                    <fullName>DEC-Semi Silicones</fullName>
                </value>
                <value>
                    <fullName>DEC-SL</fullName>
                </value>
                <value>
                    <fullName>DEI-ACST</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>Primary &quot;Owning Organisation&quot; this user belongs to</description>
        <label>User Owning Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AGCP-CPC</fullName>
                </value>
                <value>
                    <fullName>BI</fullName>
                </value>
                <value>
                    <fullName>CORP</fullName>
                </value>
                <value>
                    <fullName>DCF</fullName>
                </value>
                <value>
                    <fullName>DEC</fullName>
                </value>
                <value>
                    <fullName>DPP</fullName>
                </value>
                <value>
                    <fullName>DPT</fullName>
                </value>
                <value>
                    <fullName>DSS</fullName>
                </value>
                <value>
                    <fullName>DTT</fullName>
                </value>
                <value>
                    <fullName>FIN</fullName>
                </value>
                <value>
                    <fullName>HR</fullName>
                </value>
                <value>
                    <fullName>IB</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>LEGL</fullName>
                </value>
                <value>
                    <fullName>M&amp;S</fullName>
                </value>
                <value>
                    <fullName>M&amp;S-IT</fullName>
                </value>
                <value>
                    <fullName>N&amp;H</fullName>
                </value>
                <value>
                    <fullName>P&amp;IP</fullName>
                </value>
                <value>
                    <fullName>PNR</fullName>
                </value>
                <value>
                    <fullName>Adhesives &amp; Fluids</fullName>
                </value>
                <value>
                    <fullName>Multibase</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/User_Access_Review__c.object
<CustomObject>
    <description>Overall Umbrella/Container Object for the Audit Process</description>
    <fields>
        <fullName>Process_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who is owner of the Audit Process and is functionality administrator.</description>
        <inlineHelpText>User who is owner of the Audit Process and is functionality administrator.</inlineHelpText>
        <label>Process Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Starting Date for Audit Process</description>
        <inlineHelpText>Enter Start Date for Audit Process</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>User Access Review</label>
    <nameField>
        <label>Audit Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Access Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/User_Access_Review_Details__c.object
<CustomObject>
    <description>To Capture User Security Details for Audit Purpose</description>
    <fields>
        <fullName>Approval__c</fullName>
        <description>Approval Status</description>
        <inlineHelpText>Approval Status</inlineHelpText>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Reviewed</fullName>
                    <default>true</default>
                    <label>Not Reviewed</label>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Modify</fullName>
                </value>
                <value>
                    <fullName>De-Activate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Approver</description>
        <inlineHelpText>Approver</inlineHelpText>
        <label>Approver</label>
        <referenceTo>User</referenceTo>
        <relationshipName>User_Access_Review_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Audit_Process__c</fullName>
        <description>Audit Process</description>
        <inlineHelpText>Audit Process</inlineHelpText>
        <label>Audit Process</label>
        <referenceTo>User_Access_Review__c</referenceTo>
        <relationshipName>User_Information_Audit_Data</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <description>CompanyName</description>
        <inlineHelpText>CompanyName</inlineHelpText>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org__c</fullName>
        <description>Org</description>
        <inlineHelpText>Org</inlineHelpText>
        <label>Org</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>One-DuPont</fullName>
                </value>
                <value>
                    <fullName>DuPont Utility</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>Program</description>
        <inlineHelpText>Program</inlineHelpText>
        <label>Program</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Review_Date__c</fullName>
        <description>Review Date</description>
        <inlineHelpText>Review Date</inlineHelpText>
        <label>Review Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User_Email_Id__c</fullName>
        <description>Email Id</description>
        <inlineHelpText>Email Id</inlineHelpText>
        <label>Email Id</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>User_Grouping__c</fullName>
        <description>User Grouping</description>
        <label>Grouping</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <description>User ID in system</description>
        <inlineHelpText>User Id in system</inlineHelpText>
        <label>User Id</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <label>User Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Owning_Org__c</fullName>
        <description>User Owning Org</description>
        <inlineHelpText>User Owning Org</inlineHelpText>
        <label>Owning Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Owning_SBU_Org__c</fullName>
        <description>User Owning SBU Org</description>
        <inlineHelpText>User Owning SBU Org</inlineHelpText>
        <label>Owning SBU Org</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Permission_Sets__c</fullName>
        <description>User Permission Sets</description>
        <inlineHelpText>User Permission Sets</inlineHelpText>
        <label>Permission Sets</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Profile__c</fullName>
        <description>User Profile</description>
        <inlineHelpText>User Profile</inlineHelpText>
        <label>Profile</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Public_Group__c</fullName>
        <description>User Public Group</description>
        <inlineHelpText>User Public Group</inlineHelpText>
        <label>Public Group</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Roles__c</fullName>
        <description>User Roles</description>
        <inlineHelpText>User Roles</inlineHelpText>
        <label>Roles</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>User_Type__c</fullName>
        <description>User Type</description>
        <inlineHelpText>User Type</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>DuPont Employee</fullName>
                </value>
                <value>
                    <fullName>Non-Employee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User_ePass_Id__c</fullName>
        <description>ePass Id</description>
        <inlineHelpText>ePass Id</inlineHelpText>
        <label>ePass Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>User Access Review Details</label>
    <nameField>
        <label>User Information Audit Data Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Access Review Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ctrlAUAReviewPage_UT.cls
/*******************************************************************************
Copyright © 2016 DuPont. All rights reserved. 
Author: Abhinav Bhatnagar
Email: abhinav.bhatnagar@dupont.com
Description:  Unit Test for ctrlAUAReviewPage
********************************************************************************/
@isTest
//Merge&Spin - Removed SeeAllData
//(SeeAllData=true)

private class ctrlAUAReviewPage_UT {
        
    public static testMethod void LoadData() {
        Test.startTest();
        User_Access_Review__c uar = new User_Access_Review__c(name='Test User Access Review Audit 2016',Process_Owner__c=UserInfo.getUserId(), Start_Date__c=Date.today());
        Insert uar;
        
        User_Access_Review_Details__c uard = new User_Access_Review_Details__c(CompanyName__c='DUPONT (THAILAND) LIMITED',Program__c='CPC',User_Owning_Org__c='AGCP-CPC' ,User_Owning_SBU_Org__c='Crop Protection',Approval__c='De-Activate',Approver__c=UserInfo.getUserId(),Audit_Process__c=uar.id,Review_Date__c=Date.today(),Name='Test User1',Org__c='DuPont',User_Email_Id__c='Test1@test.com',User_Id__c=UserInfo.getUserId(),User_ePass_Id__c='test4234',User_Name__c=Userinfo.getFirstName()+','+UserInfo.getLastName(),User_Permission_Sets__c='Test',User_Profile__c='Test',User_Public_Group__c='Test',User_Roles__c='Test',User_Type__c='Test',User_Grouping__C='CPC',User_Country__c='India', User_Region__c='Asia Pacific');
        User_Access_Review_Details__c uard1 = new User_Access_Review_Details__c(CompanyName__c='DUPONT (THAILAND) LIMITED',Program__c='CPC',User_Owning_Org__c='AGCP-CPC' ,User_Owning_SBU_Org__c='Crop Protection',Approval__c='De-Activate',Approver__c=UserInfo.getUserId(),Audit_Process__c=uar.id,Review_Date__c=Date.today(),Name='Test User2',Org__c='DuPont',User_Email_Id__c='Test2@test.com',User_Id__c=UserInfo.getUserId(),User_ePass_Id__c='test4235',User_Name__c=Userinfo.getFirstName()+','+UserInfo.getLastName(),User_Permission_Sets__c='Test',User_Profile__c='Test',User_Public_Group__c='Test',User_Roles__c='Test',User_Type__c='Test',User_Grouping__C='CPC',User_Country__c='India', User_Region__c='Asia Pacific');
        User_Access_Review_Details__c uard2 = new User_Access_Review_Details__c(CompanyName__c='DUPONT (THAILAND) LIMITED',Program__c='CPC',User_Owning_Org__c='AGCP-CPC' ,User_Owning_SBU_Org__c='Crop Protection',Approval__c='De-Activate',Approver__c=UserInfo.getUserId(),Audit_Process__c=uar.id,Review_Date__c=Date.today(),Name='Test User3',Org__c='DuPont',User_Email_Id__c='Test3@test.com',User_Id__c=UserInfo.getUserId(),User_ePass_Id__c='test4236',User_Name__c=Userinfo.getFirstName()+','+UserInfo.getLastName(),User_Permission_Sets__c='Test',User_Profile__c='Test',User_Public_Group__c='Test',User_Roles__c='Test',User_Type__c='Test',User_Grouping__C='CPC',User_Country__c='India', User_Region__c='Asia Pacific');
        List<User_Access_Review_Details__c> uards = new List<User_Access_Review_Details__c>();
        uards.add(uard);
        uards.add(uard1);
        uards.add(uard2);
        
        insert uards;
        
        apexpages.currentpage().getparameters().put('Id',uar.id);
        executeTest(uar);
        Test.stopTest();
    }
    
    public static  void executeTest(User_Access_Review__c uar) {
        testTakeSnapshot(uar); 
        testAUAReviewPageController();
    }
    
    public static  void testAUAReviewPageController()    
    {
        ctrlAUAReviewPage carp = new ctrlAUAReviewPage(); 
        carp.oname = 'User Access Review Details';
        carp.getUserAccessReviewDetails('NAME','DESC');
        
        carp.showfields();    
        loadFields(carp);
        
        Apexpages.Currentpage().getParameters().put('callingFrom','showRecords');
        carp.refreshTable();
        carp.sortbyField = 'Name';
        carp.sortDirection = 'ASC';
        Apexpages.Currentpage().getParameters().put('callingFrom','showRecords');
        carp.refreshTable();
        
        testPagination(carp);
    }
    
    public static  void testTakeSnapshot(User_Access_Review__c uar) {
        AUATakeSnapshot.startSnapshotProcess(uar.id);
    }
    
    public static void testPagination(ctrlAUAReviewPage carp){
        carp.getFields();
        Apexpages.Currentpage().getParameters().put('callingFrom','Beginning');
        carp.refreshTable();
        Apexpages.Currentpage().getParameters().put('callingFrom','Next');
        carp.refreshTable();
        Apexpages.Currentpage().getParameters().put('callingFrom','Next');
        carp.refreshTable();
        Apexpages.Currentpage().getParameters().put('callingFrom','Previous');
        carp.refreshTable();
        Apexpages.Currentpage().getParameters().put('callingFrom','End');
        carp.refreshTable();
        
        carp.getDisablePrevious(); 
        carp.getDisableNext();  
        carp.getTotal_size(); 
        carp.getPageNumber();
        carp.sortTable();
        
        String strMyList = carp.myList;
        carp.cancel();
        carp.showpage = String.valueOf(2);
        
        Apexpages.Currentpage().getParameters().put('callingFrom','changePage');
        carp.refreshTable();
        
        carp.columnLabels[0].getName();
        carp.columnLabels[0].getLabel();
        carp.save();
    }
    
    
    public static void loadFields(ctrlAUAReviewPage carp){
        carp.finalsFields = new String[]{};
            for(String s:carp.fieldsMap.Keyset()){
                carp.finalsFields.add(carp.fieldsMap.get(s));
            }
    }
    
    
}