objects/User_Access_Review__c.object
<CustomObject>
    <description>Overall Umbrella/Container Object for the Audit Process</description>
    <fields>
        <fullName>Process_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who is owner of the Audit Process and is functionality administrator.</description>
        <inlineHelpText>User who is owner of the Audit Process and is functionality administrator.</inlineHelpText>
        <label>Process Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Audit_Processes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>Starting Date for Audit Process</description>
        <inlineHelpText>Enter Start Date for Audit Process</inlineHelpText>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>User Access Review</label>
    <nameField>
        <label>Audit Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Access Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/batchAUATakeSnapshot_UT.cls
/*******************************************************************************
Copyright © 2016 DuPont. All rights reserved. 
Author: Abhinav Bhatnagar
Email: abhinav.bhatnagar@dupont.com
Description:  Unit Test for batchAUATakeSnapshot
********************************************************************************/
@isTest
public class batchAUATakeSnapshot_UT {
    public static testMethod void LoadData() {
        User_Access_Review__c uar = new User_Access_Review__c(name='Test User Access Review Audit 2016',Process_Owner__c=UserInfo.getUserId(), Start_Date__c=Date.today());
        Insert uar;
        executeTest(uar);
    }
    
    public static  void executeTest(User_Access_Review__c uar) {
        Test.startTest();
         ID batchprocessid = Database.executeBatch(new batchAUATakeSnapshot(uar.id),50);
        Test.stopTest();
    }

}